### ISSUE TITLE
Library function name suggested over language statement keyword

### ISSUE THREAD

**Issue by wesinator** [atom/autocomplete-plus#1012]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Seems imported/included library function names are suggested over language statement keywords in autocompletion.

### Steps to Reproduce

1. Start a C file
```c
#include <openssl/evp.h>
```
2. type `else`

**Expected behavior:** `else` suggested if keywords are supposed to be suggested, or nothing is suggested

**Actual behavior:** Autocomplete tries to correct `else` statement keyword to the `OPENSSL_assert` function from the include
![else_autocomplete](https://user-images.githubusercontent.com/5124946/49599477-226b7380-f94f-11e8-8925-9df7ec14bc76.png)

**Reproduces how often:** Always

### Versions
1.32.2 x64
language-c 0.60.13

**Comment by rsese** [comment]
Thanks for the report!  I think this is the built-in provider and fuzzy matching at work?

If you enable `Settings > Packages > autocomplete-plus > Use Strict Matching For Built-in Provider`, you won't see suggestions like this.  Let us know if that helps.

**Comment by wesinator** [comment]
Weird, I can't reproduce in 1.33.0

**Comment by rsese** [comment]
Do you have the file open with that function name?  You can reproduce with just this content once you start typing `else` after the `if`:

```c
int main() {}
  int OPENSSL_assert = 1;

  if (1 == 1) {
  } 
}
```

That's the built-in provider suggesting words from open files.

You can disable that behavior in general by disabling `Settings > Packages > autocomplete-plus > Enable Built-in Provider` or you can enable the other setting I mentioned above.

**Comment by wesinator** [comment]
`Use Strict Matching For Built-in Provider` fixes it.


> Do you have the file open with that function name? You can reproduce with just this content once you start typing `else` after the `if`:
> 
> ```c
> int main() {}
>   int OPENSSL_assert = 1;
> 
>   if (1 == 1) {
>   } 
> }
> ```

@rsese `OPENSSL_assert` is a function name defined from the include, not a declared variable.

**Comment by rsese** [comment]
> `Use Strict Matching For Built-in Provider` fixes it.

:+1:

> @rsese `OPENSSL_assert` is a function name defined from the include, not a declared variable.

We just needed the text itself, for autocomplete's built-in provider it doesn't matter what the string is in the program, it's just looking at the text (see the description of `Settings > Packages > autocomplete-plus > Enable Built-In Provider`).  E.g. I can also reproduce with this as I type `else` if I don't have `Use Strict Matching For Built-in Provider` enabled:

```c
int add(int OPENSSL_assert);

int main() {}
  if (1 == 1) {
  } else
}
```

Going to go ahead and close since that autocomplete-plus setting helped you in this particular case.
