### ISSUE TITLE
AutoComplete-plus picks letters from other completion entries to suggest from

### ISSUE THREAD

**Issue by michael-gracy** [atom/autocomplete-plus#1024]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

AutoComplete-plus picks letters from other completion entries to suggest from

### Steps to Reproduce

1. Open file as Plain Text or Shell Script (haven't tested elsewhere, but will probably work anywhere else)
2. Type in a item like SYM_DB_HOSTNAME and save the file
3. In a new tab, same as before, type 'done' (no quotes), suggestion will be made up of D...O...N..E highlighted from 'SYM_DB_HOSTNAME' instead of 'done'.

**Expected behavior:** to see the word 'done' as the topmost suggestion when typing the complete word (by habit)

**Actual behavior:** See step 3 above

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15
git 2.21.0

autocomplete-plus@2.42.0

MacOS 10.13.6

### Additional Information

This is reproducible in standard and safe modes.

**Comment by michael-gracy** [comment]
The first screenshot is from standard mode (plain text doc):
![screen shot 2019-03-05 at 2 29 30 pm](https://user-images.githubusercontent.com/21319707/53842519-9e785600-3f54-11e9-8167-5d40bdc8fd4f.png)

This second screenshot is from safe mode (same doc, shell script doc):
![screen shot 2019-03-05 at 2 03 59 pm](https://user-images.githubusercontent.com/21319707/53842524-a33d0a00-3f54-11e9-8309-5ae9bc6e7def.png)

**Comment by rsese** [comment]
Thanks for the report!  This is the default behavior of the built-in autocomplete provider which provides suggestions from open files by default - you can turn off this fuzzy matching by enabling `Settings > Packages > Autocomplete Plus > Use Strict Matching For Built-In Provider`.

![strict-matching](https://github-slack.s3.amazonaws.com/monosnap/shell.sh__worktest-tree-sitter_2019-03-13_21-14-57.png)

Going to go ahead and close but let me know if I'm misunderstanding anything.
