### ISSUE TITLE
Words with umlauts are ignored even with extended Unicode support enabled

### ISSUE THREAD

**Issue by rseichter** [atom/autocomplete-plus#1026]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Words with umlauts (like `repräsentativ`or `Möhre`) are not offered in autocompletion even when extended Unicode support is enabled via the plugin settings menu. Was this not supposed to be fixed with #667 about three years ago?

### Steps to Reproduce

1. Enable extended Unicode support in plugin settings.
2. Restart Atom.
3. Enter some text containing words with German umlauts (`ä ö ü Ä Ö Ü ß`).
4. Begin typing these words to trigger autocompletion.

**Expected behavior:** [What you expect to happen]

Autocompletion should offer words with umlauts.

**Actual behavior:** [What actually happens]

Autocompletion ignores words with umlauts.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

macOS 10.14.3 (Mojave)
```
> atom --version
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

> apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 3.7.2
git 2.21.0
```

**Comment by rsese** [comment]
Thanks for the report!  I was unable to reproduce with 1.35.1 on macOS 10.12.6 in safe mode:

![ac-unicode](https://github-slack.s3.amazonaws.com/monosnap/untitled__workself_2019-04-09_02-41-43.png)

Am I missing anything to reproduce?

**Comment by rsese** [comment]
:smile:  🐴 🎁 

Since things are looking ok for you now we'll go ahead and close - if this issue shows up again though, please let us know :v:
