### ISSUE TITLE
java autocomplete not working on fresh install of Atom

### ISSUE THREAD

**Issue by mattjcl** [atom/autocomplete-plus#1031]
### Description

Autocomplete suggestions are not appearing aside from those provided by the snippets extension.

### Steps to Reproduce

1. Install atom.io.
2. create and save a .java file.

**Reproduces how often:**
100%

### Expected Behaviour

code suggestions should be offered while typing e.g. "thr" --> "throws"

### Actual Behaviour

code suggestions are not offered.
### Versions

Atom 1.36.0
macOS Mojave 10.14.4

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Aerijo** [comment]
> Expected behavior: [What you expect to happen]
> 
> Actual behavior: [What actually happens]

@mattjcl You've forgotten to fill these out. Especially regarding what you were expecting.
