### ISSUE TITLE
Autocomplete suggest bads entries

### ISSUE THREAD

**Issue by Adri1G** [atom/autocomplete-plus#1037]
# Description

In a C and C++ file, when I write an end-line like return 0;, autocomplete suggest ⚃^㱋x:饬ኡj'꧵T☽O㔬RO婎?향ᒭ搩$渣y4i;(Q>꿘e8q": "j~錘}0g;L萺*;ᕭꄮ0l潛烢5H▄쳂ꏒוֹꙶT犘≫x閦웧v",. for example.
I deactivate packages one by one  and this problem disappears when this package is disabled.

### Steps to Reproduce

1. write return 0;

**Expected behavior:** nothing or relevant keyword

**Actual behavior:** suggest string like ;⚃^㱋x:饬ኡj'꧵T☽O㔬RO婎?향ᒭ搩$渣y4i;(Q>꿘e8q": "j~錘}0g;L萺*;ᕭꄮ0l潛烢5H▄쳂ꏒוֹꙶT犘≫x閦웧v"

**Reproduces how often:** every time

### Versions

Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

This behavior appear without a configuration change.

Installed packages:
atom-ctags
autocomplete-ctags
linter

**Comment by rsese** [comment]
Thanks for the report!  It looks like the `Prerequisites` section has been removed, did this reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) with all core packages re-enabled? 

Also, do you have other files open or can you reproduce with just a new empty file?

**Comment by Adri1G** [comment]
Thank you for the answer.
I have three open project.
I do not have the problem when
- I start atom in safe mode with all core packages enable
- I open a new windows and a new file to test

**Comment by Adri1G** [comment]
I think the probleme come from atom-ctags. Thank you for your help rsese!
