### ISSUE TITLE
Autocomplete don't work within the tags (still)

### ISSUE THREAD

**Issue by sanada01** [atom/autocomplete-plus#1062]
Hi Guys!

This problem detected in 2017. We have been waiting for the fix ever since, very annoying mistake.

[Autocomplete don't work within the tags](https://github.com/atom/autocomplete-plus/issues/1029)
[a tag does not autocomplete in some specific cases](https://github.com/atom/autocomplete-plus/issues/932)

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python
git 2.20.1.windows.1
visual studio

Please, please, please, please, please, please, please, please, please, please, please fix it, :'(

**Comment by rsese** [comment]
Thanks for reaching out - please don't create duplicate issues to remind us of open issues.  We're aware that there are open issues but with finite resources, we're only able to resolve a finite number of items.

We're happy to review a well-written pull request however, that would be most helpful for addressing open issues.

Closing in favor of https://github.com/atom/autocomplete-plus/issues/932.
