### ISSUE TITLE
"Keymap for Confirming a Suggestion" option not working

### ISSUE THREAD

**Issue by pmalonis** [atom/autocomplete-plus#1066]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
"Keymap for Confirming a Suggestion" option not working

### Steps to Reproduce

Go to settings for the package. Select "Keymap for Confirming a Suggestion" to any of the options that do not include enter (including "None")

**Expected behavior:**
Enter should not confirm a suggestion except when certain Keymap options are selected

**Actual behavior:**

Enter confirms selection, including when "None" is selected. However, if I select "Enter" or "None" then Tab does not confirm the selection.

**Reproduces how often:**
Every time.

### Versions
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
apm  2.4.3

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce with 1.40.1 on macOS 10.14.6, I tried setting to `Tab` and `None` and in both cases, <kbd>Enter</kbd> doesn't confirm a suggestion for me.

Did Atom behave exactly the same when you tried in safe mode?  Also, what operating system are you running?

**Comment by grussy** [comment]
I can confirm this behaviour on ubuntu linux 
atom --version : 1.35.1

Tried in safe mode: Here the behaviour is as expected, <kbd>Enter</kbd> does not confirm suggestions.

Installed Packages:
advanced-open-file 
emacs-plus

Disabling the emacs-plus package solves the problem.

**Comment by rsese** [comment]
Thanks :+1:

> Disabling the emacs-plus package solves the problem.

You can open an issue on their repository: https://atom.io/packages/emacs-plus.  Then if there's a problem on the Atom side, they can either fix the problem or tell us where the problem is coming from. 

Are you also using emacs-plus @pmalonis?

As a side note:

> atom --version : 1.35.1

The current stable version of Atom is 1.41.0 so I'd suggest updating if possible.
