### ISSUE TITLE
Autocomplete don't work within the tags 

### ISSUE THREAD

**Issue by sanada01** [atom/autocomplete-plus#1068]
Hi guys!

### Description

This bug is frustrating. 
This bug is irritating.
This bug is long present.
This bug is disappointing.

### Steps to Reproduce

1. Open a new .html file
2. Open a li tag, and open a tag within li tag

![33762836-6d991844-dc0e-11e7-927f-6c6c93067786](https://user-images.githubusercontent.com/28780118/56117442-5c393000-5f68-11e9-9d97-97e4185b4661.gif)

**Reproduces how often:** 100%

### Versions

Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python
git 2.20.1.windows.1
visual studio

### Additional Information

[Prevent issue is closed.](https://github.com/atom/autocomplete-plus/issues/932) Please fix it.

**Comment by icecream17** [comment]
Note to self: this is an open issue
