### ISSUE TITLE
Overriding default keymaps doesn't seem to work

### ISSUE THREAD

**Issue by ilanbiala** [atom/autocomplete-plus#112]
I'm somewhat new to remapping in Atom, so I may be forgetting something, but based on reading the Atom documentation I think I did everything.

I'm trying to remap the `autocomplete-plus:confirm` command to the enter key, but I can't seem to get it working. In my keymap.cson file, I have tried:

```
'.autocomplete-plus':
  'enter': 'autocomplete-plus:confirm'
```

'.autocomplete-plus input.hidden-input':
  'enter': 'autocomplete-plus:confirm'

```

but neither seem to allow me to press enter instead of tab. Is there something I'm missing?
```

**Comment by anjerodesu** [comment]
With the latest update, this worked for me
``` coffee
'.autocomplete-plus':
  'tab': 'unset!' # optional
  'enter': 'autocomplete-plus:confirm'
```

**Comment by joefitzgerald** [comment]
Please see: https://github.com/atom-community/autocomplete-plus/blob/master/README.md#usage
