### ISSUE TITLE
Add option to use tab to cycle through completions 

### ISSUE THREAD

**Issue by gglanzani** [atom/autocomplete-plus#12]
The arrows are quite far from the home-row :smile:

**Comment by roychoo** [comment]
for the latest version to use tab to cycle through suggestions
```
'atom-text-editor.autocomplete-active':
  'tab': 'core:move-down'
```

**Comment by timofurrer** [comment]
@roychoo This does not work me.
I want to change the key to cycle through the suggested items to tab and the confirm I want to have enter. How can I do this with Atom v1.0.19?

**Comment by roychoo** [comment]
@timofurrer hmmm did you set the settings if autocomplete-plus package?
![image](https://cloud.githubusercontent.com/assets/1853311/10384519/0469c846-6e6f-11e5-8329-bde097bb0020.png)

**Comment by banjocat** [comment]
The instructions to do this were added in the settings for autocomplete-plus within atom. It even gives sample keymap.cson values to use as well.

It worked as expected when I tried it.
