### ISSUE TITLE
change keystroke

### ISSUE THREAD

**Issue by frenci8** [atom/autocomplete-plus#152]
i would like to change the keystroke of autocomplete-plus:confirm from tab to enter, but I do not see this option. Any idea how this can be done? 

Thanks

**Comment by ianrose14** [comment]
@yongkangchen this does not work for me - any ideas?

I have only one entry in my keymap.cson:

".autocomplete-plus input.hidden-input":
  "enter": "autocomplete-plus:confirm"

When I go to keybindings and search for "autocomplete" I see only two entries which copy as:

'atom-text-editor':
  'ctrl-shift-space': 'autocomplete-plus:activate'

and

'.autocomplete-plus input.hidden-input':
  'enter': 'autocomplete-plus:confirm'

If I press tab on an autocomplete entry, it works.  If I press enter, however, I just get a newline in the document.
