### ISSUE TITLE
Installing “autocomplete-plus@1.1.0” failed

### ISSUE THREAD

**Issue by fpcorso** [atom/autocomplete-plus#185]
I have tried multiple times to install this package from within Atom and it always fails.  Here is the output:

npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/grim/-/grim-0.13.0.tgz
npm http 200 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/fuzzaldrin
npm http 304 https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/fuzzaldrin/-/fuzzaldrin-2.1.0.tgz
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-2.0.1.tgz
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http 200 https://registry.npmjs.org/grim/-/grim-0.13.0.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-2.0.1.tgz
npm http 200 https://registry.npmjs.org/fuzzaldrin/-/fuzzaldrin-2.1.0.tgz
npm http 200 https://registry.npmjs.org/async/-/async-0.9.0.tgz
npm http GET https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/underscore
npm http 200 https://registry.npmjs.org/coffeestack
npm http 304 https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/coffeestack/-/coffeestack-0.7.0.tgz
npm http 200 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.0.tgz
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\bin\\node.exe" "c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\npm-cli.js" "--globalconfig" "c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\.apmrc" "--userconfig" "C:\Users\Frank\.atom\.apmrc" "install" "C:\Users\Frank\AppData\Local\Temp\d-1141131-8096-1wcsmia\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-8096-11kkn5j
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 200 https://registry.npmjs.org/coffeestack/-/coffeestack-0.7.0.tgz
npm http 304 https://registry.npmjs.org/property-accessors
npm http 200 https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.0.tgz
npm http 304 https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 200 https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/coffee-script/-/coffee-script-1.7.1.tgz
npm http 200 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.41.tgz
npm http 200 https://registry.npmjs.org/balanced-match
npm http 200 https://registry.npmjs.org/concat-map/0.0.1
npm http 200 https://registry.npmjs.org/coffee-script/-/coffee-script-1.7.1.tgz
npm http GET https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http GET https://registry.npmjs.org/balanced-match/-/balanced-match-0.2.0.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.41.tgz
npm http 200 https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 200 https://registry.npmjs.org/balanced-match/-/balanced-match-0.2.0.tgz
npm http GET https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/mkdirp
npm http 200 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz
npm http 200 https://registry.npmjs.org/amdefine/-/amdefine-0.1.0.tgz
npm

**Comment by fpcorso** [comment]
I installed git as you said; however, I am still receiving an error. This one does not mention git.

Copied output:

**Comment by fpcorso** [comment]
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/fuzzaldrin
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/fuzzaldrin
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/coffeestack
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/coffee-script
npm ERR! Error: ENOENT, open 'C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-5184-e1mdpt\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\test\sequence.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-5184-xgaaes\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-5184-e1mdpt
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-5184-e1mdpt\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\test\sequence.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat 'C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-5184-e1mdpt\node_modules\autocomplete-plus\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\emitter.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-5184-xgaaes\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-5184-e1mdpt
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-5184-e1mdpt\node_modules\autocomplete-plus\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\emitter.js
npm ERR! fstream_path C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-5184-e1mdpt\node_modules\autocomplete-plus\node_modules\event-kit\node_modules\grim\node_modules\emissary\lib\emitter.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Frank\AppData\Local\atom\app-0.165.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/mixto
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Frank\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Frank\\.atom\\.apmrc" "install" "C:\\Users\\Frank\\AppData\\Local\\Temp\\d-1141131-5184-xgaaes\\package.tgz" "--target=0.18.0" "--arch=ia32"
npm ERR! cwd C:\Users\Frank\AppData\Local\Temp\apm-install-dir-1141131-5184-e1mdpt
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 200 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/source-map/-/source-map-0.1.42.tgz
npm http 200 https://registry.npmjs.org/source-map/-/source-map-0.1.42.tgz
npm http GET https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/mkdirp
npm

**Comment by joefitzgerald** [comment]
Still mentions git:

```
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
```

Happy new year!

**Comment by joefitzgerald** [comment]
Open a command prompt and type `git`. If it cannot be found, add the path to it to your PATH. Until you can type `git` in the command prompt and get got to run, you won't be able to install atom packages.

**Comment by fpcorso** [comment]
Ah, it's further down this time. I clearly overlooked it. Sorry to keep bothering you.

**Comment by joefitzgerald** [comment]
No worries.

**Comment by fpcorso** [comment]
I'm fairly new to this kind of thing. I downloaded the Git for Windows from your link. I followed a tutorial here: http://blog.countableset.ch/2012/06/07/adding-git-to-windows-7-path/ to add it to the PATH but I still cannot type git and get it to run. Any ideas as to where I should look?

**Comment by fpcorso** [comment]
Nevermind. I works now. Let me go try to install your package again. Thanks

**Comment by fpcorso** [comment]
Alrighty, sorry to keep bothering you. I installed a few other packages and they installed successfully. However, I still cannot get your package to install. I can now type git in the command prompt and it works; however, I am still receiving the errors when trying to install this package.

**Comment by joefitzgerald** [comment]
Paste the error you get now.

**Comment by fpcorso** [comment]
I decided to try rebooting the computer and that seems to have worked. I successfully installed the package and am using it now.

Sorry to have kept bothering you. It seems to have been just some user errors and ignorance. Thank you for your patience and time.

**Comment by finalxcode** [comment]
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.26 | win32 | ia32
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.11.10/node-v0.11.10.tar.gz
gyp WARN install got an error, rolling back install
