### ISSUE TITLE
Configurable "Accept" Key

### ISSUE THREAD

**Issue by Toady00** [atom/autocomplete-plus#20]
Other editors like Sublime Text allow you to disable "Accepting" a suggestion on enter. For example, I get to the end of a line, and hit enter to return to the next line, but there was a suggestion that gets accepted instead.

In ST when you disable accept on enter, if there is a suggestion when you hit enter, it just returns to the next line. This would be my preferred behavior.

**Comment by davelandry** [comment]
has this been added? if so, can someone post how to change this behavior?

**Comment by duozmo** [comment]
@davelandry Atom > Settings > Packages > autocomplete-plus > Settings > Keymap For Confirmation A Suggestion.

(Note, does not appear under Settings > Keybindings.)

**Comment by davelandry** [comment]
thanks @duozmo!

**Comment by deckar01** [comment]
Having "tab and enter" be the default "confirm" option seems odd. It has been annoying me for a year, and I just noticed it can be configured.

**Comment by stefankroes** [comment]
Agree, I've been annoyed with this for a long time before finally googling and finding this thread

**Comment by mossworks** [comment]
You're a lifesaver, @duozmo .  Or at least, a sanity-saver.  ;)

**Comment by zetolhousa** [comment]
You can also use **ctrl+enter** if you don't want to select the suggestion and go to the next line but also have the benefits of a simple **enter** when you want to select the suggestion. Works for me.
