### ISSUE TITLE
Remove enter as default confirmation key

### ISSUE THREAD

**Issue by lmartins** [atom/autocomplete-plus#24]
The tooltip with the suggestions shouldn't have an option selected by default.
Im using this with the "live completion" enabled, but because of the default selection I can't using in conjunction with emmet or even with my custom snippets. This happens because when I try to expand a snippet, most of the times there's a autocomplete suggestion that will expand instead.

**Comment by masaeedu** [comment]
@saschagehlich Is there a way we can configure it to not select an option in the dropdown unless you move down into it? This gets particularly annoying with JS objects, when all you want is a new line and the thing will autocomplete some (usually completely useless) suggestion ahead of your comma on the same line instead.

**Comment by joefitzgerald** [comment]
This is one of those tricky things where a default can never please anyone. You have the ability to change this in autocomplete-plus preferences, and you should do so. You can also set this via your keymap.

![screen shot 2015-06-24 at 10 03 40 am](https://cloud.githubusercontent.com/assets/744740/8335032/5557e320-1a58-11e5-87bf-330e3280e33c.png)

**Comment by geoffreywiseman** [comment]
This is literally the reason why I use VSCode more than Atom right now. Not having enter as a select key after I select something throws me off, because I hit enter and get a new line when I wanted a selection. Having something selected by default with enter enabled does too because I hit enter wanting a beeline and get something I didn’t deliberately select.

**Comment by geoffreywiseman** [comment]
Great -- I'll give this a shot. Thanks for letting me know.

**Comment by zetolhousa** [comment]
You can also use **ctrl+enter** if you don't want to select the suggestion and go to the next line but also have the benefits of a simple **enter** when you want to select the suggestion.

**Comment by jcbalmer** [comment]
@nyuszika7h Could you direct me to where the Keymap For Confirming A Suggestion is found? I am a new user, using using Atom 1.35.1 and haven't been able to locate this setting.

**Comment by rsese** [comment]
@jcbalmer it's at `Settings > Packages > Autocomplete Plus > Keymap For Confirming A Suggestion`.
