### ISSUE TITLE
Support for page down, page up, home end keyshortcut.

### ISSUE THREAD

**Issue by lygstate** [atom/autocomplete-plus#319]

**Comment by joefitzgerald** [comment]
This is already possible via your keymap. E.g.:

```cson
'atom-text-editor:not(mini).autocomplete-active':
  'tab': 'unset!'
  'enter': 'autocomplete-plus:confirm'
  'up': 'unset!'
  'down': 'unset!'
  'pageup': 'autocomplete-plus:select-previous'
  'pagedown': 'autocomplete-plus:select-next'
  'home': 'autocomplete-plus:select-previous'
  'end': 'autocomplete-plus:select-next'
```

@benogle we could probably add commands for `select-top` / `select-bottom` (or some synonyms).

**Comment by lygstate** [comment]
Yeap, this is possible, except not works as expected.

**Comment by joefitzgerald** [comment]
@lygstate could you please elaborate? _What_ does not work as expected? _How_ should things work, if working as expected?

**Comment by lygstate** [comment]
I hope page down will cause select-list-pagedown,
pageup cause select-list-pageup
and home navigate the list -top
end navigate the list-bottom,
