### ISSUE TITLE
There is a way to disable the tab hotkey of autocomplete-plus, but not of core?

### ISSUE THREAD

**Issue by xlaywan** [atom/autocomplete-plus#385]
```
'atom-text-editor:not([mini]).autocomplete-active':
   'tab': 'unset!'
```
This keymap disables all hotkeys for `tab`.

**UPD**: I've changed keymap for confirming via settings from tab to enter. And wrote into `keymaps.cson`:
```
'atom-text-editor:not([mini]) !important':
   'enter': 'editor:newline'
```
It seems that works.

**Comment by benogle** [comment]
Can you describe the problem a little more? I am not totally understanding.

Have you changed the option for `Keymap for confirming a selection`?

![screen shot 2015-04-13 at 10 59 29 am](https://cloud.githubusercontent.com/assets/69169/7121930/b7509000-e1cc-11e4-932f-e5c821f72a48.png)

**Comment by xlaywan** [comment]
This PR https://github.com/atom/atom/pull/6245 most likely will fix this issue. You can close this issue.
