### ISSUE TITLE
Are there any recommendations for tag completions?

### ISSUE THREAD

**Issue by DWand** [atom/autocomplete-plus#403]
Hello. I would like to add a list of completions for [apiDoc](https://github.com/apidoc/apidoc) syntax to Atom (probably, port [this Sublime Text plugin](https://github.com/DWand/SublimeText_apiDoc_autocompletion)). It seems that creating a provider for autocomplete-plus is a great way to accomplish this task (as it is easy, flexible and kinda declarative). Thank you for this package.

This syntax is like JavaDoc, JsDoc, PhpDoc, etc. So, I'd like to ask if there are any recommendations of how to build such kind of stuff.

*It worth to be mentioned that I've never used Atom before. I don't have any experience with its plugin system. So, I may be totally wrong.*

I've created a little draft plugin:
```js
// provider.js
function Suggestion(name, snippet, isDeprecated) {
  this.snippet = snippet;
  this.type = 'tag';
  this.leftLabel = 'apiDoc';
  this.rightLabel = isDeprecated ? 'deprecated' : '';
}

var suggestions = [
  new Suggestion("@api", "@api {${1:method}} ${2:path} ${3:[title]}"),
  new Suggestion("@apiDefine", "@apiDefine ${1:name} ${2:[title]}\n${3:* }           ${4:[description]}"),
  new Suggestion("@apiDescription", "@apiDescription ${1:text}"),
  new Suggestion("@apiError", "@apiError ${1:[{group\}]} ${2:[{type\}]} ${3:field} ${4:[description]}"),
  // 30 tags are ommited
  new Suggestion("@apiSuccessTitle", "@apiSuccessTitle {${1:group}} ${2:description}", true)
];

module.exports = {
  selector: '*',
  getSuggestions: function getSuggestions(options) {
    console.log(options.scopeDescriptor.scopes, options);
    return suggestions;
  }
};
```
and it gives the following output:
![default](https://cloud.githubusercontent.com/assets/4358089/7216781/e3f52c7e-e613-11e4-97e3-c6c11b12cbf8.PNG)

At this point I've got the following questions:

1. What should be passed to `leftLabel` and `rightLabel` properties in case of tags?

2. How to handle deprecated things properly?

3. I have pretty long snippets (up to ~90 characters). Is there any way to replace them with some name instead of printing the whole thing to suggestions list? For example, show "@apiParam" instead of "@apiParam [{group]} [{type]} [field=defaultValue] [description]"?

4. It looks like autocompete-plus doesn't aware of context - it simply shows options returned from providers. But, if a user types "@apiError", then he, probably, does not want to replace it with "@apiDefineSuccessStructure". Will such kind of filtering be provided by autocomplete-plus internally in the future or providers have to do it on their own?

5. This question is related to the previous one, but covers another aspect - sorting. Will autocomplete-plus sort suggestions by relevance (for example, like Sublime Text) or providers have to sort suggestions on their own?

6. How to handle optional elements? For example, tag "@apiDefine" can either have a "title" field or don't have this field. At this moment, I've wrapped such elements with `[` and `]` characters.

7. What to do in case the default value (or, probably, a placeholder) in snippet contains symbols `{` and `}`? In the provided example "@apiError" tag has the following construction: `${1:[{group\}]}`, but Atom inserts it like `[{group]}` instead of `[{group}]`.

**Comment by joefitzgerald** [comment]
/cc @maxbrunsfeld :wink:

For 1, leftLabel should be the return type(s) (if a function) or the type (if a variable) and rightLabel should probably not be used.

For 2, move away from deprecated things.

For 4, you should filter your suggestions.

For 5, you should sort your suggestions. That said, autocomplete-plus may implement a default sort function that you can call.

For 7, escape the right brace `}` with one slash `\` which itself will require escaping (`"\\}"`).

**Comment by Peekmo** [comment]
Hello !

In my own plugin, for 4 & 5 I decided to develop multiple providers which are called only in specific contexts. But you have to define this logic (you can just filter by scope in autocomplete-plus, and that's already greeaaat feature)

For 6, it's your choice  (and I think that's really good to be able to have the choice). Somebody would prefer hide optional parameters, others would like to have them in a single snippet, or just [] around like you. In my providers, I chose to add juste one snippet for whole things optionals. E.G (it's PHP function)

```php
array_slice($arg, $offset[,$length, $preserve_keys])
```
$length and $preserve_keys are optionals, so they are present but in the same snippet tab.

Maybe let the choice to the user in your package setting ? ;)

**Comment by benogle** [comment]
> What should be passed to leftLabel and rightLabel properties in case of tags?

In your case, you could use `apiDoc` in the rightLabel, but might be kind of redundant.

> I have pretty long snippets (up to ~90 characters). Is there any way to replace them with some name instead of printing the whole thing to suggestions list? For example, show "@apiParam" instead of "@apiParam [{group]} [{type]} [field=defaultValue] [description]"?

Not yet. This is coming.

> It looks like autocompete-plus doesn't aware of context - it simply shows options returned from providers. But, if a user types "@apiError", then he, probably, does not want to replace it with "@apiDefineSuccessStructure". Will such kind of filtering be provided by autocomplete-plus internally in the future or providers have to do it on their own?

You have to filter on your own currently. In the future there will be a way to hook into a default filter/sort, but not at this time.

> This question is related to the previous one, but covers another aspect - sorting. Will autocomplete-plus sort suggestions by relevance (for example, like Sublime Text) or providers have to sort suggestions on their own?

Same as last answer.

**Comment by DWand** [comment]
I've been thinking about filtering and sorting for a couple of days.

It looks like filtering could be separated into two phases:
1) Provider level filtering
2) Aggregation level filtering

Let's say we have a provider for some programming language like Java. There are a bunch of methods in the code and all of them have different scopes (belong to different classes) and access modifiers (private, public, ...). The provider has to determine a current context according to the code and prepare all possible suggestions according to this context (all methods of the current class, all public methods of some another class, all available variables, all available constants, etc). So, it has to filter these options among all methods, all variables, all constants which exist in the code.

But it may result in a pretty long list. This list should be filtered and sorted again according to what the user has already typed in. It is better to implement these features inside the aggregation unit because this part is common for almost any provider. This way results will look nice and consistent. Also, it may be not so trivial as the user is a human - he can to make mistakes, forget things and so on. It may be nice to make some kind of fuzzy search depending on some criteria. This is completely different logic than the one used inside the provider.

Thank you.

**Comment by joefitzgerald** [comment]
@DWand the current stance regarding filtering and sorting is this:

* It is the provider's responsibility to filter its suggestions for the current context
* A default sort function will be added to autocomplete-plus that can be used by providers - but they are free to sort with their own implementation if they have different needs
* Suggestions are displayed in an order that is determined via the specificity of provider registration and the priority of the provider

So I think your core request (to have a default filter function) is not currently planned. But its goal could be achieved using the sort function and the max suggestions setting.

**Comment by DWand** [comment]
@joefitzgerald, yes, I understand. Just thoughts :-)

**Comment by benogle** [comment]
Closing as it seems this ended in the provider created in #425.
