### ISSUE TITLE
Add descriptionHTML for better extendability.

### ISSUE THREAD

**Issue by vilic** [atom/autocomplete-plus#423]
E.g. emphasizing and new line.

**Comment by sadovnychyi** [comment]
:+1:

**Comment by vramana** [comment]
@benogle I want to work on this issue. Can you please guide me where to start ? :bow:

**Comment by benogle** [comment]
See the [description update method](https://github.com/atom/autocomplete-plus/blob/4a181bad83d5ce9d6c98806b6071219fb6c1c53b/lib/suggestion-list-element.coffee#L101), and another [example](https://github.com/atom/autocomplete-plus/blob/4a181bad83d5ce9d6c98806b6071219fb6c1c53b/lib/suggestion-list-element.coffee#L310) picking between the sanitized and html options.
