### ISSUE TITLE
A provider for apiDoc tags

### ISSUE THREAD

**Issue by DWand** [atom/autocomplete-plus#425]
Hello.

I've just finished a provider for [apiDoc](https://github.com/apidoc/apidoc) tags. It can be found here: https://github.com/DWand/Atom_autocomplete-apidoc. It would be cool you to make a little review of it. So it will be possible to make this thing better before publishing.

**Comment by joefitzgerald** [comment]
@DWand first thing I would recommend (prior to even looking at it) is to remove `_` (replace with `-` if needed). Second, consider renaming the repo to https://github.com/dwand/autocomplete-apidoc.

... and now I will actually review it :smile:.

**Comment by benogle** [comment]
Also, specs!

**Comment by DWand** [comment]
@joefitzgerald, is it critical a repo to be named exactly like a project name?

I've mentioned `"name": "autocomplete-apidoc",` in the package.json file. But I'd like to keep the "atom" part in repository name because there are also similar repositories for Sublime Text and Eclipse in my account. However, if it is critical, I can replace ` _ ` with ` - `.

**Comment by DWand** [comment]
As for specs, it is much harder task. It is not so obvious how to test such things. I'll try to write something based on autocomplete-html package.

There is a line in autocomplete-html's specs:
```coffee
waitsForPromise -> atom.packages.activatePackage('language-html')
```
Does it mean that I have to activate all 10 languages supported by my provider or it is okay to test only some of them?

**Comment by benogle** [comment]
I'm going to close this out. I agree with @joefitzgerald on the naming. The consistency throughout the community is really nice.
