### ISSUE TITLE
Possible memory leak  after update.

### ISSUE THREAD

**Issue by v3ss0n** [atom/autocomplete-plus#427]
When enabled , memory usage is jumping , then atom ran out of memory and Linux start swapping. 

At first i thought , it was due to  https://github.com/tinloaf/autocomplete-plus-python-jedi provider, but memory still increasing even if i disabled it.But memory usage stop increasing when i disable autocomplete-plus.

There are still many providers left to disable , if anyone have this problem , please test around and report. I gotta go for now.

Atom version is 194

**Comment by joefitzgerald** [comment]
@v3ss0n can you please provide more information? What is the setting for `Default Provider`? `Symbol` or `Fuzzy`? Could you try your testing with the other one and let us know if you still experience the same behavior?

**Comment by steelbrain** [comment]
I was experiencing the same leak a few weeks ago, but @benogle fixed it pretty quickly.

**Comment by benogle** [comment]
This may be fixed. Please reopen if this is still an issue.
