### ISSUE TITLE
Some displayText doesn't show correctly.

### ISSUE THREAD

**Issue by Qusic** [atom/autocomplete-plus#436]
I'm working with version 2.12.1.
Such `displayText` `'swap(std::vector<Foo, std::allocator<Foo> > &x)'` shows as below:
![image](https://cloud.githubusercontent.com/assets/2141853/7466454/d1677742-f315-11e4-8665-30da35b491c0.png)
![image](https://cloud.githubusercontent.com/assets/2141853/7466468/10554eac-f316-11e4-82d9-6897984c1c32.png)

**Comment by benogle** [comment]
We definitely need to html escape the displayText. Sorry about this.
