### ISSUE TITLE
Support for Appcelerator-Titanium 

### ISSUE THREAD

**Issue by DaneGrinder** [atom/autocomplete-plus#444]
I am trying to find a solution, where I can work with Appcelerator/Titanium Mobile Crossplatform, and have code completion for both Coffeescript and Appcelerator/Titanium. Can anyone make this happen in Atom?

Coffeescript seems to work fine in Atom already.

There is an old Textmate bundle available for Titanium if that is of any help
https://github.com/subtleGradient/JavaScript-Appcelerator-Titanium-Mobile.tmbundle

**Comment by benogle** [comment]
I'm going to close this. Maybe the [forum](https://discuss.atom.io/) would be a better place to round up folks?
