### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Andreyco** [atom/autocomplete-plus#446]
Uncaught TypeError: Cannot read property '0' of undefined  
/Users/andrejbadin/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:96

```
TypeError: Cannot read property '0' of undefined
  at autocomplete-suggestion-list.SuggestionListElement.updateDescription (/Users/andrejbadin/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:96:36)
  at autocomplete-suggestion-list.SuggestionListElement.renderItems (/Users/andrejbadin/.atom/packages/autocomplete-plus/lib/suggestion-list-element.coffee:184:6)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:168:9)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

**Comment by izuzak** [comment]
@Andreyco Which version of Atom are you using? Can you try updating to the latest version (0.198.0) and see if that helps? If not, can you reproduce the problem in [safe mode](safe mode)? If so, can you provide steps to reproduce this problem?

**Comment by Andreyco** [comment]
That's the exact version I am using. This started to show up after update to 0.198.0  
Happened to me several times since but I don't clearly remember how. I'm trying to reproduce the issue with no luck (as usually, you must know that). Will report back when it pops out!

**Comment by izuzak** [comment]
Thanks for following up, @Andreyco. Well that's strange -- where did you see this exception exactly? Did a red notification pop up in the top right corner? If so, then it's really strange that the notification didn't include more information than just a stack trace -- normally it includes the version of Atom, OS, installed packages and lots more. That's why I thought you were using an old Atom version.

**Comment by Andreyco** [comment]
Yes, that's where it popped out. Unfortunately reporting issue right from the popup was not possible (button didn't react to click action) so I copy-pasted what was available.

**Comment by benogle** [comment]
I just published a fix with ac+ 2.15.0. Try it out and let us know.

**Comment by izuzak** [comment]
:sparkles: @benogle

**Comment by Andreyco** [comment]
Hasn't happened since the update <3
