### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by iamkeyur** [atom/autocomplete-plus#447]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.158.0
**System**: linux 3.13.0-24-generic
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, v2.14.2

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/keyur/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:53

TypeError: undefined is not a function
  at FuzzyProvider.module.exports.FuzzyProvider.updateCurrentEditor (/home/keyur/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:53:45)
  at FuzzyProvider.updateCurrentEditor (/home/keyur/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:1:1)
  at /home/keyur/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:31:8

```

/cc @atom/core

**Comment by izuzak** [comment]
You're on a super-old version of Atom. Can you please update to the latest version (0.198.0) and if you can still reproduce this -- open a new issue? Thanks!
