### ISSUE TITLE
SymbolStore.adjustBufferRows takes too much time in large files

### ISSUE THREAD

**Issue by nathansobo** [atom/autocomplete-plus#452]
Here's a profile of typing in `huge.js`. We need to find a way to reduce the overhead of adjusting the symbol store. A tree structure that's relative like the marker index would probably be a good idea, because this seems like a lot to pay for this.

![screenshot_2015-05-14_11_05_33](https://cloud.githubusercontent.com/assets/1789/7629020/92c0e5c6-fa29-11e4-9f33-2105541ecb7c.png)

**Comment by nathansobo** [comment]
Thinking some more about this. It would be great to find a way to use markers to index and invalidate completion tokens. Currently, this would require a marker object for each completion, which has its own problems in a large file. Originally I was considering a marker API that just returned an integer id for a marker and allowed queries based on that id. That's looking like something worth revisiting as a possible more performant path.

**Comment by stephenhandley** [comment]
i saw pretty slow typing performance in atom 0.199 in a file of only about 120 lines. downgrading to 0.198 brought things back to normal so this may be due to the new autcomplete-plus integration. this was noticeable when the cursor was active and trying to scroll or click to another line in the file. things also slowed down pretty significantly when typing within string constants.

**Comment by nathansobo** [comment]
@stephenhandley If you have time to take a profile in the dev tools and post a screenshot here, that would be super helpful. Would be good to know what's causing your performance problems so we can fix them.

**Comment by benogle** [comment]
@as-cii did your change fix this? I think so, right?

**Comment by as-cii** [comment]
:+1: 

I still believe that the tree idea is interesting, but as I also pointed out in #672, it seems like the array based solution is a great tradeoff between speed and simplicity. Closing this for now, thanks for the heads-up @benogle! :balloon:
