### ISSUE TITLE
Show function parameter names on autocompletion

### ISSUE THREAD

**Issue by mnquintana** [atom/autocomplete-plus#455]
_From @TiagoMarinho on May 15, 2015 0:13_

I don't really know if this issue belongs here, but since I like a lot how WebStorm autocompletes code, I think it would be a great idea to implement a code hint that shows functions parameter names. Here's a gif example showing how WebStorm handles this:

![WebStorm parameter hinting](http://i.imgur.com/ikHBaVB.gif)

This feature helps a lot when I don't know exactly how many arguments a function is supposed to handle.

_Copied from original issue: atom/atom#6793_

**Comment by 50Wliu** [comment]
Jumping on to this issue: it'd be fantastic if autocomplete could also show you the argument descriptions.

**Comment by joefitzgerald** [comment]
autocomplete-plus is capable of this already. It's up to the provider (which is often grammar specific) to provide this information in the suggestions. What grammar (language) are you missing this information for?

**Comment by TiagoMarinho** [comment]
You're right. I'm using JavaScript, but I haven't noticed I could add a third-party provider when writing this issue. Tern is able to do what I was asking for, but it would be great if this came built-in.

**Comment by TiagoMarinho** [comment]
Also, I think the autocompletion hints could be improved a lot. Is there any discussion about this open?

**Comment by mnquintana** [comment]
@TiagoMarinho That's because there isn't an autocomplete provider for JavaScript yet – what you're seeing is just the default provider (which just autocompletes based on whatever is already in the file) - there will be an autocomplete provider soon, once the language support improves.

**Comment by TiagoMarinho** [comment]
Isn't [atom-tern](https://github.com/tststs/atom-ternjs) a provider?

**Comment by mnquintana** [comment]
Ah whoops, sorry about that, you're right

**Comment by TiagoMarinho** [comment]
Hah, no problem. Do you think there will be more providers in the future that support this feature? I really want to switch from WebStorm to Atom but the autocompletion is driving me crazy.

**Comment by lee-dohm** [comment]
@TiagoMarinho There will definitely be more providers and more improved providers in the future. autocomplete-plus has only been default-installed for less than a day so far :grinning:

**Comment by TiagoMarinho** [comment]
You can close this issue if you want, since it's not up to autocomplete-plus to provide smarter autocompletion, but to third-party providers. Obviously, it would be awesome if improvements were made to the built-in provider, but the way it's designed is really interesting (allowing anyone to create better providers). Thanks for the help.

**Comment by vimniky** [comment]
+1 .@TiagoMarinh . I really want to switch from WebStorm to Atom but the autocompletion is driving me crazy. And refactory also driving me crazy too .

**Comment by julmot** [comment]
@TiagoMarinho Did you find any package that has this feature?

**Comment by ProPuke** [comment]
How is autocomplete-plus already capable of this?

Do you mean via snippet suggestions, or is there a nicer way?

I'm developing a provider, and would like to show parameter info as you type them. Some parameters will be optional so I don't want to just insert all parameters when you select a completion. I'd also like editing the arguments of existing functioncalls to also show the parameter names.

**Comment by TiagoMarinho** [comment]
@julmot nope, and I still miss this feature a lot. Switching between files and docs every single time to remember what parameters the function must take is painful.
