### ISSUE TITLE
width tooltip pane restricted by window split

### ISSUE THREAD

**Issue by donnut** [atom/autocomplete-plus#456]
I ran into this issue. I'm not sure if it belongs to autocomplete-plus. 
![tooltip-break](https://cloud.githubusercontent.com/assets/417406/7648306/db8d7c20-fae1-11e4-90fa-19f95e07ef0d.png)
See also https://github.com/TypeStrong/atom-typescript/issues/345

**Comment by aaalsubaie** [comment]
the same here.

![screen shot 2015-05-30 at 11 34 08 am](https://cloud.githubusercontent.com/assets/1550029/7896360/d8bcf34c-06bf-11e5-9fe1-d8a0bd0d46bc.png)

**Comment by basarat** [comment]
This is fixed. But note that it introduced another UX issue where the name isn't being `ellipsed` : 

![image](https://cloud.githubusercontent.com/assets/874898/8154786/1f4110be-1381-11e5-897a-1cdd9ae907be.png)

**Comment by donnut** [comment]
Great!
