### ISSUE TITLE
Potential Issue(s) Reported On HN

### ISSUE THREAD

**Issue by joefitzgerald** [atom/autocomplete-plus#460]
https://news.ycombinator.com/item?id=9555192

**Comment by MayhemYDG** [comment]
Might be a conflict with emmet perhaps?

**Comment by joefitzgerald** [comment]
I think you're right @MayhemYDG.

**Comment by fbm-static** [comment]
Congratulations on your PhD @MayhemYDG!

**Comment by MayhemYDG** [comment]
@fbm-static 
What PhD? I think you got the wrong person.

**Comment by aaronmw** [comment]
Steps to reproduce:

1. Install Emmet package
2. Install autocomplete-plus + autocomplete-css
3. Configure autocomplete-plus to use "tab" as the "Keymap for confirming a suggestion"
4. Type anything in a CSS file to trigger the autocomplete list
5. Try to accept by hitting "tab"
6. Be frustrated that it doesn't work at all as expected

**Comment by 50Wliu** [comment]
@aaronmw That is an issue with Emmet, not autocomplete-plus.

**Comment by 50Wliu** [comment]
Closing as there have been no more reports of this.
