### ISSUE TITLE
Detect autocomplete triggered via strg-space

### ISSUE THREAD

**Issue by tststs** [atom/autocomplete-plus#461]
As the title says, is there any way to determine if the user triggered autocomplete-plus via ctrl-space?

thx
tststs

**Comment by joefitzgerald** [comment]
What's the use case driving this need?

**Comment by tststs** [comment]
I don't trigger autocomplete while typing if the prefix is whitespace.
The problem with this is, that if the prefix is whitespace and the user hits ctrl-space, nothing happens, cause i can't set a flag like ```force``` to force the completion in this case.

**Comment by joefitzgerald** [comment]
OK. So you're asking if you can have `activatedManually` (https://github.com/atom/autocomplete-plus/blob/800b8d1492a08640d2e170cfa659092bf4aee688/lib/autocomplete-manager.coffee#L135) passed in the options object passed to a provider's `getSuggestions` function? That seems reasonable. @benogle?
