### ISSUE TITLE
2 issues regarding javascript autocomplete.

### ISSUE THREAD

**Issue by techsin** [atom/autocomplete-plus#462]
1) Autocomplete doesn't trigger until i've typed a letter, and not after period ( . )....
...autocomplete doesn't trigger even when i press ctrl+space... even though settings say that's the key for autocomplete plus that came preinstalled with atomio.

2) why autocomplete doesn't show some thing, for example, forEach. If i write in developer tools 

    var n = [1,3,4];
    n.for   *here if i press ctrl space* it will complete to forEach whereas in atomio it isn't even present in drop down list of possible things that start with for.

WIndows 7 64 bit
atom version 0.199

**Comment by saschagehlich** [comment]
Chrome's developer tools autocompletion is way more sophisticated since it can work with the actual JavaScript objects and not with the pure source code (like autocomplete-plus does / has to). It can easily display the prototype functions and properties of the `n` object..

**Comment by techsin** [comment]
I just tried new visual studio code and it's 

 1- showing forEach after array.

 2- shows possible solutions right after i type period. This is expected and common behavior across eclipse, brackets, sublime, and everywhere. Show rest while typing, and Definitely show possible things right after i type period like so, **document.** ---> [ body, getElementById, etc]

**Comment by benogle** [comment]
Try the https://atom.io/packages/ternjs package, it should provide deeper intelligence.
