### ISSUE TITLE
Intellisense snippets should be html escaped

### ISSUE THREAD

**Issue by nosami** [atom/autocomplete-plus#466]
Without escaping, snippets currently look like this :-

![](https://cloud.githubusercontent.com/assets/95136/7665037/06bca802-fb5b-11e4-95c8-30ace4155a1b.png)

Although the resulting completion looks as follows :-

![](https://cloud.githubusercontent.com/assets/95136/7665038/21b60d06-fb5b-11e4-9fc5-90b5c1240e0a.png)

If I escape the snippet property myself, it renders correctly but then the escaped text is inserted into the document.

**Comment by joefitzgerald** [comment]
Related to #436.

**Comment by nosami** [comment]
Awesome, thanks!

**Comment by benogle** [comment]
Sorry this took so long.

**Comment by nosami** [comment]
No worries at all.... thanks for your work on Atom.... loving it :)
