### ISSUE TITLE
Autocompletion does not work with multiple cursors

### ISSUE THREAD

**Issue by saschagehlich** [atom/autocomplete-plus#467]
When using autocomplete-plus with multiple cursors (and the Symbol provider), the package always suggests the current text at the first cursor as well:

![autocomplete-plus-multiple-cursors](https://cloud.githubusercontent.com/assets/119684/7680602/63b543f2-fd68-11e4-9db6-07ad903dacad.gif)

**Comment by maxbrunsfeld** [comment]
@saschagehlich can you explain your expected behavior in more detail?

**Comment by benogle** [comment]
This is legit. It's caused [here](https://github.com/atom/autocomplete-plus/blob/6e2e4600a290191cbdd2df010fe35758bc7d1fff/lib/symbol-provider.coffee#L191). Basically what happens is:

* the symbol provider adds the tokens as you are typing. In this case it will add `logoHi` etc. twice
* [this code](https://github.com/atom/autocomplete-plus/blob/6e2e4600a290191cbdd2df010fe35758bc7d1fff/lib/symbol-provider.coffee#L191) takes `wordUnderCursor` and subtracts 1 from the symbol instances for that word when pulling them out of the store. 
* There is one instance that the `wordUnderCursor` code isnt taking into account, and it is returned.

**Comment by maxbrunsfeld** [comment]
Oh I see. The partially-typed text appears in the suggestion list. @saschagehlich disregard my question above.
