### ISSUE TITLE
Sass Mixins position in dropdown oddity

### ISSUE THREAD

**Issue by madebyrichard** [atom/autocomplete-plus#470]
When i type in @include, the dropdown select oddly places the mixins I have at the *bottom* - forcing me to type more letters to narrow down the word. In some cases I find myself typing in the full mixin instead of selecting from the dropdown.

see screengrab:
https://www.evernote.com/l/AFxyKHAPRKtDi41VaJc2ZZEwBaWXud8NUMo

**Comment by joefitzgerald** [comment]
Duplicate of #465.
