### ISSUE TITLE
Enter a new line on "enter"

### ISSUE THREAD

**Issue by raulsann** [atom/autocomplete-plus#471]
When typing very often I come to a situation when the autocomplete is autocompleting at the end of a line. I just want to enter a new line but when I hit enter, the autocomplete plugin enters the first entry on the autocomplete list.

I think there should be a command to do the following:

```cson
'atom-text-editor:not(mini).autocomplete-active':
  'tab': 'unset!'
  'enter': 'Do not autocomplete(). Close the autocomplete modal() and enter a new line()'
  'up': 'unset!'
  'down': 'unset!'
  'ctrl-p': 'core:move-up'
  'ctrl-n': 'core:move-down'
```

Can this be achieved at the moment?

Thanks!

**Comment by mnquintana** [comment]
Yup! You can go to Settings > Packages > autocomplete-plus and change Keymap For Confirming A Suggestion to tab.

Or just copy this to your config.cson:
```cson
  "autocomplete-plus":
    confirmCompletion: "tab"
```

**Comment by raulsann** [comment]
Great! Thank you!

**Comment by logicmason** [comment]
I have to 2nd this. It's horrible UX to autocomplete on enter by default. It leads to things like typing

```
  ...
  session[:user_id] = user.id
end
```
and Atom printing
```
  ...
  session[:user_id] = user.# IDEA: end 
```
