### ISSUE TITLE
icon of autocomplete type not showing on mac

### ISSUE THREAD

**Issue by funsterisdafunniest** [atom/autocomplete-plus#481]
Hi, after a few weeks of using autocomplete plus, i've just noticed something,
The icon that's supposed to mark the autocomplete candidate as function, variable, etc are not showing up on my editor. It works fine with windows and linux (ubuntu).

my question is, is this intentional? or did i do something bad with my atom to produce this result
(image for reference)
![screen shot 2015-05-27 at 11 26 24 am](https://cloud.githubusercontent.com/assets/5591104/7828838/43ef538a-0463-11e5-817b-7046ad78c73c.png)

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by funsterisdafunniest** [comment]
Hi, i'm sorry, i haven't followed it yet (mainly because i didn't know it existed)

i was confused as to where should i find help for this problem, oh yeah for your question :

<ol>
<li>version 0.201.0</li>
<li>mac yosemite</li>
<li>i can't, so i'm checking it by turning off my packages one by one, it might be that some packages are not compatible with autocomplete-plus</li>

**Comment by funsterisdafunniest** [comment]
@lee-dohm it seems that removing the autocomplete package installed via apm before the atom 0.200 upgrade solved this, thanks!
