### ISSUE TITLE
Autocomplete only in new panes, not mini-editors 

### ISSUE THREAD

**Issue by csaund** [atom/autocomplete-plus#486]
I'm trying to get autocomplete to activate in a mini text editor in a pane that is tagged as something other than a text editor. I see that the autocomplete-active tag is applied by using observeActivePaneItem, and if that pane is invalid autocomplete is not active. How would I go about changing this so that all text editors activate autocomplete, not just panes as editors? 

Thanks,

**Comment by benogle** [comment]
Closing in favor od #383
