### ISSUE TITLE
AutoComplete box position incorrect on left

### ISSUE THREAD

**Issue by steelbrain** [atom/autocomplete-plus#487]
A picture is worth a thousand words.
![screenshot from 2015-05-28 13-40-23](https://cloud.githubusercontent.com/assets/4278113/7870575/27dd05b6-053f-11e5-83ba-fd9737d4dc04.png)
It only happens when I am typing on the left side, when I am in the middle, it shows correctly.

**Comment by benogle** [comment]
I'm not following. Looks right to me. Do you mean the description / docs?

**Comment by steelbrain** [comment]
Here's the version with the explaination 
![screenshot from 2015-05-28 13-40-23](https://cloud.githubusercontent.com/assets/4278113/7870884/09f279d0-0541-11e5-8e2f-1597d8cb3ff1.png)

**Comment by joefitzgerald** [comment]
@steelbrain short term fix is to set `Suggestion List Follows` to `Cursor`, instead of `Word`, but this indeed looks like an issue.

**Comment by benogle** [comment]
Does this happen in safe mode? Looks like a zindex issue with whatever is on the left side (tree-view?)

**Comment by steelbrain** [comment]
![screenshot from 2015-06-14 01 56 41](https://cloud.githubusercontent.com/assets/4278113/8147747/9f61edd0-1238-11e5-89ed-d7276aa5131a.png)
It's fixed in the latest atom
