### ISSUE TITLE
Autocomplete triggered in CSS on semi colon

### ISSUE THREAD

**Issue by AdamBuczynski** [atom/autocomplete-plus#489]
Consider the following behaviour:

![Example](https://www.dropbox.com/s/zj13mkn28veugoh/atom-css-autocomplete-issue.gif?dl=1)

When I reach the end of the line in my CSS/LESS file, I want to be able to hit enter and go to the next line, not select "width" every time or keep typing on the same line. Why is the autocomplete automatically triggered here? This behaviour is not exhibited in other files like javascript. No autocomplete box shows up after ending a line with a semi colon:

![Example](https://www.dropbox.com/s/3n8m66o6japkz88/atom-css-autocomplete-issue2.gif?dl=1)

**Comment by joefitzgerald** [comment]
This is an issue for [autocomplete-less](https://github.com/atom/autocomplete-less). Essentially, autocomplete-less needs to suppress it's suggestions for specific characters (e.g. `;`).

You can work around this issue in the short term
By switching the keybinding for accepting suggestions from `tab and enter` to `tab` - this will ensure that when you type enter, even though the suggestion is selected, it won't be confirmed and inserted into your document when you press enter.

@benogle this is why we used to have `tab` as the default.

**Comment by AdamBuczynski** [comment]
Yes, I tried switching to TAB only, but found that I had gotten used to confirming with ENTER, so it was not an option. I will post this issue at the autocomplete-css package actually, because after disabling it, the behaviour went away.

**Comment by AdamBuczynski** [comment]
Re-opened issue here: https://github.com/atom/autocomplete-css/issues/15
