### ISSUE TITLE
Extra opening tag on autocomplete

### ISSUE THREAD

**Issue by Mehdi-Hp** [atom/autocomplete-plus#494]
Of course i'm writing HTML by start typing the opening tag (<);
but the extra opening tag after autocompletion is really annoying. actually it was one of the main reason I left ST3 to atom.  

![atom extra opening tag](https://cloud.githubusercontent.com/assets/8641684/7943563/7cd7aff0-097a-11e5-9aa1-f2ae8162ef02.gif)

**Comment by mnquintana** [comment]
This is because the snippet prefix is `div`, not `<div` – all you need to do is type `div` and hit <kbd>Tab</kbd> to complete it properly. If you really do want to be able to autocomplete from typing something like `<div`, you could always add a snippet to your `snippets.cson`:

```coffee
'.text.html.basic':
  'Div completion':
    'prefix': '<div'
    'body': '''
      <div class="$1">
        $2
      </div>
    '''
```

**Comment by benogle** [comment]
Do you have autocomplete-html enabled? When typing the `<` it should just complete the tag name, rather than the entire snippet. What version of atom are you on?

**Comment by Mehdi-Hp** [comment]
@benogle I've just downloaded atom. it's 0.204.0
Noting changes if I disable or enable autocomplete-html. absolutely no difference. even restarted atom.

BTW, I kinda like the way it completes and put cursor between double quotes. I don't want to miss it.

**Comment by benogle** [comment]
Is this still an issue? Are you on 1.0.*?

**Comment by benogle** [comment]
Please reopen if you're still not getting autocomplete-html completions. Also make sure autocomplete-html is enabled.

**Comment by dy** [comment]
Oh, run the same issue after transitioning from vscode, which doesn't have that issue.
Do you think it's UX-friendly - to start typing with <kbd><</kbd> for custom tags and <kbd>x</kbd> for regular tags?

**Comment by tomkc** [comment]
Same story here, i got Atom 1.43.0 with stock configuration plus few plugins and got same problem as OP. Selecting autocomplete suggestion after typing something like "<htm" puts code without removing "<" giving me something like this 
```
"<<!DOCTYPE html>
<html lang="en" dir="ltr">". 

```
It's kinda weird behavior, not existing in other code editors
