### ISSUE TITLE
SymbolProvider word regex does not include accents

### ISSUE THREAD

**Issue by LucFabresse** [atom/autocomplete-plus#495]
word completion does not work on accentuated languages because accentuated letters are not considered as part of words. 

I suppose that replacing \w with [:alpha:] in the wordRegex of SymbolProvider would be a start to include letters with accents inside words. 
http://www.regular-expressions.info/posixbrackets.html

FYI, I am using atom Version 0.205.0 and autocomplete-plus 2.17.3 (the one that comes by default with atom). 

all non-english users will thank you a lot by taking care of this ;-)

**Comment by benogle** [comment]
Thanks for the report. This should be supported in #76
