### ISSUE TITLE
Problem with _accented characters_

### ISSUE THREAD

**Issue by alefragnani** [atom/autocomplete-plus#496]
It appears that **accented characters** like **ã**, **á** and **ç** are not recognized on autocomplete.

For instance, look how the autocomplete lists this accented words:

* **Solicitação**: _Solicita_ and _o_ are listed
* **Perímetro**: _Per_ and _metro_ are listed

It doesn't appear to be an *encoding* issue, since either UTF-8 and Windows 1252 have the same problem.

Thanks in advance

**Comment by benogle** [comment]
Thanks for the report. This should be supported in #76
