### ISSUE TITLE
Finding suggestions takes over 200ms sometimes

### ISSUE THREAD

**Issue by xPaw** [atom/autocomplete-plus#499]
I can't reproduce this consistently, but after Atom has been running for a while, there's a noticeable freeze when typing something before it shows relevant suggestions for autocompletion.

When I tried to save a timeline, Atom just wrote `[` to the file and then closed, so I can't attach it here.

**Comment by robballou** [comment]
Not sure if this is related but I often get a small delay while typing related to autocomplete. I managed to save this timeline on one occurrence: https://gist.github.com/robballou/fdf0508d51c0a3409078. I think the consistency relates to something with autocomplete generating new suggestions but I'm not totally clear on what the timeline reveals.

Hopefully this helps, but if there's other things I can do to help let me know.

**Comment by benogle** [comment]
@robballou Thanks a ton for the timeline. Looks like it's happening when pulling the builtin suggestions out of the config when changing scopes. 

What language were you in? Thinking maybe the language was defining tons of builtin suggestions. Are you defining any builtin suggestions in your config file?

**Comment by benogle** [comment]
@xPaw a screenshot of a profile's flame graph would be nice as well. Just zoom in on a bit where there is a big spike or sustained spike so the function names are visible, and paste in the screenshot.

**Comment by robballou** [comment]
@benogle I believe this was in PHP along with https://atom.io/packages/drupal (which has lots of snippets). I'm not adding anything else beyond what's in packages. If a separate issue or other details would be helpful, let me know. Currently I've turned off the automatic suggestions and am just using the key command to trigger it. And thank you for looking into this.

**Comment by benogle** [comment]
Wellll, this is probably it https://github.com/atom/language-php/blob/master/settings/language-php.cson#L5

I will make it better at handling all these.

**Comment by benogle** [comment]
This should be faster on the next release of atom next week. There will be no more lag where there were issues in your timeline @robballou. Closing for now.

**Comment by robballou** [comment]
@benogle great news! That completion list is ... something :)

**Comment by benogle** [comment]
@robballou check out atom 1.0.3 and let me know if things are better. If not, another timeline would be great :)

**Comment by robballou** [comment]
So far this is working really well for me. I'm not getting any noticeable lag now. Thanks!
