### ISSUE TITLE
Up-Down Keypress brokes Atom UI

### ISSUE THREAD

**Issue by muhasturk** [atom/autocomplete-plus#500]
Please [download video](https://yadi.sk/i/08sVlpxCh8ELW "Download") to observe behaviour when press up and down on autocomplete menu.

![](http://i.imgur.com/ZVMhZJP.png)

**Comment by mnquintana** [comment]
Have you followed the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?

**Comment by benogle** [comment]
This will be fixed in the next version of atom next week. See #511
