### ISSUE TITLE
Disable default suggestion list

### ISSUE THREAD

**Issue by lczech** [atom/autocomplete-plus#502]
In every file (even plain text), autocomplete suggests a list of items that have no use for me when I type a dot:

* .wrap-guide
* .indent-guide
* .invisible-character
* .gutter
* .line-number
* ...

This seems like unnecessary spamming to me. Those items look like the belong to some atom features, but even after disabling autocomplete-atom-api they do not disappear.

I'd like to have a possibility to disable those suggestions.

**Comment by steelbrain** [comment]
The last time I checked the settings, there's an option to disable the builtin provider

**Comment by lczech** [comment]
@steelbrain: That is correct, but it is not the option I am looking for. The built-in provider simply looks for words in open buffers:

    The package comes with a built-in provider that will provide suggestions using the words
    in your current buffer or all open buffers.

Disabling it does not change the behaviour that I described above. Furthermore, the list of suggestions is always the same (see above), regardless of the documents that I have open. Those items do not come from my buffers, as I do not have words like "wrap-guide" or "gutter" in my code. They sound more like atom-internal identifiers to me.

**Comment by steelbrain** [comment]
Are those snippets or regular autocomplete items?

**Comment by lczech** [comment]
I don't know where they are coming from. Is there a way to tell?

This is what the list looks like:
![suggestions](https://cloud.githubusercontent.com/assets/4741887/8148584/4601fb88-12a4-11e5-97f9-a5452b679afc.png)

As said, it appears when I am typing a dot. Not always though; sometimes it seems the language-specific provider kicks in instead. It mostly appears when the word in front of the dot is not a symbol of the current code, so in comments for example. But also for some occurrences of symbols. I do not see much of a regularity there... Although it is reproducible in the sense that if the list appears in one place, it does again after deleting the dot and typing it again.

**Comment by thomasjo** [comment]
Are you able to reproduce in safe mode?

**Comment by lczech** [comment]
No, I do not get any suggestions in safe mode. The suggestion list just never shows up - not even with the built-in behaviour of showing words from the current buffers. No list at all.

**Comment by steelbrain** [comment]
@lczech Are you using the latest Atom?

**Comment by lczech** [comment]
I think so. Atom version 0.201.0, under Ubuntu 14.04 (fully updated).

apm list --installed
/home/lucas/.atom/packages (29)
├── Sublime-Style-Column-Selection@1.3.0
├── atom-beautify@0.28.4
├── atom-ctags@4.1.2
├── autocomplete-clang@0.7.0
├── autocomplete-python@0.4.2
├── block-travel@1.0.2
├── cut-line@0.10.0
├── docblockr@0.7.2
├── drag-drop-text@0.1.2
├── hex@0.6.2
├── highlight-line@0.11.0
├── highlight-selected@0.10.0
├── isotope-ui@2.4.0
├── language-cmake@0.1.3
├── language-cpp@0.0.1
├── linter@0.12.7
├── linter-clang@2.26.0
├── lucas-dark-syntax@0.0.0
├── minimap@4.10.0
├── minimap-bookmarks@0.1.0
├── minimap-find-and-replace@4.2.0
├── minimap-git-diff@4.1.3
├── minimap-highlight-selected@4.3.0
├── seti-syntax@0.4.0
├── simple-drag-drop-text@0.2.3
├── switch-header-source@0.19.0
├── tabs-to-spaces@0.11.0
├── word-jumper@0.3.0
└── writer-syntax@0.6.2

Does this help?

**Comment by steelbrain** [comment]
I am unable to reproduce this on v0.209.0 https://github.com/atom/atom/releases

**Comment by thomasjo** [comment]
Try updating Atom. The latest version is v0.209.0. Thanks for providing the list of installed packages, it's helpful!

**Comment by lczech** [comment]
Found the culprit! The items disappear when I disable atom-ctags. I created an issue there: https://github.com/yongkangchen/atom-ctags/issues/106

Sorry for the confusion, I disabled all other packages before submitting this issue, just not this one, because I didn't think that those items (looking like atom-internal words) would come from a C/C++ related package...
