### ISSUE TITLE
Don't show suggestions when there's only one and it's already been typed in

### ISSUE THREAD

**Issue by adambuczynski** [atom/autocomplete-plus#504]
Screencap to illustrate:

![ex](https://www.dropbox.com/s/mjvw2eeyljadmd5/dont%20suggest%20if%20text%20is%20there.gif?dl=1)

When I've already typed "false", there's little point in showing the autocomplete suggestion box if "false" is the only thing that is being suggested. The word is already there in the code, so there is no point to suggest it, especially if there are no other alternatives either. Currently, it only gets in the way if you want to double click quickly on the next line to replace text there.

**Comment by benogle** [comment]
This is deliberate for a couple reasons:

* case sensitivity: Say you type `false` and you want `False`
* when there are other items with the same prefix. Say you type `item` and there are a few other options `itemLength`, `itemColor`. It's strange if a suggestion that matches, and is first match suddenly drops out. 

We could limit it in the case where it's strictly equivalent, and there are no other suggestions, though.

**Comment by adambuczynski** [comment]
Thanks, yes, I understand the use case for when there's multiple other items where the word you've typed is a prefix. Case sensitivity as well.

But if it's an exact match and if there are no other options, it does seem to be redundant.

**Comment by xeron** [comment]
I just was about to report the same.
