### ISSUE TITLE
Editor pane halved when scrolling down on a suggestion

### ISSUE THREAD

**Issue by abinashmeher999** [atom/autocomplete-plus#505]
I was editing my file and I was at the third line from last, of the editor pane. I began typing and the suggestions showed. The list was long so it went past the bottom border and as I tried to scroll down upto that the editor halved. I am attaching some screenshots
![screenshot from 2015-06-18 03 16 58](https://cloud.githubusercontent.com/assets/6918379/8219588/b22abcf2-1568-11e5-8d1a-676096cb5519.png) 
![screenshot from 2015-06-18 03 21 46](https://cloud.githubusercontent.com/assets/6918379/8219672/47c68f3e-1569-11e5-9fe1-3fcf3bf251eb.png)
Is this natural behaviour? Just wanted to let you know, in case it is a potential bug.

**Comment by thomasjo** [comment]
Which UI theme are you using, and what version of Atom? Are you able to reproduce this in safe mode? `atom --safe`

**Comment by abinashmeher999** [comment]
I am using Seti-ui with 0.209.0 of Atom. The safe mode uses Atom Dark ui, so I am not able to reproduce this bug. Neither in the normal mode, the list of suggestions now shows above the line.
![screenshot from 2015-06-18 14 40 30](https://cloud.githubusercontent.com/assets/6918379/8227857/07e3067c-15c8-11e5-82f5-158d923196e9.png)
I don't get how this doesn't happen now.

**Comment by benogle** [comment]
Could this be the same as https://github.com/atom/autocomplete-plus/issues/511?

**Comment by abinashmeher999** [comment]
This is very similar, in a sense that the ui moves up. In this case, the ui significantly moves up, almost half the screen. 
In the meantime, I successfully reproduced the bug. I have made a gif, that shows what happens
![uamqt_](https://cloud.githubusercontent.com/assets/6918379/8452784/945e48ee-200b-11e5-9c12-5d1c85c56a8b.gif)
Hope this helps.

**Comment by ppizarror** [comment]
For me it happens with arrow keys, but when using mouse scroll it works well
