### ISSUE TITLE
Autocomplete not working for anything except HTML and CSS

### ISSUE THREAD

**Issue by KaloyanMarshalov** [atom/autocomplete-plus#507]
I have a freshly installed instance of Atom. I had some packages installed before, but autocomplete never really worked. It only works with html and css files. When I try to write javascript nothing comes out except snippets. I tried selecting other languages from the bottom right corner in a new unsaved file, but still no response. 

 I am using Version 0.210.0 of Atom and 2.17.4 of Autocomplete-plus. My OS is Windows 7 x64.

**Comment by steelbrain** [comment]
Please note that autocomplete+ is just the base provider, You'll need other autocomplete providers to provide autocompletions for specific languages. 
You can find autocomplete providers here https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers

**Comment by KaloyanMarshalov** [comment]
Ah I feel so stupid now. I should have noticed that "autocomplete-css" and "autocomplete-html" are installed, but there is nothing for JavaScript. I got it working by installing "atom-ternjs". Thank you for the quick response!
