### ISSUE TITLE
Suggestion order

### ISSUE THREAD

**Issue by m1ga** [atom/autocomplete-plus#508]
I have a variable called "transRotate" and when I type "transr" (or transR) it always puts "transform" as first suggestion:
![Image](http://migaweb.de/autocomplete.png)

shouldn't be the second suggestion weighted higher because the character order is the one i've typed?

**Comment by zachthenerd169** [comment]
This is an issue with fuzzaldrin, the tool autocomplete-plus uses to provide fuzzy string matching. It looks like they almost have it working to add higher priority to exact substring matches https://github.com/atom/fuzzaldrin/pull/19

**Comment by florianb** [comment]
I have the same issue in a ruby-file using the boolean-keyword `and`. Autocomplete prefers to suggest the snippet `asnd` first.

![image](https://cloud.githubusercontent.com/assets/983507/10131041/893967e8-65cd-11e5-8a21-78ea463e66dc.png)

**Comment by jeancroy** [comment]
snippets is a different issues. I believe the list of snippets is hard-coded to be on top.

**Comment by florianb** [comment]
:disappointed: Any hints where i should start searching? I guess its both, unusual to tweak the fuzz-priorities and not that easy to be done in a package.

**Comment by florianb** [comment]
@jeancroy i found the occurence in the [language-ruby-on-rails](https://github.com/atom/language-ruby-on-rails/search?utf8=%E2%9C%93&q=assert_no_difference)-package. It seems not being treated special by the language-pack.

**Comment by jeancroy** [comment]
Your issue is related to this one: https://github.com/atom/autocomplete-plus/issues/465
Eg every provider manage their own ordering, and we show all item of provider A, before any item of provider B

Original issue (transr) is related to the fuzzaldrin algorithm. A limited testing with fuzzy finder is being done, see https://github.com/atom/fuzzaldrin/pull/22

**Comment by florianb** [comment]
Thanks @jeancroy! :+1:

**Comment by 50Wliu** [comment]
fuzzaldrin-plus is now default.
