### ISSUE TITLE
Code snippets inside tag attributes

### ISSUE THREAD

**Issue by jgibba** [atom/autocomplete-plus#509]
It would be awesome to allow code snippet hints to work inside of attributes.

Currently mytag src = "my_code_snippet_hint_here" will not render code snippet autocomplete options inside tag attribute quotes.

This editor is amazing! Thanks!

Jon

**Comment by benogle** [comment]
Thanks for the report! Closing this in favor of https://github.com/atom/autocomplete-snippets/issues/55
