### ISSUE TITLE
Scrolling through Autocomplete breaks App's UI

### ISSUE THREAD

**Issue by izuzak** [atom/autocomplete-plus#511]
_From @silvestreh on June 22, 2015 19:4_

Kind of a strange bug. At first I thought my theme was at fault, but then I switched to One Dark UI and the bug was still there.

The reproduction steps are pretty easy. Open the autocomplete menu, then scroll it using the arrow keys. The entire UI will "move" up, making the top parts of the app (tabs, for example) non accesible.

Here, I made a GIF to explain myself better.

![atombug](https://cloud.githubusercontent.com/assets/1133339/8290257/2979bf0a-18f8-11e5-8ef9-0799115467bd.gif)

I tried searching through the issues but couldn't find a related issue (maybe my searching keywords sucked)

###### EDIT with actual information

Atom is version `0.211.0`
OS is `Mac OS X 10.10.3`

The expected behavior is for the rest of the UI not to move while scrolling an autocomplete list. The console on Dev tools doesn't print any errors.

_Copied from original issue: atom/atom#7372_

**Comment by izuzak** [comment]
Thanks for the report, @silvestreh -- I was able to reproduce this. /cc @benogle 

Also, this sounds a bit similar to https://github.com/atom/autocomplete-plus/issues/500

**Comment by DionisiusMayr** [comment]
Wops, didn't see this issue before reporting mine (https://github.com/atom/autocomplete-plus/issues/517) I believe they are the same, but I put some extra info on my issue report that might be useful (extra info is always a good thing. :smile: ).

**Comment by izuzak** [comment]
Thanks @DionisiusMayr :bow:

> extra info is always a good thing.

That's true, but having two issues for the same problems is not as good. :smile: I'll close your issue in favor of this one, so please add the description from the issue as a comment here if you'd like.

**Comment by DionisiusMayr** [comment]
Sure!

I am having the same issue here, but if you have a small amount of options in the auto-complete menu this doesn't happen with me.

I've seen this bug on versions prior to 1.0 and both on Windows and on Debian OS.

**Comment by benogle** [comment]
Crappy. It's scrolling the workspace, likely because of the browser's `scrollIntoView` method: https://github.com/atom/autocomplete-plus/blob/a7a41d8be6da9d2b499cd7634b747f76a5e1b1fd/lib/suggestion-list-element.coffee#L215

We probably should write our own that only scrolls the suggestion list.
