### ISSUE TITLE
AutocompleteManager.deprecateForSuggestion is deprecated.

### ISSUE THREAD

**Issue by nmn** [atom/autocomplete-plus#512]
Autocomplete provider 'Object(undefined)'
returns suggestions with a `label` attribute.
The `label` attribute is now `rightLabel` or `rightLabelHTML`.
See https://github.com/atom/autocomplete-plus/wiki/Provider-API
```
AutocompleteManager.deprecateForSuggestion (/Users/nmn/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:255:11)
<unknown> (/Users/nmn/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:165:29)
```

**Comment by benogle** [comment]
What providers do you have installed? This is an issue of some outdated provider.

**Comment by nmn** [comment]
This issue was basically submitted automatically by Atom. I think it has solved itself since. Will create another Issue, if this happens again.
