### ISSUE TITLE
Don't show suggestions on space or comma

### ISSUE THREAD

**Issue by dsandstrom** [atom/autocomplete-plus#513]
Apologies if this has been brought, but I didn't see an open issue.  When using scss, I get suggestions after typing a comma or space.  I use enter to confirm a suggestion so I often end up with something like:
```scss
h1,width: |
```
when I wanted:
```scss
h1,
| 
```
At the least, I don't think there should be any suggestions when the previous character is a space.  It would also be helpful to have no suggestions when the previous character is a comma.

**Comment by jasenc** [comment]
Having the same issue, I changed the default key binding to be tab instead of enter, but now it just does the same thing with tab.

If the issue can't be solved, it would be nice to figure out how to make enter + tab be the only way to accept the autocomplete.

**Comment by olafgleba** [comment]
+1

It slows down writing scss/css where multiple selectors arise on a regular base.

**Comment by jasenc** [comment]
+1

@olafgleba is exactly right, and it happened one time trying to reformat html, but it doesn't seem to be happening since 1.0

**Comment by olafgleba** [comment]
@jasenc , all occurs with Atom 1.0 (since i switched from ST just a several days ago).

**Comment by arjanvanderleden** [comment]
+1 
It also happens unwanted when editing javascript objects

**Comment by dsandstrom** [comment]
Thanks for working on this, however the original issue wasn't fixed.  I'm using Atom 1.0.3 and autocomplete-css 0.9.0

**Comment by benogle** [comment]
Can you make a gif and paste it in here? I guess I am not understanding the usecase

**Comment by dsandstrom** [comment]
http://screencast.com/t/e0Sol5W8

I noticed it doesn't happen on the outer selector.  Just when the selector is nested.

**Comment by benogle** [comment]
Ok, noted, thanks for the screencast

**Comment by benogle** [comment]
Thanks for the screencast. It should be fixed for real this time.

**Comment by dsandstrom** [comment]
That works great, thanks.
