### ISSUE TITLE
[CSS][Request]: !important and initial values

### ISSUE THREAD

**Issue by arielnoname** [atom/autocomplete-plus#514]
Hello,

It doesn't show autocompletion for initial and !important on CSS

    #container {
    width: initial !important;
    }

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/autocomplete-css?

**Comment by arielnoname** [comment]
@mnquintana I don't know how to move it, so I'll close it and post it again in that branch.
Thanks man.
