### ISSUE TITLE
Wrong autocompletion of begin keyword in Tex files

### ISSUE THREAD

**Issue by FlyingPumba** [atom/autocomplete-plus#516]
Hi ! When I type ```\begin``` Atom gives me the option to autocomplete, and then it completes as:
```
\\begin{env}
\end{env}
```
Note that the _begin_ keyword has an extra "\", and it should be:
```
\begin{env}
\end{env}
```
Atom version is: 1.0.0
Latexer package version is: 0.2.3
Latex package version is: 0.24.2
Language-latex package version is: 0.6.1
OS is: Ubuntu 14.04

**Comment by 50Wliu** [comment]
Could you please move this to the [latexer](https://github.com/Focus/latexer) repo?  Thanks.

**Comment by FlyingPumba** [comment]
@50Wliu Already did: https://github.com/Focus/latexer/issues/8
They say it's your issue.

**Comment by 50Wliu** [comment]
If you disable the latexer package, does the `begin` autocomplete not appear?  If it still appears, then it's most likely an issue on the latex package.

**Comment by 50Wliu** [comment]
Actually, it won't be a problem with `latex`, because that package doesn't offer autocomplete.
If \begin still appears after disabling latexer, could you please post the output of `apm list --installed` here?  Thanks.

**Comment by thomasjo** [comment]
I don't have latexer, yet have the completion. It's provided by language-latex. It's a snippet. And it's triggered by `begin`, not `\begin`.

**Comment by 50Wliu** [comment]
Thanks @thomasjo :)

**Comment by thomasjo** [comment]
This has been a problem for at least a year, but I've never managed to find a reasonable fix, so just don't type `\begin` until this eventually gets resolved.

**Comment by FlyingPumba** [comment]
@50Wliu @thomasjo  I was about to say I narrowed it down to the language-latex package :)
Thanks for the help ! I just tried typing ```begin``` and the autocompletion worked as expected.
