### ISSUE TITLE
Auto-complete opens a "bottom panel" after passing through all the options

### ISSUE THREAD

**Issue by DionisiusMayr** [atom/autocomplete-plus#517]
I made a gif showing the bug:

![bug_atom](https://cloud.githubusercontent.com/assets/10378472/8398902/9480db54-1dcf-11e5-9f13-5f99b276d745.gif)

Basically the STR would be open a .css file and start typing something that has many options (such as "font..."). Then you go through every option (using the down arrow key) and a strange panel will pop on the bottom of the screen.

I noticed that if you have a small amount of options in the auto-complete menu this isn't going to happen.

I don't know if it happens but I've seen this bug on versions prior to 1.0 and both on Windows and on Debian OS.

Note: This bug was first discussed here: https://discuss.atom.io/t/auto-complete-opens-a-bottom-panel-after-passing-through-all-the-options/18185

**Comment by izuzak** [comment]
See https://github.com/atom/autocomplete-plus/issues/511#issuecomment-116484126 (this seems to be a duplicate).
