### ISSUE TITLE
Searching by displayText as opposed to text

### ISSUE THREAD

**Issue by one-more-minute** [atom/autocomplete-plus#518]
I'm trying to make a latex completions plugin which replaces e.g. `\alpha -> α`

I have completions which look like this:
```coffeescript
[{text: 'α', displayText: 'alpha', replacementPrefix: prefix} # e.g. prefix = "\alp"
{text: 'β', displayText: 'beta', replacementPrefix: prefix}]
```
At the moment these always appear in the same order, so it'd be good to have autocomplete-plus fuzzy match on the `displayText`.

**Comment by benogle** [comment]
You can filter and sort them anyway you want in your provider. Can you point me to your provider? Or paste in some code?

**Comment by one-more-minute** [comment]
Ok, I went back to this and found that I couldn't get my example working again. I'm going to try a completely different approach to this.
