### ISSUE TITLE
"Keymap For Navigating The Suggestion List" missing from preferences

### ISSUE THREAD

**Issue by jeffpamer** [atom/autocomplete-plus#519]
The documentation states you are able to modify the following in `Preferences`:
- Keymap For Confirming A Suggestion
- Keymap For Navigating The Suggestion List

But the suggestion list navigation option doesn't appear anywhere I can find. Am I missing something?

**Comment by 50Wliu** [comment]
They're not in the global settings (ie the ones you see when hitting <kbd>Cmd+,</kbd>).  To see them you have to click on Packages on the left-hand side in Settings and then search for Autocomplete Plus.

**Comment by jeffpamer** [comment]
Sorry if I didn't make that clear, but I'm looking at the package settings ...

**Comment by jeffpamer** [comment]
![image](https://cloud.githubusercontent.com/assets/888818/8415792/4b78933e-1e6f-11e5-9ef6-a208df3cd314.png)

Keymap for Confirming A Suggestion, but no option for Navigating Suggestion List.

**Comment by 50Wliu** [comment]
Sorry about that.  It's missing from my settings too (Atom 1.0.0).  I'm assuming it got removed somewhere down the line and the README wasn't updated to reflect that.

**Comment by 50Wliu** [comment]
Aha, it was removed in /b5fd30a.
/cc @benogle

**Comment by benogle** [comment]
This is now tied to `core:move-up` and `core:move-down`. I think there are docs on remapping these in the autocomplete context, but I cant find them. @joefitzgerald do you know? We should probably add them to the readme.

**Comment by joefitzgerald** [comment]
Fixed by https://github.com/atom/autocomplete-plus/issues/519.

**Comment by joefitzgerald** [comment]
@benogle this is documented here: https://github.com/atom/autocomplete-plus/blob/a7a41d8be6da9d2b499cd7634b747f76a5e1b1fd/README.md#usage

```coffeescript
'atom-text-editor:not(mini).autocomplete-active':
  'tab': 'unset!'
  'enter': 'autocomplete-plus:confirm'
  'up': 'unset!'
  'down': 'unset!'
  'ctrl-p': 'core:move-up'
  'ctrl-n': 'core:move-down'
```

**Comment by benogle** [comment]
Well, there you go. I clearly didnt look very hard.
