### ISSUE TITLE
How to breakpoint in atom --dev

### ISSUE THREAD

**Issue by jannavarro** [atom/autocomplete-plus#520]
I run atom --dev, Inspect Element and then opened KeymapManager in dev tools. I breakpoint at handleKeyboardEvent but when I run commands such as ctrl+shift+p or any command in my keymap.cson the method is not executed. Am I pointing at the wrong method? I also breakpoint helpers keydownEvent but it is not executed.

**Comment by joefitzgerald** [comment]
You need to open the developer tools (cmd-option-i). Then, reload specs in the spec suite window or press command-r. Note that many specs (the ones that test UI) may fail while the developer tools are open.

**Comment by jannavarro** [comment]
Hi @joefitzgerald thank you for your response. I already did what you mention but the code at keymapmanager does not get executed. However I am able to breakpoint on other classes such as AutocompleteProvider. I am moving this issue to atom editor as keymapmanager class is  not part of autocomplete-plus. Would you have thoughts why keymapmanager is not being debug?
