### ISSUE TITLE
Please provide pure JS api examples or more coffee examples

### ISSUE THREAD

**Issue by GradyD** [atom/autocomplete-plus#525]
Hey,

I am trying to create a provider for Apex and Visualforce using the 2.0 API. I have looked at the snippet, CSS, and HTML providers and I am still confused. I looked at the coffeescript as well as converting to JS. 

I think a better documented API or commented example files would be very helpful for those of us that are just starting out writing providers. Is there plans to do this?

Thanks

**Comment by benogle** [comment]
What specifically are you struggling with?

Did you see https://github.com/atom/autocomplete-plus/wiki/Provider-API#defining-a-provider ?

Here is a js conversion of the example in the docs:

```js
var provider = {
  selector: '.source.js, .source.coffee',
  disableForSelector: '.source.js .comment',

  inclusionPriority: 1,
  excludeLowerPriority: true,

  getSuggestions: function({editor, bufferPosition, scopeDescriptor, prefix}) {
    return new Promise(function(resolve) {
      resolve([{text: 'something'}])
    })
    
    // OR for synchronous
    return [{text: 'something'}]
  },

  onDidInsertSuggestion: function(options) {
  },

  dispose: function() {   
  }
}
```
