### ISSUE TITLE
Snippet inside a snippet

### ISSUE THREAD

**Issue by idleberg** [atom/autocomplete-plus#532]
I have noticed that a snippet might not work within another snippet. For instance, when I trigger a snippet with multiple tab-points and then trigger another snippet at one of these points, I can no longer use the <kbd>Tab</kbd> to jump to the remaining tab-points of the outer snippet.

Here's how you can reproduce this:

- Create an empty HTML document
- type `html` and hit <kbd>Tab</kbd> to complete to a HTML skeleton

You can now use <kbd>Tab</kbd> to jump between `<title>` and `<body>`, but let's continue the steps above with the following:

- With the cursor between the  `<title>` tags, type `img` and hit <kbd>Tab</kbd> to complete this (stupid thing to do, but this is for demonstration purposes only!)
- Hit <kbd>Tab</kbd> to complete again to jump between `src` and `alt`
- Hit <kbd>Tab</kbd> again and Atom will indent  `</title>` rather than jumping inside the `<body>`

For my understanding, that's a bug that should be addressed in the future.

**Comment by lee-dohm** [comment]
This belongs on the [snippets package](https://github.com/atom/snippets). Would you mind opening it there instead?
