### ISSUE TITLE
fuzzy-matching doesn't consider underscores

### ISSUE THREAD

**Issue by faressoft** [atom/autocomplete-plus#538]
fuzzy-matching doesn't consider underscores.

With PHP for example.
When we type `arrayse` it doesn't provide any suggestions ! It should provide at least `array_search` function. (I am using autocomplete-php provider).

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/1908658/8768475/83c5bf0c-2e8a-11e5-8710-d5a9dfc9e030.gif)

**Comment by jeancroy** [comment]
There should not be any particular problem with underscore, fuzzy matching is probably turned off for some reason.

[![Gyazo](http://i.gyazo.com/f055cb8ce5d58354e8a14de4752ef59e.gif)](http://gyazo.com/f055cb8ce5d58354e8a14de4752ef59e)

**Comment by benogle** [comment]
This is an issue with the autocomplete-php provider. Please open an issue on their repo. Thanks for reporting!
