### ISSUE TITLE
Language keywords should always be availabe, regardless of if they are already typed or not

### ISSUE THREAD

**Issue by YuriSolovyov** [atom/autocomplete-plus#540]
Taken from https://github.com/atom-archive/autocomplete/issues/71
Eg. `return`, `function`, `while` for JavaScript.

**Comment by benogle** [comment]
They can be added to each language with the `autocomplete.symbols.builtin.suggestions` key. See [language-css](https://github.com/atom/language-css/blob/0fcb9d9a49cf1bc4626df339706f491203834258/settings/language-css.cson#L16) for an example
