### ISSUE TITLE
Suggestion: use adaptive debounce

### ISSUE THREAD

**Issue by jeancroy** [atom/autocomplete-plus#541]
**Symptoms:**
 - high CPU during search
 - laggy keyboard input.

**Problems**
- Compute result list, then discard it before user see it
- Browser will queue keyboard events to allow us to do those "important" calculation, resulting in laggy keyboard.

**Solution:** increase `suggestionDelay`

**New Symptoms:** Laggy UI response time
**New Solution:**  ??

**Analysis:**

Proper setting of `suggestionDelay` depend on 
- User machine
- Project 
     - number of suggestion
     - average size of a suggestion

**Suggestion:**

Observe the actual time it takes will allow the UI to be as responsive as it can while helping high CPU or keyboard freeze. Allow a small overhead for variability.

````diff
--- lib/autocomplete-manager.coffee	(revision d26fb2c6c41fda361b1f318b56f4554615ae8da5)
+++ lib/autocomplete-manager.coffee	(revision )
@@ -130,7 +130,11 @@
     scopeDescriptor = cursor.getScopeDescriptor()
     prefix = @getPrefix(@editor, bufferPosition)
 
+    start = Date.now()
     @getSuggestionsFromProviders({@editor, bufferPosition, scopeDescriptor, prefix, activatedManually})
+    elapsed = 1.2*(Date.now()-start)
+    @suggestionDelay += 0.5*(elapsed - @suggestionDelay)
````

Magic number 1.2 is an overhead to account for variability. Range about 1.1 - 2.0
Magic number 0.5 is the weight of last observation vs older ones. Range 0.0 - 1.0 

I patched that location because `findSuggestions` is the function gated by the suggestionDelay here
https://github.com/atom/autocomplete-plus/blob/master/lib/autocomplete-manager.coffee#L410

----

Fuzzy finder could probably benefit from something similar, but I cannot find anything that look like a denounce in the first place.

**Comment by benogle** [comment]
I think we're going to stick with the static delay for now. We want the time to popup to be predictable, and reduce complexity in the code. Effort will be spent on making autocomplete faster sometime soon.

**Comment by jeancroy** [comment]
As you wish. I don't believe there's perceived unpredictability if "as fast as you can" sometime mean 35ms and sometime means 75. 

Code complexity is a valid point if there's no perceived benefit.
Moslty toyed with this idea on report fuzzy finder was super slow on large project.
