### ISSUE TITLE
Weird screen jump when scrolling past the end of an autocomplete list

### ISSUE THREAD

**Issue by zephraph** [atom/autocomplete-plus#548]
After going to the bottom of the autocomplete list the selection wraps around to the top. When that happens, I get a weird screen jump. 

![autocomplete_bug](https://cloud.githubusercontent.com/assets/3087225/8860974/f91fcd8c-314c-11e5-995c-344e16d00178.gif)

I'm running Atom 1.0.2 on win7

**Comment by benogle** [comment]
This should be fixed in 1.0.3 which should be out next week. Sorry about this. See #505, #511 and https://github.com/atom/autocomplete-plus/pull/528

**Comment by zephraph** [comment]
S'all good. Thanks.
