### ISSUE TITLE
Speed Suggestion: test "candidate must match first letter of prefix" before fuzzaldrin.filter()

### ISSUE THREAD

**Issue by jeancroy** [atom/autocomplete-plus#549]
Suggestion: test [first char of result must be first char of prefix]( https://github.com/atom/autocomplete-plus/blob/75412768dc7b2f97da5e52df2786d48e820ac00c/lib/fuzzy-provider.coffee#L145-151) before applying [filter()](https://github.com/atom/autocomplete-plus/blob/75412768dc7b2f97da5e52df2786d48e820ac00c/lib/fuzzy-provider.coffee#L139-143).
(Use first char test as a pre-processing step to filter(), instead of a post processing step)

**Rationale:**

Most of the haystack is not the query, so speed can be gained by quickly eliminating bad candidate.

- The test for the first letter (and !== prefix)
       - can discard a candidate in 1 string equality + 1 char comparison.
- `IndexOf` in exact match 
       - need N char comparison to discard a match.
-  fuzzaldrin.score() 
       - need at least 2 indexOf + character identification+floating point operations etc.

**Currently we do:**
- Compute relatively expensive score() on 100% of the candidate. 
- Filter > zero, maybe 5% remains.
- Filter resulting list again for "first letter" test which is relatively fast.

**Switching the order of test would do:**
- Assuming the candidates can be divided into 5 popular firsts letters (the more the better)
- Eliminate maybe 4/5 of the candidate with the fast "first letter" test
- Only need to compute expensive score() on 1/5 of the candidate. 

It's like opening the dictionary at the right letter before doing a full-text-search VS doing a full-text-search then testing if we are at the right letter.

Also `prefix[0].toLowerCase()`[L150](https://github.com/atom/autocomplete-plus/blob/75412768dc7b2f97da5e52df2786d48e820ac00c/lib/fuzzy-provider.coffee#L150) is loop invariant and don't need to be re-computed for each candidate.

**Comment by benogle** [comment]
Does this not do what you want: https://github.com/atom/autocomplete-plus/blob/da80f69d71831501aa073b7202b9ceb4903df649/lib/symbol-provider.coffee#L211

Also the other providers do the same: 

* [autocomplete-css](https://github.com/atom/autocomplete-css/blob/fbb6c65e102886deeffae563a2f2dfafe8d44f82/lib/provider.coffee#L158)
* [autocomplete-html](https://github.com/atom/autocomplete-html/blob/2ab8d02d04216100260b0d90822d8cb3a4c2008b/lib/provider.coffee#L105)
* [autocomplete-snippets](https://github.com/atom/autocomplete-snippets/blob/0504bc47f8ea9c2cf7fedaaa1d9c93f2c3555bf3/lib/snippets-provider.coffee#L23)

**Comment by jeancroy** [comment]
It does. I may have looked at the wrong code segment.

Using fuzzylandrin.score() however have some separate problem, because it prevent optimizations using the idea of precomputing stuff ahead of the candidate loop to get faster per item cost.

But that do not apply to fuzzaldrin as it is now, so it's not yet a concern.
Will close as you are already doing this.

**Comment by benogle** [comment]
I appreciate you looking for speed. Feel free to try some things out. Posting profiles before and after would be super helpful.
