### ISSUE TITLE
Autocomplete Suggestion Window Not Showing Up

### ISSUE THREAD

**Issue by girron** [atom/autocomplete-plus#551]
I am not getting Autocomplete suggestions at all when using Atom. I have made sure Autocomplete-us is enabled, and even disabled and then re-enabled but it still doesn't seem to work for me. I am running the newest version of Atom on Mac OS X Yosemite 10.10.4

**Comment by benogle** [comment]
Please quit atom completely and run `atom --safe`. Is the issue still there? More information on debugging: https://atom.io/docs/latest/hacking-atom-debugging

What kind of file are you in?

**Comment by dangerousdan** [comment]
I had this same problem. It turned out that the `php-introspector` package was causing no autocompleting on PHP files. It works fine after disabling the offending package.

**Comment by benogle** [comment]
Closing this due to in activity. If you have more information, please comment and we can reopen

**Comment by ShivamS136** [comment]
@benogle I tried safe mode... Then it was working fine.

But then I tried in normal mode but this time with an empty file, and it was working fine again.

But when I open a new file in a git repo, then it didn't work.

So outside git repo files, it's working fine but in git repo files, the Autocomplete is not working.
