### ISSUE TITLE
Mistake (Javascript forin snippet has lowercase object)

### ISSUE THREAD

**Issue by tqn** [atom/autocomplete-plus#553]
Close this, I'm way too sleepy and made a mistake :stuck_out_tongue: 

~~I am using Atom 1.0.3 and Windows 8.1 x64.
After selecting this:
![image](http://i.imgur.com/7lZ7J3p.png)
It generates:
![image](http://i.imgur.com/K4f02aP.png)
The `object.hasOwnProperty(variable)` has a lowercase `object`.
Apologies if this is in the wrong repository.~~

**Comment by kevinsawicki** [comment]
> Close this, I'm way too sleepy and made a mistake

Sure thing, closing out.
