### ISSUE TITLE
Basic autocompletion not working?

### ISSUE THREAD

**Issue by bjubinville** [atom/autocomplete-plus#555]
Hello,

I must be doing something incorrectly here, but I've spent the better part of an hour looking through issues and config but have yet to figure out why I'm unable to get basic completion to work using the Symbols provider.  The Fuzzy provider does the expected thing. 

Example (ruby):

```
class CompleteMe
  def you
    complet       # <-- No completion
  end
  
  private
  
  def complete_me
  end
end
```

atom: 1.0.3
autocomplete-plus: 2.19.0
os: Yosemite 10.4.4

Any help would be appreciated

**Comment by kevinsawicki** [comment]
it appears to be working for me:

<img width="292" alt="screen shot 2015-08-03 at 5 55 39 pm" src="https://cloud.githubusercontent.com/assets/671378/9050941/ec4d15fa-3a08-11e5-87ba-97c6613f972c.png">

What completions do you see?

**Comment by bjubinville** [comment]
@kevinsawicki nothing at all.  I'm going to reinstall the plugins and see if that fixes anything

**Comment by bjubinville** [comment]
Looks to be something conflicting with https://github.com/aki77/atom-autocomplete-ctags.  Once I disabled this package, things worked as expected. I'll follow up over there.  Many thanks.
