### ISSUE TITLE
 autocomplete-plus is eating whitespace

### ISSUE THREAD

**Issue by stepancar** [atom/autocomplete-plus#561]
Hello!
I created [issue for atom-typescript](https://github.com/TypeStrong/atom-typescript/issues/525) which uses this project for autocomplete.
What do you think about it?

**Comment by thomasjo** [comment]
I am unable to reproduce this using a fairly pristine Atom. It would be great if you can provide an example that is reproducible in safe mode (`atom --safe`).

**Comment by basarat** [comment]
> I am unable to reproduce this using a fairly pristine Atom

You are right.

![whitespace](https://cloud.githubusercontent.com/assets/874898/9265012/68433e18-4270-11e5-8849-298c7c2fa21b.gif)


I'll investigate more :rose: Thanks!

**Comment by jeancroy** [comment]
@basarat  The autocomplete in your other screenshot is using something else than vanilla. For example we can see `var` next to the `ref` that eat the white-space.
