### ISSUE TITLE
Cannot find package in Atom

### ISSUE THREAD

**Issue by rugk** [atom/autocomplete-plus#563]
![autocompleteplusnotthere](https://cloud.githubusercontent.com/assets/11966684/9389168/e5acaf08-4769-11e5-807d-5af8c6621312.PNG)

Or on the website:
https://atom.io/packages/search?q=autocomplete-plus ([archived version](https://atom.io/packages/search?q=autocomplete-plus))

**Comment by mnquintana** [comment]
Just out of curiosity, why are you looking for it in Install Packages? autocomplete-plus ships with Atom, so it's already installed.

**Comment by rugk** [comment]
Oh, yes indeed found it.

But why is it named 'autocomplete-**plus**' in this case? Where is the 'autocomplete-standard'? :wink:

**Comment by mnquintana** [comment]
There was an older implementation of autocomplete, but it was replaced by a community-driven autocomplete-plus - you can read more about it here: http://blog.atom.io/2015/05/15/new-autocomplete.html
