### ISSUE TITLE
Keep limiting the width of the popup but provide way to expand selection.

### ISSUE THREAD

**Issue by ghost** [atom/autocomplete-plus#566]
Hello

Ticket #389 deals with the fact that very long descriptions make the tooltip too wide; in my case the tooltip has the correct width but ellipsizes the rightLabel. This seems like correct behavior, however I was wondering if it would be a good idea to have a way to 'expand' this ellipsized text. For example:

![test](https://cloud.githubusercontent.com/assets/6823929/9690205/36dc1f1c-533b-11e5-8a41-46a06c616526.png)

I've used the rightLabel here to display the class/interface/trait the method is originating from, which works fine, but seeing as the complete name is fairly long, there is no way this can ever be visible to the user. (Perhaps the rightLabel was not intended for this purpose?)

I've noticed that PHPStorm handles this by letting the selected row 'pop out' of the tooltip, essentially increasing the width of just that row to extend past the tooltip box itself so you can temporarily view the complete text. The styling of this doesn't seem very pretty, but it may be helpful in finding a better way.

(Also, `testChaining` seems to have odd styling because of its length, but that might be another issue.)

Thanks in advance

**Comment by benogle** [comment]
What about a tooltip when hovered? Using the title attribute of the element?

**Comment by hotoiledgoblinsack** [comment]
Would this mean adding a title attribute to a HTML element that is then inserted in the `rightLabelHTML`? That could indeed work, perhaps there can be one large tooltip for each row that contains the complete row contents (or the title attributes of each 'column' of the row), if other elements of the row can also be ellipsized (such as `leftLabelHTML`).

**Comment by meritozh** [comment]
I also hava same problem. I hope you can just highlight the line that you choose. Do not change the style such as font size.
