### ISSUE TITLE
Idea - Trigger the descriptionMoreURL when pressing e.g. F1 during autocompletion.

### ISSUE THREAD

**Issue by ghost** [atom/autocomplete-plus#567]
Hello

It would be handy to have a keyboard shortcut to open the `More...` URL in the browser when it is present for the selected row during autocompletion (e.g. by pressing the F1 key). (It would basically be identical to clicking the link but remove the need to reach for the mouse.)

Thanks in advance

**Comment by benogle** [comment]
I like this idea :+1: PRs welcome :)

**Comment by scarecrow21** [comment]
Hi. I'm new to open source. Would someone please help me go about fixing this bug?

**Comment by zzulanas** [comment]
heyo! I'll try and work on this one, trying to also get started with open source

**Comment by leroix** [comment]
merged #919
