### ISSUE TITLE
Idea - Adding descriptionHTML in the Provider API

### ISSUE THREAD

**Issue by JohnnyCrazy** [atom/autocomplete-plus#569]
Hi,

I think it would be useful having a `descriptionHTML`.(like there already is `leftLabelHTML` for the left label)
This could be e.g useful for having short hyperlinks inside the description. Also it would generally enable the styling of the description.

Currently, it's not possible adding any kind of styling to the description, since [the textContent-property is set](https://github.com/atom/autocomplete-plus/blob/42660ee4d794d1403881a9fc20fadfb29014f96e/lib/suggestion-list-element.coffee#L104)

**Comment by benogle** [comment]
Closing in favor of #423

**Comment by JohnnyCrazy** [comment]
Woops, sorry, must have been completely blind :see_no_evil:
