### ISSUE TITLE
Support function autocompletion like snippets

### ISSUE THREAD

**Issue by steelbrain** [atom/autocomplete-plus#570]
I met a guy in the IRC today who proposed that he should have variable names even after autocomplete. Imagine that you have an autocomplete entry `is_function($function_name, $autoload)`. When you click it or press tab, it becomes `is_function()`.

I propose that we should introduce an option which doesn't replace those `$variable_names` in the function declaration and instead represents them as snippets. I have done this in my [autocomplete-hack](https://github.com/steelbrain/AutoComplete-Hack/blob/master/lib/autocomplete-hack.coffee#L71-L84) package and we LOVE it! Every single variable name is a snippet entry, You can cycle through them using tabs.

**Comment by benogle** [comment]
Can you paste in a gif?

**Comment by nonameolsson** [comment]
This sounds great. Any update @steelbrain?

**Comment by steelbrain** [comment]
Sorry for not being as active. I'd like to close this issue as invalid.

The issue is that the default completions provided by grammers are treated as text instead of snippet and when someone writes `is_function` and autocompletes, they get `is_function()` instead of `is_function(${0:$function_name})` snippet which renders to `is_function($function_name)`. It's more of a problem with the grammars and not a problem with AC+

This is working well in all the intelligent autocomplete plugins who know the signatures of the functions they are completing so the fix for the end-users would be to install one of those.

Thanks everyone
