### ISSUE TITLE
Autocomplete windows stops showing up

### ISSUE THREAD

**Issue by JonnyCBB** [atom/autocomplete-plus#578]
Basically when I start Atom my autocomplete seems to work fine but after a certain amount of time, the autocomplete window stops appearing. Ctrl-Space doesn't work and I'm not sure why it's doing this. If I close Atom and then reopen it, the autocomplete window appears as expected for a little while and then after a while just stops appearing. I haven't worked out why it does this.

I saw a similar [issue #551](https://github.com/atom/autocomplete-plus/issues/551), but because there was no mention that the window seemed to work at any point I thought the issue might be different.

**Comment by mnquintana** [comment]
Can you try quitting Atom, then reopening it in safe mode (`atom --safe`) and seeing if you can reproduce this? What kind of file (ie. language) is this happening in?

**Comment by JonnyCBB** [comment]
It's happening in .jl (julia) files.
I just tried quitting atom and opening in safe mode as you suggested. This changed the theme and also stop highlighting my code (I don't know what the expected behaviour is in safe mode).

The autocomplete window did appear for various simple words e.g. "the", "which" etc. but not for anyof my variable names (maybe due to a similar reason that the file was not highlighted). The window didn't ever stop showing up though so I guess that's a plus.

**Comment by mnquintana** [comment]
Are you using an autocomplete provider for Julia? Can you post a list of your installed packages? (`apm list --installed`)

[Safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) loads Atom without any community packages and without loading your init script.

**Comment by JonnyCBB** [comment]
Yes I am using [autocomplete-julia](https://atom.io/packages/autocomplete-julia).

My list of installed packages are:
>apm list --installed
C:\Users\jonathan\.atom\packages (41)
├── atom-beautify@0.28.12
├── atom-html-preview@0.1.11
├── atom-material-syntax@0.2.4
├── atom-material-ui@0.6.1
├── autocomplete-julia@0.1.0
├── autocomplete-plus-python-jedi@0.3.6
├── autocomplete-python@0.5.3
├── color-picker@2.0.11
├── compare-files@0.6.2
├── highlight-line@0.11.0
├── highlight-selected@0.10.1
├── Hydrogen
├── ink@0.0.0
├── julia-client@0.0.0
├── language-c@0.48.0
├── language-julia@0.4.1
├── language-latex@0.6.1
├── language-matlab@0.1.1
├── latex@0.25.1
├── latex-completions@0.3.0
├── latexer@0.2.7
├── linter@1.5.2
├── linter-chktex@1.0.0
├── linter-pylint@1.0.0
├── markdown-format@2.5.1
├── markdown-pdf@1.3.9
├── markdown-preview-plus@2.1.1
├── markdown-toc@0.3.0
├── markdown-writer@1.9.3
├── mathjax-wrapper@0.1.0
├── merge-conflicts@1.3.5
├── minimap@4.13.3
├── pdf-view@0.23.0
├── pigments@0.15.0
├── preview-inline@0.4.4
├── python-jedi@0.3.3
├── script@2.26.4
├── tabs-to-spaces@0.11.1
├── tool-bar@0.1.9
├── tool-bar-main@0.0.8
└── trailing-spaces@0.3.2

**Comment by vhKarel** [comment]
So I'm having the same issue, it seem to be because autocomplete switches to a different port after a certain amount of time. After that it gives an error on every keypress.
![screen shot 2015-10-13 at 10 28 16](https://cloud.githubusercontent.com/assets/9048726/10449655/3f141234-7195-11e5-90d7-4902f6b57195.jpg)
![screen shot 2015-10-13 at 10 28 38](https://cloud.githubusercontent.com/assets/9048726/10449654/3f13b5dc-7195-11e5-8fd7-2232b40b33c9.jpg)

**Comment by benogle** [comment]
@vhKarel your issue looks like an issue with the ternjs package: https://github.com/tststs/atom-ternjs

**Comment by JonnyCBB** [comment]
So my original problem was about the fact that after a short period of time the autocomplete window wouldn't work when I was writing in **Julia (.jl)** files. This is still the case.   
But I also get the problem that autocomplete **doesn't work at all with Python** files.   
When I open atom in safe mode, the autocomplete functionality comes back (for Python files at least), so I assume that this is a problem with one of my installed community packages. Here is my current list of installed packages. Are you aware of any that would cause problems? If not then I'll go through disabling them until I find the culprit.   
If it helps, I'm now using Atom version 1.3.2 on Windows 10.   

C:\Users\jonathan>apm list --installed
C:\Users\jonathan\.atom\packages (50)
├── atom-beautify@0.28.19
├── atom-html-preview@0.1.13
├── atom-material-syntax@0.2.10
├── atom-material-ui@0.8.0
├── autocomplete-bibtex@0.6.2
├── autocomplete-julia@0.1.0
├── autocomplete-python@1.2.4
├── color-picker@2.0.14
├── compare-files@0.6.2
├── highlight-line@0.11.0
├── highlight-selected@0.11.1
├── Hydrogen
├── ink@0.0.0
├── julia-client@0.0.0
├── language-batch@0.3.3
├── language-c@0.51.1
├── language-julia@0.5.0
├── language-latex@0.6.1
├── language-matlab@0.1.1
├── language-svg@0.9.0
├── latex@0.28.2
├── latex-completions@0.3.0
├── latexer@0.2.7
├── linter@1.11.3
├── linter-flake8@1.9.3
├── linter-pylint@1.2.0
├── markdown-format@2.5.1
├── markdown-pdf@1.3.9
├── markdown-preview-plus@2.2.2
├── markdown-toc@0.4.1
├── markdown-writer@2.1.1
├── mathjax-wrapper@0.1.0
├── merge-conflicts@1.3.7
├── minimap@4.19.0
├── minimap-bookmarks@0.2.0
├── minimap-find-and-replace@4.4.0
├── minimap-git-diff@4.1.8
├── minimap-highlight-selected@4.3.1
├── minimap-linter@1.1.0
├── minimap-pigments@0.1.7
├── pdf-view@0.37.0
├── pigments@0.19.5
├── preview-inline@0.5.1
├── python-jedi@0.3.6
├── script@3.3.0
├── tabs-to-spaces@1.0.1
├── tool-bar@0.1.9
├── tool-bar-main@0.0.8
├── trailing-spaces@0.3.2
└── wordcount@2.4.1

**Comment by JonnyCBB** [comment]
So the problem with the Python autocomplete seems to be resolved. I uninstalled the python-jedi package because it also had autocompletion as one of its features which I don't need because I also have the autocomplete-python package. So that's fine.   

However the original issue regarding the Julia files (the autocompletion initially works and then after a while stops working) still persists. I still have no idea why this is happening.

**Comment by JonnyCBB** [comment]
So it turns out I'm not the only one having this problem since it's now been [raised as an issue](https://github.com/vindvaki/atom-autocomplete-julia/issues/7) for the [atom-autocomplete-julia](https://github.com/vindvaki/atom-autocomplete-julia) package.   
I'm going to use a different autocomplete provider for Julia so I'm going to close this issue.
