### ISSUE TITLE
choosing a css class causes newline instead

### ISSUE THREAD

**Issue by lpommers** [atom/autocomplete-plus#583]
Sometimes, when writing html and choosing a css class from auto-complete, a newline is created from where ever you stop typing instead.

![class](https://cloud.githubusercontent.com/assets/5764316/10012389/e121731c-6107-11e5-90c8-7f1e3cddd26c.gif)

**Comment by thomasjo** [comment]
Are you able to reproduce this in safe mode?

**Comment by lpommers** [comment]
nope, so maybe a package I have installed is interfering?

**Comment by thomasjo** [comment]
Yes, correct! Do you have Emmet installed?

**Comment by lpommers** [comment]
yeps

**Comment by fnkr** [comment]
I have Emmet installed too but no problems.

![Screencapture](https://ge1.me/5d4ee130a16c42f7929d/raw)

**Comment by lee-dohm** [comment]
This was most likely caused by Emmet being installed and interfering with the built-in keymaps. Please let us know if this was not the case!
