### ISSUE TITLE
How works the attribute selector?

### ISSUE THREAD

**Issue by sagax85** [atom/autocomplete-plus#585]
Hi, 

I'm trying to code a provider, but have problems understanding how the attribute ```selector``` works.

I followed the basic example and have the following two files

**main.js**
```javascript
var provider = require('./provider');

module.exports = {
  activate: function() {
    console.log("activated");
  },
  getProvider: function(){
    return provider;
  }
};
```

**provider.js**
```javascript
module.exports = {
  selector: ".source.txt",
  filterSuggestions: true,

  getSuggestions: function(request){
    console.log(request);
    return [{text: "something"}];
  }
};
```

the plugin loads fine, so that's not the issue (and I also reload the atom every time I do changes). 

I tried ```selector:".source.txt"``` or ```selector:".txt"```, but nothing happened when I edited something on .txt files. It didn't work either for js files. BUT as soon as I set ```selector:"*"```, it works. Thus, how do I have to interpret the selector attribute? or what am I doing wrong that it doesn't work if I specify a file type.

Thanks for your help!

**Comment by jeancroy** [comment]
There's an issue for plain text file: https://github.com/atom/autocomplete-plus/issues/557, if that's the only kind of selector you have tried.

**Comment by sagax85** [comment]
i also tried other file types, and some I made up myself like ".bla". what exactly does the ```.source``` mean? is there somewhere a spec how the selector works?

**Comment by jeancroy** [comment]
maybe this ?
https://atom.io/docs/v0.139.0/advanced/scopes-and-scope-descriptors

and some other example here
https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers

**Comment by benogle** [comment]
Closing. Feel free to comment for if you need more help.

**Comment by MggMuggins** [comment]
I'm having the same problem with D source files (.d and .di). According to the dev tools, the selector should be .source.d (for both file types), same as js and every other language under the sun. The package loads fine, but getSuggestions is never called.
