### ISSUE TITLE
Help testing a new provider locally

### ISSUE THREAD

**Issue by evansalta** [atom/autocomplete-plus#601]
I am trying to develop a provider locally but I am having no luck getting it to work. I have the package in `~/.atom/packages/autocomplete-freemarker` and I also have the accompanying `language-freemarker` package installed (for the selector). I have tried both CoffeeScript and JavaScript... and still nothing.

I don't see it as a source in the dev tools either. Is there something I need to do for atom to load my package?  

I'm using OS X Yosemite with Atom 1.0.19 and I'd appreciate any suggestions.

**Comment by 50Wliu** [comment]
Have you executed `apm install` inside `autocomplete-freemarker`?

**Comment by evansalta** [comment]
Yes

**Comment by evansalta** [comment]
FreeMarker is often used with HTML, so it's loading the HTML autocomplete suggestions, and I'm wondering if the FreeMarker ones aren't getting recognized due to that.

**Comment by evansalta** [comment]
I believe figured it out--the language for FreeMarker in atom is missing symbols. Once I added them things started working.
