### ISSUE TITLE
Recent change broke the matcher

### ISSUE THREAD

**Issue by yamsellem** [atom/autocomplete-plus#603]
Atom 1.1.0.
AutoComplete+ 2.22.0.

To reproduce the problem; select a variable named `color`, cmd+d two times.
This will select the string `"color"` and an array named `colors`.

This is not what it's expected from autocomplete.
And this is not how it was working not so long ago (it was just selecting same variables).
Is this the desired behavior?

![text matching](https://cloud.githubusercontent.com/assets/606754/10864247/5f5e3b12-7fe8-11e5-8834-237ade3d7c1a.png)

Does is has something to do with [ternjs](https://github.com/tststs/atom-ternjs)?

**Comment by 50Wliu** [comment]
This is unrelated to autocomplete-plus and is actually from the find-and-replace package.  To change this behavior, open the find panel (<kbd>Cmd+d</kbd>) and select the Whole Word option.

**Comment by yamsellem** [comment]
@50Wliu thanks for your answer. Their is no "whole word" option in find-and-replace 0.181.0 settings. Are you sure it's there?

![capture d ecran 2015-11-03 a 15 37 31](https://cloud.githubusercontent.com/assets/606754/10910646/d9977286-8240-11e5-985b-a33c8d1d437c.png)

**Comment by 50Wliu** [comment]
Sorry, I meant cmd+f, not cmd+d (so that the find-and-replace panel appears).  Then there should be 4 options on the right-hand side (whole word, regex, case insensitive, and I forget the last one).

**Comment by yamsellem** [comment]
@50Wliu thanks for your help, but I don't get it. This is the search panel, the "whole word" option is supposed to change the current search not atom global behavior.

And, in fact, this selects variables and strings.
This was not the behavior of atom before and I don't understand 1. why this has changed 2. why this is not getting broader coverage, I guess people should become crazy as I do with this.

This ruins refactoring.

![capture d ecran 2015-11-03 a 15 56 03](https://cloud.githubusercontent.com/assets/606754/10911106/73f00ec2-8243-11e5-8ef9-335de2598c97.png)
