### ISSUE TITLE
Provider does not work for *-selector when file starts with a dot

### ISSUE THREAD

**Issue by cemrich** [atom/autocomplete-plus#605]
This could be a windows (10) issue. I've written a very simple provider not tied to no special grammar:
```js
'use babel';
    
export default class AutoSuggestProvider {
    constructor() {
         this.selector = '*';
    }

    getSuggestions(suggestionRequest) {
        return [{ text: 'test' }];
    }
}
```
This works as expected for every filetype, returning 'test' as suggestion regardless of the prefix. On files beginning with a dot (e.g. `.gitignore` or `.editorconfig`) however, no suggestions are returned. 

I am using atom 1.1.0 and autocomplete-plus 2.22.0 on a windows 10 machine.

**Comment by benogle** [comment]
This might be a dupe of https://github.com/atom/autocomplete-plus/issues/557

**Comment by cemrich** [comment]
I'm so sorry but I resolved this issue. I've missed the `File Blacklist` setting which defaults to `.*`. This way a fresh install of atom won't provide autocompletion for files starting with a dot - regardless of the providers selector.

Sorry again for the noise.
