### ISSUE TITLE
auto-complete suggestions unreadable when mixing dark and light themes

### ISSUE THREAD

**Issue by braver** [atom/autocomplete-plus#608]
When using One-Light-Syntax with One-Dark-UI, some of the information in the tooltip becomes unreadable.

One-Light
![screen shot 2015-11-05 at 12 24 32](https://cloud.githubusercontent.com/assets/2543659/10967161/dd316428-83b8-11e5-9f7d-a33669eb7874.png)

Monokai
![screen shot 2015-11-05 at 12 24 45](https://cloud.githubusercontent.com/assets/2543659/10967166/dfd9b27a-83b8-11e5-8638-a7b0f219518f.png)

**Comment by benogle** [comment]
Ah, crappy. We should probably explicitly style the description text with the UI text color.

**Comment by braver** [comment]
I can look into it tomorrow.

**Comment by jneubrand** [comment]
[This can probably be closed since #609 has been merged]

**Comment by benogle** [comment]
Word, thanks

**Comment by jneubrand** [comment]
No problem!
