### ISSUE TITLE
Grammar indentation triggering

### ISSUE THREAD

**Issue by fruggiero** [atom/autocomplete-plus#610]
The autocomplete suggestion seem's to interfere with the custom grammar indentation pattern.
In my grammar i have no autocomplete provider (so that means, i think, it is using the default fuzzy provider of autocomplete-plus) but i have indentation patterns correctly setted up for the grammar.
If i i manually type the keyword that must decrease the indentation i have the correct behaviour (the one that i wrote for the grammar), but if i use what the suggestion box show me (by pressing enter) the indentation doesn't trigger.

Attached a gif to show better the problem:
(first i use the autocomplete which don't indent correctly, then i write manually the entire keyword and the indentation will trigger correctly)

![38f7f189944420711469027a08e5ce2caa4644b0](https://cloud.githubusercontent.com/assets/4760358/11157682/1f2ce226-8a53-11e5-8aed-6ce82f6b58db.gif)

**Comment by kevinsawicki** [comment]
It looks like it uploaded a `.png` and not a `.gif`. Do you have an animated GIF available that shows the problem? Thanks.

**Comment by feddstylez** [comment]
Sorry, here it is:

![38f7f189944420711469027a08e5ce2caa4644b0](https://cloud.githubusercontent.com/assets/4760358/11157682/1f2ce226-8a53-11e5-8aed-6ce82f6b58db.gif)

**Comment by fruggiero** [comment]
Made a pull request:


https://github.com/atom/autocomplete-plus/pull/612
