### ISSUE TITLE
Format of autocompleted boolean HTML attributes

### ISSUE THREAD

**Issue by willnwhite** [atom/autocomplete-plus#613]
E.g. checked is a true/false checkbox attribute, and rather than Atom autocompleting to `checked=""`, implying checked takes a value, it should just complete to `checked`, implying true. I had to read the HTML spec to learn that the actual presence or absence of boolean attributes were their true and false values, and Atom did not help me learn this (for ages I was trying `checked="false"` to no avail).

**Comment by benogle** [comment]
This issue was moved to atom/autocomplete-html#15
