### ISSUE TITLE
Tab doesn't confirm completition

### ISSUE THREAD

**Issue by alexandernst** [atom/autocomplete-plus#617]
Hitting tab won't confirm the selected option in the autocomplete dialog.

**Comment by benogle** [comment]
Can you paste in your autocomplete-plus config?

**Comment by alexandernst** [comment]
`"autocomplete-plus": {}`

**Comment by alexandernst** [comment]
I just discovered that I can't reproduce this in `atom --safe`. I must blame some of the plugins that I hve installed.

**Comment by benogle** [comment]
emmett?

**Comment by alexandernst** [comment]
Give me a moment, I'll try it right now. Thanks for the tip

**Comment by alexandernst** [comment]
Yup, that was it!
