### ISSUE TITLE
Consume suggestion text following the cursor consumes parentheses

### ISSUE THREAD

**Issue by nmote** [atom/autocomplete-plus#621]
If a provider returns `foo()` as the suggestion, `autocomplete-plus` will, by default, consume a right parenthesis after the cursor.

For example, let's say I have my cursor after 'fo' below:

`bar(fo)`

I hit enter to confirm the `foo()` item, and what I get is:

`bar(foo()`

What I should get is:

`bar(foo())`.

It seems that the problem is that [getSuffix](https://github.com/atom/autocomplete-plus/blob/5d883caef25a89164772b457568c0e06bd62b99b/lib/autocomplete-manager.coffee#L388) consumes non-identifier characters.

I'm not sure what a good way to solve this is while keeping autocomplete-plus language agnostic. My knee-jerk reaction is for us to only use a suffix if it consists of typical identifier characters. That is distasteful since it makes assumptions about the languages.

We could also add an autocomplete suggestion property to indicate whether that suggestion is eligible to replace its suffix. That is also not ideal since it adds complexity to the provider API, and many providers would overlook it.

However, I think it's clear that this needs to get fixed. The current user experience is subpar.

I am happy to implement either of these ideas, or to entertain others.

**Comment by nmote** [comment]
I've implemented both ideas. Take a look!

**Comment by nmote** [comment]
To be clear, I do not intend for both of these to be merged.

**Comment by benogle** [comment]
What if this was an autocomplete setting like `autocomplete-plus.suffixConsumeBlacklist` that defaulted to `)`? Then specific languages could override it wholesale and it could be overridden in settings. I like that a little more than forcing the provider to specify that.

You can also untick 

<img width="678" alt="screen shot 2015-11-20 at 5 30 47 pm" src="https://cloud.githubusercontent.com/assets/69169/11315751/7ad248ec-8fac-11e5-849e-8ee02057bfbc.png">

**Comment by nmote** [comment]
I'm aware of the setting, but disabling it disables some legitimately useful behavior in addition to fixing this problem. And I also believe that the right thing should happen by default. I don't want to have to tell everybody using Nuclide that they have to go change this setting in order to have autocomplete work properly.

I like the idea of making it a setting. Do you imagine that providers could include a suffixConsumeBlacklist property that would override what the user has in the settings? But, if they do not, it defaults to whatever characters are listed in that setting?

I think that's a great idea and I will go ahead and implement that.

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/atom/autocomplete-plus/pull/634. Thanks for getting the :baseball: rolling @nmote.
