### ISSUE TITLE
Don't insert function signature if the following character is a parenthesis

### ISSUE THREAD

**Issue by karlek** [atom/autocomplete-plus#625]
Hi!

In sublime the autocomplete feature is aware of the following character. If the next character is a parenthesis it doesn't insert the function signature.   

![Sublime](https://cloud.githubusercontent.com/assets/1278705/11318791/c06270e4-9060-11e5-942a-62e62c2e5162.gif)

Atom inserts the function signature every time.

![Atom](https://cloud.githubusercontent.com/assets/1278705/11318790/bddee7c6-9060-11e5-976d-d2004ad02e01.gif)

I'm not sure if this issue should be on the language level i.e `autocomplete-go`, but I found this problem in `autocomplete-python` as well so I created it here.

**Comment by Gert-dev** [comment]
I think this is more something that needs to be done on the language level, as autocomplete-plus is not (supposed to be) aware of the actual language. I've implemented the same behavior for PHP functions in [php-integrator-autocomplete-plus](https://github.com/Gert-dev/php-integrator-autocomplete-plus/blob/c1fb86ea9490fec0b5fe33a949660f6625154e34/lib/FunctionProvider.coffee#L30).

It literally shouldn't be more work than fetching the character after the passed trigger position and seeing if it is a paranthesis, after which you simply don't insert the function parameter list in the suggestion snippet or text.

**Comment by karlek** [comment]
Sounds logical! Then this issue can be closed :+1:
