### ISSUE TITLE
Support Markdown in description field

### ISSUE THREAD

**Issue by jordwalke** [atom/autocomplete-plus#626]
Shouldn't the formatting of the description allow "code fencing" such by using backticks?  In my `description` field, I supply some type information - which should be formatted using a monospace font (the one used in my editor) so that it renders as code. I believe the `autocomplete-plus` tutorial says the `description` field is a `doc-string` - which I believe implies that text in backticks should be rendered in monospace editor font. Either way, it sounds like a really good thing to have anyways.

**Comment by jordwalke** [comment]
Any comment on this? Perhaps the description field should accept pure HTML to make it easier to support all the edge cases that people will come up with.

**Comment by lee-dohm** [comment]
I think supporting Markdown in the description field is a good change. That's what we eventually did for the descriptions of configuration settings in Settings View.
