### ISSUE TITLE
20 second editor freeze when editing markdown file

### ISSUE THREAD

**Issue by Hurtak** [atom/autocomplete-plus#627]
I was editing some markdown file and my editor was iregularry (kinda randomly) freezing for 20+ seconds. I opened dev tools and recorder timelene and apperently autocomplete-plus is to blame. I am not able to reproduce 100% of times to give you clear guidelines but if you just jump around in the file and randomly press ctrl + space (autocomplete-plus:activate) you should be able to see it pretty quickly. As far as I know this bug is only happening in markdown files

__snippet of file on which i am able to reproduce__:

```markdown

## Typography

- always use bad typography for maximum clarity (eg use `--` instead of `&ndash;` or `–`)
- [typogr.js](https://github.com/ekalinin/typogr.js) plugin is used to fix these errors

| use   | converted into |
| ----- | ---------------|
| `...` | `…`            |
| `'`   | `‘` or `’`     |
| `"`   | `“` or `”`     |
| `--`  | `–`            |
| `---` | `—`            |

```

__I was able to record timeline in dev tools during one of these freezes__
file: __[TimelineRawData-20151122T094830.json](http://www.megafileupload.com/5wzu/TimelineRawData-20151122T094830.json)__
screenshot:
![](http://i.imgur.com/5booh3E.png)

__system__
Atom 1.2.3
putocomplete-plus 2.23.0

**Comment by nmote** [comment]
This is not a problem autocomplete-plus. One of your providers is misbehaving by making a synchronous filesystem call. If it really does need to look at the filesystem, it should make an asynchronous call so as not to block the entire main loop.

It looks like [autocomplete-paths](https://github.com/atom-community/autocomplete-paths) is the offending plugin. You can file an issue there or disable it for now.

As an aside, that call still shouldn't take 20 seconds. Something might be wrong with your filesystem or hard drive.

**Comment by lee-dohm** [comment]
Thanks for opening the issue on autocomplete-paths. Since this is not an Issue with autocomplete-plus, I'm going to close this. Thanks for the feedback!
