### ISSUE TITLE
Current file is ignored when autocompleting in PHP files

### ISSUE THREAD

**Issue by bakert** [atom/autocomplete-plus#632]
**Testing with `atom --safe` I think this is an issue with a package installed rather than autocomplete-plus. Please close this issue. I'd still love to know how to make new files that have not been saved and plain text files perform autocomplete from within themselves/other open files.**

Steps to reproduce:

1. Open a new file.
2. Add:
```php
<?php

class MyTest {
}
```
2. Type:
```php
$myTest = new My
```
3. Engage autocomplete either via Ctrl-Space or Cmd-Shift-P and choose off the menu.

Expected:

* Autocomplete fire automatically in step 3 and show MyTest as an option.
* Autocomplete will show MyTest as an option when fired manually.

Actual:

* Autocomplete does not believe it has a suggestion.

Tested on 1.3.0-beta6 and 1.0.18.

Some other interesting notes:

* If MyTest is defined in another file that is currently open it *will* be a suggestion to autocomplete. Even if the new file has not been saved and contains no PHP-ish symbols.
* Saving the file as MyTest.php doesn't make any difference to the behavior.
* If you perform the exact same test but save the file as MyTest.js it *will* work.

I'm happy to look into this myself but I'd love some suggestions on where to look/how to get started. Thanks!

**Comment by bakert** [comment]
I ended up filing this issue with the offending package: https://github.com/facebook/nuclide/issues/254

**Comment by 50Wliu** [comment]
Glad that you found the offending package.

Unfortunately I'm not sure how to get autocomplete working in the two scenarios you described, but make sure you don't have any suspicious settings that could be affecting it in your autocomplete-plus settings.
