### ISSUE TITLE
Keep fuzzy match, but only match results whose first char is the first char of input

### ISSUE THREAD

**Issue by chenglou** [atom/autocomplete-plus#647]
(Apologies if this has been raised before)

Coming from a Sublime Text background, I've rarely felt that e.g. the user typing `es` might have the intention of matching it against "helloT**es**t". It's almost always "**e**blabla**s**bla", aka the first letter of the input matches the first letter of the suggestions (which is ST's behavior). Is it possible to at least expose this as an option? Bonus is that this might also speed up things.

**Comment by lee-dohm** [comment]
Do you have the "Use Alternative Scoring" option selected? It may help things work better. It is still experimental though, so it is behind a configuration option for now.

**Comment by chenglou** [comment]
Yes I did have it enabled. I tried both scorings.

**Comment by benogle** [comment]
Currently the default providers match the first char. Which provider are you using? Can you add an image to clarify?

**Comment by chenglou** [comment]
Ah I see. I'm using the [Flow provider](https://atom.io/packages/nuclide-flow) for js. Maybe that's why. It matched `if` to `diff`.

Closing this then =). Thanks!
