### ISSUE TITLE
Use native API for scrollIntoView

### ISSUE THREAD

**Issue by steelbrain** [atom/autocomplete-plus#652]
The current scroll into view API is manually implemented and not-the-best solution ever. It has several bugs, including one that screws up the workspace if we press up arrow on first autocomplete item. Not sure if it has been fixed yet but I think we have a better way

I ran into a similar situation where I had to scroll manually the list items while writing the [intentions](https://github.com/steelbrain/intentions) package. I evaluated several options and ended up using

```js
Element.prototype.scrollIntoViewIfNeeded(false)
```

It will not only cleaup the codebase but will also save us from future bugs in our implementation

There's an [example implementation](https://github.com/steelbrain/intentions/blob/d6be05721e7259a9df76d405cf0d4a8e09308f49/lib/elements/list.js#L38-L49) of this, please have a look.

**Comment by benogle** [comment]
So this is intentional. It used to use the native call, but there were problems with it scrolling parent nodes. See https://github.com/atom/autocomplete-plus/pull/528 for more info

**Comment by steelbrain** [comment]
Gotcha!
