### ISSUE TITLE
Empty element tags don't need to be self closed in HTML 5

### ISSUE THREAD

**Issue by adambuczynski** [atom/autocomplete-plus#655]
This package auto completes a `<br>` to `<br />`. This is not valid HTML5, as per the spec:

https://developer.mozilla.org/en/docs/Web/HTML/Element/br

> Must have a start tag, and **must not have an end tag**. In XHTML documents, write this element as `<br />`.

I don't think anyone uses XHTML much anymore these days, (or at least there should be a setting or auto-detection of the language), so can this be removed from the list of auto closed tags?

Same applies to any other empty element tags, like `<input>` or `<img>` etc.

**Comment by lee-dohm** [comment]
Does autocomplete-plus do this substitution or some other package like [autocomplete-html](https://github.com/atom/autocomplete-html)?

**Comment by adambuczynski** [comment]
Sorry, I posted this in the wrong repo!

**Comment by lee-dohm** [comment]
It's quite alright. Thanks for following up! :grinning:
