### ISSUE TITLE
tab and enter don't autocomplete the same thing

### ISSUE THREAD

**Issue by radfahrer** [atom/autocomplete-plus#657]
I have my Keymap For Confirming A Suggestion setting set to "tab and enter".  Pressing tab does not choose the first suggestion. Pressing enter will choose the first suggestion. Tab and enter should have the same behavior.

**Comment by vinkla** [comment]
I've the same issue. The tab key doesn't work for autocompletion.

**Comment by aaronmw** [comment]
I wonder if this is similar to #460 ?

**Comment by 50Wliu** [comment]
@radfahrer do you have Emmet installed?  If not, does it work in safe mode (`atom --safe`)?

**Comment by radfahrer** [comment]
Yes I do have Emmet installed. Thanks for pointing that out.

**Comment by 50Wliu** [comment]
Ok, and does uninstalling Emmet fix the problem?

**Comment by lee-dohm** [comment]
@radfahrer We've run into this kind of problem with Emmet quite a bit, so I'm going to assume that is the problem here. Please let us know if that isn't the case and we can continue digging.
