### ISSUE TITLE
Snippets not expanding properly

### ISSUE THREAD

**Issue by tjkohli** [atom/autocomplete-plus#661]
Similar to #583, I am having this issue where the HTML "class" attribute is populated with "$1"$0.
Can you please advise?

![ac-bug](https://cloud.githubusercontent.com/assets/7361247/12764168/38b30114-c9c6-11e5-8c04-7038b4588572.gif)

**Comment by lee-dohm** [comment]
Do you have [Emmet](https://atom.io/packages/emmet) installed like in the linked Issue? If so, it could be causing trouble with the built-in keymaps.

**Comment by tjkohli** [comment]
Nope. I also disabled all my non-core plugins and restarted Atom, and the issue still occurs.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* Which packages do you have installed?

Also, I can't reproduce this using Atom v1.4.3 on Mac OS X 10.11.3.

**Comment by steelbrain** [comment]
We're also seeing this on OSX

![screenshot](https://cloud.githubusercontent.com/assets/4278113/12770844/2d3a624e-c9e1-11e5-8282-9b1d8bb09311.png)

That snippetted item when expanded, acts like a text item

See https://v.usetapes.com/qkQisJcd2z

**Comment by ncammarata** [comment]
It was actually caused by me having the default `snippets` plugin off

**Comment by lee-dohm** [comment]
@ncammarata I'm confused. Is @steelbrain reporting a problem you ran into? Or are you commenting on something else?

**Comment by steelbrain** [comment]
@lee-dohm Yes. I maintain the autocomplete provider he was having troubles with, so I reported the bug here. But he was originally getting that error.

**Comment by lee-dohm** [comment]
@steelbrain Which autocomplete provider is that?

**Comment by lee-dohm** [comment]
Can you give any more information? Is there a bug you can link to? Don't leave me in the dark here @steelbrain :grinning:

**Comment by steelbrain** [comment]
@lee-dohm https://github.com/steelbrain/steel-flint

As @ncammarata reported, this wasn't really a bug. He had accidentally disabled the `snippets` package

**Comment by lee-dohm** [comment]
Ah ok, thanks!

I also can't reproduce the originally described behavior by disabling the snippets package but leaving the autocomplete-snippets package active.

**Comment by tjkohli** [comment]
@lee-dohm Here is what you asked:
I am using:

- Atom 1.4.2 (But I just upgraded to 1.4.3 and the issue still occurs)
- Mac OS X 10.11.3
- Yes, issue still occurs in atom --safe (1.4.3)
- Packages installed:
  - atom-wrap-in-tag
  - autocomplete-plus
  - highlight-selected
  - minimap
  - project manager
  - tag
  - (I tried disabling all of these except autocomplete plus and the issue still occurs)

New information: The SAME issue occurs with `<a href="$1"$0`

**Comment by steelbrain** [comment]
@tjkohli Could you please post your `~/.atom/config.cson` (if you have any private keys or such in your configuration, make sure to remove them before posting)

**Comment by tjkohli** [comment]
@steelbrain Hey! That worked! I did have snippets disabled. Enabling snippets fixed the issue.

This now works properly. Maybe we should add this to the documentation? That enabling 'snippets' is **required**.

Thoughts? Thanks for all your help.

**Comment by steelbrain** [comment]
I am glad you got it working :+1:
