### ISSUE TITLE
Format completion based on jsdoc/ngdoc tags

### ISSUE THREAD

**Issue by mhartington** [atom/autocomplete-plus#662]
Howdy, quick question really about how to format jsdoc info

So currently, with ionic, we're just inlining markdown in our code as part of our doc build process. Unfortunately, this is problematic with your plugin as it outputs everything as one long string 

![screen shot 2016-02-01 at 12 43 29 pm](https://cloud.githubusercontent.com/assets/2835826/12725641/adb63642-c8e1-11e5-94aa-3f524745abcb.png)

Now my question is, if were to format our source code a bit with jsdob/ngdoc tags, would the completion window be able to format this?

**Comment by benogle** [comment]
There's probably a custom autcomplete provider for ionic, no? Can you change the provider to use less of the doc string? Like maybe use a one-line summary via `description` and add a link to the full docs via `descriptionMoreURL`? Check out [the docs](https://github.com/atom/autocomplete-plus/wiki/Provider-API#suggestions).

**Comment by mhartington** [comment]
Actually this is from the [atom-typescript plugin](https://github.com/TypeStrong/atom-typescript/), which utilizes this plugin. I opened a [similar issue](https://github.com/TypeStrong/atom-typescript/issues/828) on their repo, but was pointed here. 

Now looking at their code, they just take the output from Typescripts language service (which includes full inline commented docs) and output it into the description window.

Now what I'm looking for is if there's anything that can be done with At least parse some jsdoc/ngdoc tags and format it a bit.

**Comment by benogle** [comment]
> Now what I'm looking for is if there's anything that can be done with At least parse some jsdoc/ngdoc tags and format it a bit.

I definitely feel like this is the right approach. We could add some css that limits that mass to one line, but then we might be crippling other packages. I'll close this for now as I dont think there is action on our side to be taken.
