### ISSUE TITLE
autocomplete in the search box

### ISSUE THREAD

**Issue by CarloLucibello** [atom/autocomplete-plus#664]
It would be nice to have the option to use autocomplete in the search box. 

Also in combinations with a package like atom-latex-completions one would be able to search for unicode symbols like \alpha (see JunoLab/atom-latex-completions#8)

**Comment by lee-dohm** [comment]
To which search box are you referring?

**Comment by CarloLucibello** [comment]
the standard one that appears hitting `Ctrl+F`

**Comment by benogle** [comment]
Thanks for the info @CarloLucibello. I'm going to close this in favor of https://github.com/atom/find-and-replace/issues/92 and https://github.com/atom/find-and-replace/issues/383
