### ISSUE TITLE
prefix not consumed

### ISSUE THREAD

**Issue by jfrog85** [atom/autocomplete-plus#666]
I'm trying to make a provider but have run into a problem:

I type:
```
$dis
```
my provider returns this suggestion:
```
  {
    displayText:'$display()'
    snippet: 'display("$0",);'
    type: 'function'
  }
```
Executing turns it into this:
```
  $disdisplay("",);
```
What am I missing to get it to consume the prefix?

**Comment by lee-dohm** [comment]
Including the `$` in the snippet name but not in the expansion is possibly what is causing the issue. See:

https://github.com/atom/snippets/issues/151

Also note that the HTML snippets don't start with `<` but just the tag name:

https://github.com/atom/language-html/blob/master/snippets/language-html.cson
