### ISSUE TITLE
Auto complete is being triggered on space 

### ISSUE THREAD

**Issue by dlebedynskyi** [atom/autocomplete-plus#677]
I really hate this but if i trigger space right after this it will insert autocomplete.
![image](https://cloud.githubusercontent.com/assets/1182917/13302803/da4a6e54-db19-11e5-8c10-ad15d20aeb9c.png)

I've tried switching to entrer/tab
![image](https://cloud.githubusercontent.com/assets/1182917/13302821/f40f1060-db19-11e5-8183-c43c01772172.png)

switching default provider or Use Locality Bonus. 

all I want to press space and do not enter any autocomplete.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by dlebedynskyi** [comment]
@lee-dohm  issue was in conflict with omnisharp. 
Disabling autocomplete or omnisharp fixes the problem.  I assume you can close this one. 
if it may help for future. 
- issue happened both on atom stable and beta with omnisharp installed. 
- Emmet is not installed. 
- Win 7 64.

**Comment by lee-dohm** [comment]
Thank you very much for following up @dlebedynskyi :grinning: I'm glad it it fixed for you!
