### ISSUE TITLE
As it can be like webstorm code completion?

### ISSUE THREAD

**Issue by kumiao** [atom/autocomplete-plus#693]
When using webstorm，like this：
`<link rel="stylesheet" href="bootstrap.css">`
Then I can use autocomplete bootstrap class name
but using atom，I must open bootstrap.css
then I can use autocomplete bootstrap class name
how can I  use autocomplete like webstorm ，not  open the css files

**Comment by RodriguesCosta** [comment]
I also wanted to know that, because opening multiple files "css" or "js" to enable autocomplete fills the files bar

**Comment by lee-dohm** [comment]
With the right autocomplete provider, yes, this is possible. Right now, we don't have the bandwidth to create such a provider.
