### ISSUE TITLE
Atom 1.6.0 Autocomplete fails on El Capitan

### ISSUE THREAD

**Issue by t0dd** [atom/autocomplete-plus#695]
I just installed Atom 1.6.0 on my iMac running OSX El Capitan (10.11.3). Autocomplete will pop-up with options as expected, however when I hit the 'tab' or 'enter' keys it does not complete the code, and the autocomplete window goes away with the cursor right where I left it. 

This is a clean install, I have not added any packages or changed any config settings. 

The same problem occurs in safe mode. 

I've only tried this while working in HTML, CSS, and JavaScript.

**Comment by lee-dohm** [comment]
I can't reproduce this using Atom v1.7.1 on Mac OS X 10.11.4. Can you give specific steps to reproduce this problem?

**Comment by mattwiller** [comment]
@lee-dohm I'm also seeing this problem on Atom 1.7.3 on Mac OS C 10.11.4 when working with JS files (I haven't tried others).

I can reproduce by the following steps:

1. Open a new file, save as `autocomplete.js`
2. On the first line, write `var someRandomVariable = 'foo';`
3. On the next line, I start typing `someR`, and the autocomplete dialog appears with `someRandomVariable` as the first entry.
4. I press enter to select `someRandomVariable` and the autocomplete dialog closes, but the name is not autocompleted and the cursor stays where it is, right after `someR`.

**Comment by 50Wliu** [comment]
@mattwiller And can you reproduce your problem in safe mode (`atom --safe`)?

**Comment by mattwiller** [comment]
@50Wliu For me, the problem disappears when I'm in safe mode.

**Comment by 50Wliu** [comment]
Ok.  As @t0dd hasn't commented back yet, I'm going to close this issue until we can get more information.  @matwiller if you're interested in finding out which package is breaking autocomplete you can try installing the [package-cop](https://atom.io/packages/package-cop) package (if you're using Emmet I would try disabling that first).

**Comment by mattwiller** [comment]
Thanks @50Wliu — I upgraded a few packages including Emmet and it now works without using Safe Mode.
