### ISSUE TITLE
Including R

### ISSUE THREAD

**Issue by JLCCI** [atom/autocomplete-plus#697]
Thanks for the amazing package, great boost to productivity.

Any chance you could include auto completion package for R? This can be taken from Emacs-ESS (https://www.emacswiki.org/emacs/ESSAuto-complete) or several other source files in R.

Many thanks!

**Comment by puranjayjain** [comment]
@JLCCI why not make a language support for R ourselves interested?

**Comment by JLCCI** [comment]
Hey @puranjayjain, I am afraid I know very little about programming so I would not be of much help!

I have send some sample methods on how to clean R code so it is included in atom-beautify but autocomplete would be too difficult. 

If you do intend to implement something I would be very eager to test!

**Comment by puranjayjain** [comment]
@JLCCI I don't use r daily so won't be able to take that task alone.
@lee-dohm can you help us regarding the autocomplete package for R? I am referring you since I saw that you are maintaining the language support for r

**Comment by lee-dohm** [comment]
I converted the [language-r package](https://atom.io/packages/language-r) from TextMate but have done very little to maintain it since. I also no longer use R in my day-to-day work, so I'm afraid I will be little help in building an autocomplete provider for the language.

My apologies.

**Comment by lee-dohm** [comment]
Sorry, I forgot to close this when I commented. Since R grammar support isn't included in Atom, it wouldn't make sense to create an official R autocomplete provider.
