### ISSUE TITLE
Autocomplete+ does not make it easy to select what you typed as correct

### ISSUE THREAD

**Issue by fields** [atom/autocomplete-plus#701]
I am frequently frustrated by the corrections that autocomplete+ makes as I type, but it is very useful to have suggestions. It would help a lot to make the default correction be the string that was typed instead of having to press escape or several arrow keys every time to force autocmplete+ to not change it.

This frequently manifests when I'm typing a string that appears as a substring in other strings in the same project. (e.g.: I type 'us-west-1', and autocomplete wants to change it to 'us-west-1a' or 'us-west-1b' but 'us-west-1' is not an option easily selected in the suggestions menu).

I think what I'm asking for is an option to have autocomplete automatically pop up, but not automatically change anything unless I ask it to.

I am using Atom 1.4.3.

**Comment by 50Wliu** [comment]
Hi @fields, can you please upgrade to Atom 1.6.2 and try again?  The autocompletion scoring was changed in between 1.4.3 and 1.6.2 to be more "natural".

**Comment by fields** [comment]
I think this is better. Will work with it for a bit more before I close this.

**Comment by Ben3eeE** [comment]
Looks solved by updating Atom. Closing.
