### ISSUE TITLE
No expansion in Atom 1.7.0

### ISSUE THREAD

**Issue by lmartins** [atom/autocomplete-plus#705]
I first noticed this problem on Atom Beta, which i stopped using precisely for this same problem that apparently has now sneak into the stable release.

What happens is no matter what config I have for the key to trigger the expansion, when I try to expand anything, the Key Binding Resolver shows the correct command but nothing happens in the editor.

This completely breaks the editor for me and worst still is the fact that the Beta Channels still shows the same problem. Not sure how to get out of this situation. Downgrading to Atom 1.6.2 solves it for now. Hoping this can be addressed in the future. 

Thanks.

**Comment by FlorianM1234** [comment]
Same issue on Windows - Atom 1.7.2

**Comment by lee-dohm** [comment]
I can't replicate this using Atom v1.7.3 on Mac OS X 10.11.4. Can you reproduce this Issue in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by FlorianM1234** [comment]
https://github.com/tststs/atom-ternjs/issues/226#issuecomment-215444676 solves this issue

**Comment by damieng** [comment]
Was caused by a third-party plugin.
