### ISSUE TITLE
autocomplete on suffixes?

### ISSUE THREAD

**Issue by dalexj** [atom/autocomplete-plus#713]
the old autocomplete package did this and I still install the old one every time I want to use autocomplete but I think its time I actually check up on this new one. is there a way I can get autocomplete on suffixes, for example, if I have the code:

```javascript
function reallyLongNameThatIHateTyping1() {}
function reallyLongNameThatIHateTyping2() {}
function reallyLongNameThatIHateTyping3() {}
function reallyLongNameThatIHateTyping4() {}
```

I want to be able to autocomplete like this: `reallylong{cursor}3` and hit ctrl-space. this is probably strange for the autocompletion as you type, but can there be a setting for this/etc? I really like this feature and it seems to be keeping me back from all the new features with providers, etc

thanks

**Comment by lee-dohm** [comment]
The autocomplete-plus package has support for providers to look at text both before and after the cursor position. All that's necessary for what you want is a provider to take advantage of it. You can find information here on creating a provider if you're interested in doing it yourself:

https://github.com/atom/autocomplete-plus/wiki/Provider-API

Or you could file issues on specific providers that you expect to support this kind of completion.

I hope that helps!
