### ISSUE TITLE
The autocomplete-plus doesn't work well

### ISSUE THREAD

**Issue by Mascot1** [atom/autocomplete-plus#723]
I write a class in a.css,then if I open the file ,and in a html file I can get a suggestion.But if I close the file and I can't get any suggestion.

**Comment by nickfmc** [comment]
:+1:  Ya same issue basically as this one https://github.com/atom/autocomplete-plus/issues/571 suggest using a more descriptive title to your issues ;)

**Comment by 50Wliu** [comment]
Thanks for pointing out that this was a duplicate @nickfmc!
