### ISSUE TITLE
Layout problems when right label is provided

### ISSUE THREAD

**Issue by patrick-steele-idem** [atom/autocomplete-plus#728]
The right label is styled using `float: right` and this is causing space to not be reserved correctly. As a result, the suggestion list renders with layout problems:

![right-label-bad-layout](https://cloud.githubusercontent.com/assets/978214/15902771/e4d8d186-2d66-11e6-9046-1fff3d7de9e5.png)

I am testing a fix locally and will be submitting a PR.

**Comment by designorant** [comment]
Can you explain how did you get this popover? I'd like to reproduce this.

**Comment by patrick-steele-idem** [comment]
@designorant On my machine, he key thing to reproduce the problem is have a provider that returns a suggestion with a a lot of text and a right label. It might be me a little more trouble, but you can install the following plugin to reproduce the problem: https://github.com/marko-js/atom-autocomplete-marko

You would then need to create a `.marko` file or switch a text editor to the `Marko` grammar and type:

`div for` and that should result in an autocomplete overlay with the layout problem.

Please let me know if you need more details.
