### ISSUE TITLE
Suggestions for atribute 'type' in input 

### ISSUE THREAD

**Issue by lukalazov** [atom/autocomplete-plus#731]
When I type input I get this:
`<input type="button" name="name" value="">`
I think it would be helpful if someone typed inside the type <input> attribute and got this suggestions: 
-  button
- checkbox
- color
- date
- datetime
- datetime-local
- email
- file
- hidden
- image
- month
- number
- password
- radio
- range
- reset
- search
- submit
- tel
- text
- time
- url
- week

**Comment by 50Wliu** [comment]
@lukalazov Can you please reopen this issue on [atom/autocomplete-html](https://github.com/atom/autocomplete-html)?  Thanks!

**Comment by lukalazov** [comment]
No problem at all, didn't know I was at a wrong place.
