### ISSUE TITLE
Suggestion list hidden behind line number

### ISSUE THREAD

**Issue by BigfootN** [atom/autocomplete-plus#736]
Hello,

When splitting the screen, with autocomplete-plus enabled, I am having some problem concerning the autocomplete suggestion list. It is hidden behind the line number of the second split. Here is a screenshot:

![2016-06-04-135530_206x97_scrot](https://cdn-business.discourse.org/uploads/github_atom/original/3X/7/2/72ddf45caa189fe511546fff8997c93b9d321f8e.png)

Details:

theme used: atom material
OS: Archlinux x86_64

atom version:

Atom     : 1.9.0-beta0
Electron: 0.37.8
Chrome: 49.0.2623.75
Node    : 5.10.0

package used: [atom-editor-beta-bin](https://aur.archlinux.org/packages/atom-editor-beta-bin/)

Thank you very much for any answer :)

**Comment by lee-dohm** [comment]
Can you reproduce this in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by BigfootN** [comment]
Hello,

So, by launching `atom --safe`, after exiting all instances of atom, I wasn't able to choose the "atom material" ui theme, only "atom dark/light" or "one light/dark". When using either of those themes I was unable to reproduce this problem (both with `atom`  and `atom --safe`).

It really seems to come from this theme in particular. I've filled out an [issue](https://github.com/atom-material/atom-material-ui/issues/297) on the repository of the [theme](https://github.com/atom-material/atom-material-ui).

Thank you very much again :)

**Comment by 50Wliu** [comment]
Thanks for reporting back @BigfootN!
