### ISSUE TITLE
Pop-up does not hide when hit ESCAPE

### ISSUE THREAD

**Issue by cristian-sima** [atom/autocomplete-plus#745]
The bindings for `ESCAPE`

![image](https://cloud.githubusercontent.com/assets/12199042/17407160/f8198800-5a6e-11e6-81b7-2ae762621c4a.png)

Did I do something wrong?

The only way to hide/close the list is to click within the file

**Comment by damieng** [comment]
You don't seem to have it bound to autocomplete-plus as well (which is the default). It should look like this;

![image](https://cloud.githubusercontent.com/assets/118951/17820193/678dd26c-6600-11e6-9c25-4326744fd659.png)
