### ISSUE TITLE
cannot resolve popen?

### ISSUE THREAD

**Issue by pangqingyuan1991** [atom/autocomplete-plus#746]
I am a newer. And just install this plugin.
when I type fopen, it shows function declaration.
But popen not. 
Both fopen and popen are declared in stdio.h 
How does the plugin look for function declaration?

**Comment by lee-dohm** [comment]
The autocomplete-plus package doesn't do much of anything without providers. It doesn't know anything about C or your headers, it only suggests things that you've already typed in the currently open file.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions like this one, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
