### ISSUE TITLE
PHP Autocomplete bug - false is not a argument

### ISSUE THREAD

**Issue by jamiel-sharief** [atom/autocomplete-plus#747]
Autocomplete is showing:
**($type,$conditions,$callbacks,$false)**
for the following function 
**function find($type, $conditions = [], $callbacks = false)**

Here is the PHP script:
# autocomplete-test.php 
<?php

error_reporting(E_ALL);
ini_set('display_errors', 'On'); // For help of development

class Controller
{
    public function __construct()
    {
        $this->startup();
    }
}
class Model
{
    /**
   * Find records.
   *
   * @param  string $type       first,all
   * @param  array  $conditions fields with conditions
   * @param  bool $callbacks  callbacks
   *
   * @return array             results
   */
  public function find($type, $conditions = [], $callbacks = false)
  {
      return ['User' => ['id' => '10000', 'country' => 'UK']];
  }
}

class User extends Model
{
    public $name = 'User';
}
class UsersController extends Controller
{
    public $User = null;  // User model

  public function startup()
  {
      $this->User = new User();
  }
    public function index()
    {
        $results = $this->User->find('first', ['conditions' => ['id = 10000']]);
        var_dump($results);

    # # # AUTOCOMPLETE TEST # # #
    // Type: $this->User->find
    // displays $type, $conditions, $callbacks, $false - false is  not a argument
    }
}

$Controller = new UsersController();
$Controller->index();

**Comment by damieng** [comment]
autocomplete-plus has no direct knowledge of PHP - I suspect this is an issue with one of the PHP providers such as https://github.com/Peekmo/atom-autocomplete-php or https://atom.io/packages/autocomplete-php depending on what you are using.
