### ISSUE TITLE
Autocomplete doesn’t work when I split (not always and only in one side)

### ISSUE THREAD

**Issue by n3ph7hy5** [atom/autocomplete-plus#752]
![anim](https://cloud.githubusercontent.com/assets/12140196/17848767/9801da86-6855-11e6-8d36-dcc087270222.gif)
Hello,
I'm in ubuntu 16.04, I just updated from the repo to version 1.9.8 of atom and now when I do: "open folder then split right" (same file to the left and right) the completion works only on the left but not on the right.
If I open directly a file and split it works fine in both sides (but not always).
What I did:
-atom --safe,
-deleted "~/.atom",
-atom --clear-window-state.
Same results
I completely removed from synaptic and then install it again but nothing changed
I updated to 1.9.9, repeated again but no changes.
$ atom --version
Atom : 1.9.9
Electron: 0.37.8
Chrome : 49.0.2623.75
Node : 5.10.0
$ apm --version
apm 1.10.0
npm 2.13.3
node 0.10.40
python 2.7.12
git 2.7.4

**Comment by maxbrunsfeld** [comment]
Thanks for reporting this @n3ph7hy5. I'm really sorry for this broken experience. This has been fixed via https://github.com/atom/atom/pull/12125. The fix will be released in Atom v1.11.
