### ISSUE TITLE
No suggestions

### ISSUE THREAD

**Issue by SystemInfected** [atom/autocomplete-plus#754]
All of a sudden no suggestions show up.

I haven't installed any new packages or anything like that.
The setup is just like before when it was working.

**Comment by stxml** [comment]
Does it suggest to insert "PANIC" only? That's what happened to me.

**Comment by SystemInfected** [comment]
Not for me, I get no suggestions at all.

I have tried to disable all community packages but nothing changed.

**Comment by stxml** [comment]
First step should be to make sure the gocode daemon is called correctly
- quit atom and quit the daemon if it's running with 'gocode close'
- open a go file in atom and type something like a variable name that could be completed
- gocode should be the top process running

**Comment by SystemInfected** [comment]
Oh sorry I should have pointed out; for me it is PHP, Javascript and CSS.
Thanks anyway!

**Comment by stxml** [comment]
Ah man. I thought I was in autocomplete-go the whole time.

**Comment by 50Wliu** [comment]
@SystemInfected Can you reproduce this issue in safe mode (`atom --safe`)?  In addition, what Atom version and OS are you using?

**Comment by xgdgsc** [comment]
I can reproduce this in safe mode on archlinux atom 1.12.2

**Comment by 50Wliu** [comment]
Ok, can everyone affected by this issue also paste the output of `atom --version` here?

**Comment by SystemInfected** [comment]
For me it's solved by itself but I'm not sure what solved it. The autocomplete just worked one day.

**Comment by 50Wliu** [comment]
Thanks for following up @SystemInfected!  Everyone else who is experiencing this, please create a new issue.  Thanks!
