### ISSUE TITLE
Autocomplete plus not working at all anymore

### ISSUE THREAD

**Issue by blimmer** [atom/autocomplete-plus#755]
Suddenly happened to me today - ctrl + space and opening through the preference panes do nothing.

**Comment by leorossi** [comment]
I have a simliar issue as of today. No more autocomplete window while I'm typing. 
I didn't change anything in the settings, I guess I may have mis-typed some keyboard shortcut to enable or disable something, but I can't revert...

**Comment by 50Wliu** [comment]
@blimmer @leorossi Can you reproduce this in safe mode (`atom --safe`)?  In addition, what Atom version and OS are you using?

**Comment by blimmer** [comment]
It's suddenly started working again after restarting my machine. On latest atom (1.9.9) and Mac OS X latest. I'll close since I can't repro at the moment.

**Comment by leorossi** [comment]
@50Wliu sorry probably my comment wasn't complete enough but I was trying to understand why it didn't work.
As @blimmer it started working again suddenly. I will pay more attention next time if it happens ;)

**Comment by sudhirbitsgoa** [comment]
atom version 1.9.8 on ubuntu facing same issue even launched in safe mode.
