### ISSUE TITLE
constant error messages

### ISSUE THREAD

**Issue by matthewmaier** [atom/autocomplete-plus#756]
It's constantly throwing out error messages while I type

For example, I typed "the" and when I got to "e" a window popped up with "uncaught error type: cannot read property 'toLowerCase' of undefined.

That keeps appearing as I continue to type.

**Comment by 50Wliu** [comment]
@matthewmaier Is this reproducible in safe mode (`atom --safe`)?  In addition, what Atom version and OS are you using?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/autocomplete-plus/issues/756#issuecomment-242930242. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
