### ISSUE TITLE
Autocomplete breaks when split

### ISSUE THREAD

**Issue by kartagis** [atom/autocomplete-plus#758]
Hello,
I sometimes need to open the same file in two panes, so I split. Then I realised that after I close the page, autocomplete is not working anymore. My Atom version is 1.9.7 and this is on OS X 10.11.4.

**Comment by Ben3eeE** [comment]
https://github.com/atom/autocomplete-plus/issues/752

**Comment by kartagis** [comment]
Aye, I just subscribed to that. Should I close this?

**Comment by Ben3eeE** [comment]
Yeah, there is no reason in having multiple issues open for the same thing. There is also a PR you can subscribe to which patches Atom 1.10 https://github.com/atom/atom/pull/12522.

**Comment by kartagis** [comment]
Closing. Thanks
