### ISSUE TITLE
BUG: Broken after "split down"

### ISSUE THREAD

**Issue by Olian04** [atom/autocomplete-plus#761]
The autocomplete stopped working after i split the view in 2 using the "split down" option, and then resized the lower window (the one with the css), (i made it smaller, about 20% of the screen height).
It still works in the ordinary window (the upper one), but it wont trigger at all (even with ctrl-space) in the lower window.

![screenshot from 2016-08-28 13-36-31](https://cloud.githubusercontent.com/assets/5493406/18033436/806b0482-6d24-11e6-852c-3beb4beaec2c.png)

__NOTE:__ 
I realize this might not be a bug since the autocomplete menu wouldn't relay fit in the small window. Although i would still like it to work, maybe just make the menu scale with the size of the window? 

__Another bug?__
I just realized something, if i have the same css open in both windows, when i target the lower window and start typing, the menu shows up in the upper one.

**Comment by 50Wliu** [comment]
Answered in your autocomplete-css issue.
