### ISSUE TITLE
\ in snippets not displayed correctly in ac list

### ISSUE THREAD

**Issue by steelbrain** [atom/autocomplete-plus#773]
When using the `snippet` attribute on an autocomplete suggestion, it treats `\` as the escape character. To show the `\` character in the suggestions, we have to escape it as `\\`.

The bug in autocomplete-plus about this is that it shows `\\` in suggestion list, and inserts `\`. It was worked around in one of my packages in https://github.com/steelbrain/autocomplete-hack/pull/22/commits/1a71c16df543b524d763d727d3c1f970861ffa26.

The expected behavior for it would be to show `\` in both the list and inserted text.

To repro this bug set `snippet: 'Some \\ Where \\ Sunny'` on an autocomplete suggestion, then observe the visible text and mutation to the editor text after you select it.
Would you be willing to review a PR fixing this? I have a locally working fix that I would love to upstream.

**Comment by 50Wliu** [comment]
Fixing it seems reasonable to me.

**Comment by steelbrain** [comment]
I've opened up #774 to fix this
