### ISSUE TITLE
Changing one part changes all parts

### ISSUE THREAD

**Issue by kartagis** [atom/autocomplete-plus#783]
Hello
When we write php and we want a for loop, for+Enter is autocompleted to a for loop, which is nice. However, when we attempt to change one part of the loop, all 3 parts are changed. Allow me to demonstrate in a gif below. Correct me if I'm wrong, but this is not how a for loop works, right?

![atom](https://cloud.githubusercontent.com/assets/1607518/19383405/c2a4f6f2-920c-11e6-852d-2890628eb905.gif)

**Comment by 50Wliu** [comment]
Press `Esc` after changing the initial variable. In addition, autocomplete-plus has nothing to do with this - it should belong either on snippets or language-php instead.
