### ISSUE TITLE
Choose sorting of autocomplete?

### ISSUE THREAD

**Issue by kentcdodds** [atom/autocomplete-plus#785]
Here's a gif of what's happening:

![fun](https://cloud.githubusercontent.com/assets/1500684/19396231/4f45e75a-91ff-11e6-8560-23ba091b9c34.gif)

Basically, there are other autocomplete options that take precedence over my snippets. I'd like to control the sorting of that list somehow. I'll almost always prefer snippets on top. Is there any way I can get this behavior to change. I have the same problem with `cl` autocompleting to `class` when I want to use my `console.log` snippet.

Here's my plugins:

```
~
🍰  $ apm list
Built-in Atom Packages (89)
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.44.0
├── base16-tomorrow-dark-theme@1.2.0
├── base16-tomorrow-light-theme@1.2.0
├── one-dark-ui@1.6.0
├── one-light-ui@1.6.0
├── one-dark-syntax@1.3.0
├── one-light-syntax@1.3.0
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── about@1.7.0
├── archive-view@0.61.1
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.2
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.1
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── bookmarks@0.42.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.201.1
├── fuzzy-finder@1.4.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.2
├── image-view@0.59.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@1.0.0
├── notifications@0.65.1
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.242.2
├── snippets@1.0.2
├── spell-check@0.68.2
├── status-bar@1.4.1
├── styleguide@0.47.0
├── symbols-view@0.113.1
├── tabs@0.101.0
├── timecop@0.33.2
├── tree-view@0.209.3
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.33.0
├── wrap-guide@0.38.2
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.2
├── language-csharp@0.12.1
├── language-css@0.37.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.42.1
├── language-html@0.45.1
├── language-hyperlink@0.16.0
├── language-java@0.23.0
├── language-javascript@0.119.0
├── language-json@0.18.2
├── language-less@0.29.5
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.2
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.69.0
├── language-ruby-on-rails@0.25.0
├── language-sass@0.56.0
├── language-shellscript@0.22.4
├── language-source@0.9.0
├── language-sql@0.23.0
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.9
└── language-yaml@0.26.0

Community Packages (22) /Users/kdodds/.atom/packages
├── atom-ternjs@0.15.0
├── autocomplete-emojis@2.5.0
├── autocomplete-json@5.1.0
├── autocomplete-modules@1.6.7
├── custom-invisibles@0.1.2
├── docblockr@0.8.7
├── editorconfig@1.4.1
├── expand-region@0.2.5
├── file-icons@1.7.21
├── highlight-selected@0.11.2
├── hyperclick@0.0.39
├── js-hyperclick@1.8.1
├── language-babel@2.44.1
├── language-json5@1.1.0
├── linter@1.11.18
├── linter-eslint@8.0.0
├── linter-flow@5.5.0
├── local-history@3.4.1
├── open-this@0.2.0
├── relative-numbers@0.5.1
├── terminal-plus@0.14.5
└── vim-mode-plus@0.60.0

└── (empty)
```

Any tips are appreciated!

**Comment by rm-code** [comment]
I am experiencing the same "problem" with a custom provider I wrote.  Would love to know if there is a way to fix it.

**Comment by ambethia** [comment]
That gif is the story of my life.

**Comment by t9md** [comment]
@kentcdodds

Not sure if you are already happy with `Display above snippets` in ternjs package settings.
If not, and what you want is just always-show-your-custom-snippet-first, then how about following hack?

## edit your init.coffee and restart atom.

1. `Open Your Init Script` from command-palette.
2. Your `init.coffee` would be opened.
3. paste following code then restart atom.

```coffeescript
consumeService = (packageName, providerName, fn) ->
  disposable = atom.packages.onDidActivatePackage (pack) ->
    if pack.name is packageName
      service = pack.mainModule[providerName]()
      fn(service)
      disposable.dispose()

consumeService 'autocomplete-snippets', 'provide', (provider) ->
  # You can try with bigger number if it won't solve your problem
  provider.constructor::suggestionPriority = 3
```

**Comment by kentcdodds** [comment]
Oh snap. I had no idea this was even an option.

<img width="441" alt="screen shot 2016-11-06 at 7 00 39 pm" src="https://cloud.githubusercontent.com/assets/1500684/20044120/57f9782e-a453-11e6-9e47-9a090b480c45.png">

I just got half of my life back. Thank you! Looks like I'll be sticking with Atom after all (spent a week with Code and just couldn't quite do it). Thanks so much!

**Comment by bhishanpdl** [comment]
I am also getting the same problem. I have lots of python snippets in ~/.Atom/snippets.cson file.
For example, list comprehension shortcut is "lc".

However, when I type "lc", I see other options:  
 "local" 
 "licence"   
 "lc" . 


I want to make my custom command "lc" the first option.
My snippets are in snippets  ~/.Atom/snippets.cson the first choice.


**Attempts**:  
Attempt1. 
========
I tried using atom-ternjs and select Display above snippets as ON.

Attempt2:  
=======
I also tried above code to put in the ~/.Atom/init.coffee

```
[consumeService = (packageName, providerName, fn) ->
  disposable = atom.packages.onDidActivatePackage (pack) ->
    if pack.name is packageName
      service = pack.mainModule[providerName]()
      fn(service)
      disposable.dispose()

consumeService 'autocomplete-snippets', 'provide', (provider) ->
  # You can try with bigger number if it won't solve your problem
  provider.constructor::suggestionPriority = 3](url)
```

I am not sure to do I have to change **packageName, providerName, fn** but naively using above code and restarting atom did not work.

This is the reason I am forced to Disable/Uninstall autocomplete-plus.

Is there any hack Any great person on Earth who has successfully get away with this problem?

The answer will be greatly appreciated!!!!
