### ISSUE TITLE
Double @ issue

### ISSUE THREAD

**Issue by tillkruss** [atom/autocomplete-plus#788]
Whenever I type `@` and hit `tab` to autocomplete, I get a two at-symbol. Is that an issue with this package?

```sass
@@include ;
```

![screen shot 2016-10-19 at 10 14 57 am](https://cloud.githubusercontent.com/assets/665029/19529509/094e6f80-95e5-11e6-8859-809a114ce2c0.png)

![screen shot 2016-10-19 at 10 15 04 am](https://cloud.githubusercontent.com/assets/665029/19529508/094c7720-95e5-11e6-9c1d-82866c4ad3fc.png)

**Comment by 50Wliu** [comment]
This is intentional: you are trying to autocomplete a snippet, which is different than regular autocompletion.  Snippets are meant to produce chunks of code for you that you can immediately start filling in.  In this case, the `include` snippet already provides the leading `@` for you.
