### ISSUE TITLE
Attributes Being Entered With Characters Added

### ISSUE THREAD

**Issue by conbracoweb** [atom/autocomplete-plus#798]
When using the Autocomplete function for an HTML page, the attributes are entered with characters added. An example would be **class="$1"$0** 

![2016-11-23_10-16-07](https://cloud.githubusercontent.com/assets/21178698/20567319/3b5b61c6-b166-11e6-9a9b-a36c91060ff8.png)

**Comment by 50Wliu** [comment]
Make sure you have the `snippets` package enabled.
