### ISSUE TITLE
php being spawned

### ISSUE THREAD

**Issue by Mubiranking4x** [atom/autocomplete-plus#801]
events.js:160 Uncaught Error: spawn php ENOENT
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)
events.js:160 Uncaught Error: spawn php ENOENT
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)
events.js:160 Uncaught Error: spawn php ENOENT
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)
events.js:160 Uncaught Error: spawn php ENOENT
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)exports._errnoException @ util.js:1026Socket._writeGeneric @ net.js:706Socket._write @ net.js:725doWrite @ _stream_writable.js:307writeOrBuffer @ _stream_writable.js:293Writable.write @ _stream_writable.js:220Socket.write @ net.js:651execute @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:48(anonymous function) @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:84getSuggestions @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:71(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:325module.exports.AutocompleteManager.getSuggestionsFromProviders @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:304(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3module.exports.AutocompleteManager.findSuggestions @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:291(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3
events.js:160 Uncaught Error: spawn php ENOENTexports._errnoException @ util.js:1026ChildProcess._handle.onexit @ internal/child_process.js:193onErrorNT @ internal/child_process.js:359_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)exports._errnoException @ util.js:1026Socket._writeGeneric @ net.js:706Socket._write @ net.js:725doWrite @ _stream_writable.js:307writeOrBuffer @ _stream_writable.js:293Writable.write @ _stream_writable.js:220Socket.write @ net.js:651execute @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:48(anonymous function) @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:84getSuggestions @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:71(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:325module.exports.AutocompleteManager.getSuggestionsFromProviders @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:304(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3module.exports.AutocompleteManager.findSuggestions @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:291(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3
events.js:160 Uncaught Error: spawn php ENOENTexports._errnoException @ util.js:1026ChildProcess._handle.onexit @ internal/child_process.js:193onErrorNT @ internal/child_process.js:359_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)exports._errnoException @ util.js:1026Socket._writeGeneric @ net.js:706Socket._write @ net.js:725doWrite @ _stream_writable.js:307writeOrBuffer @ _stream_writable.js:293Writable.write @ _stream_writable.js:220Socket.write @ net.js:651execute @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:48(anonymous function) @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:84getSuggestions @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:71(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:325module.exports.AutocompleteManager.getSuggestionsFromProviders @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:304(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3module.exports.AutocompleteManager.findSuggestions @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:291(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3
events.js:160 Uncaught Error: spawn php ENOENTexports._errnoException @ util.js:1026ChildProcess._handle.onexit @ internal/child_process.js:193onErrorNT @ internal/child_process.js:359_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)exports._errnoException @ util.js:1026Socket._writeGeneric @ net.js:706Socket._write @ net.js:725doWrite @ _stream_writable.js:307writeOrBuffer @ _stream_writable.js:293Writable.write @ _stream_writable.js:220Socket.write @ net.js:651execute @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:48(anonymous function) @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:84getSuggestions @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:71(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:325module.exports.AutocompleteManager.getSuggestionsFromProviders @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:304(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3module.exports.AutocompleteManager.findSuggestions @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:291(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3
events.js:160 Uncaught Error: spawn php ENOENTexports._errnoException @ util.js:1026ChildProcess._handle.onexit @ internal/child_process.js:193onErrorNT @ internal/child_process.js:359_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)exports._errnoException @ util.js:1026Socket._writeGeneric @ net.js:706Socket._write @ net.js:725doWrite @ _stream_writable.js:307writeOrBuffer @ _stream_writable.js:293Writable.write @ _stream_writable.js:220Socket.write @ net.js:651execute @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:48(anonymous function) @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:84getSuggestions @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:71(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:325module.exports.AutocompleteManager.getSuggestionsFromProviders @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:304(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3module.exports.AutocompleteManager.findSuggestions @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:291(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3
events.js:160 Uncaught Error: spawn php ENOENTexports._errnoException @ util.js:1026ChildProcess._handle.onexit @ internal/child_process.js:193onErrorNT @ internal/child_process.js:359_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)exports._errnoException @ util.js:1026Socket._writeGeneric @ net.js:706Socket._write @ net.js:725doWrite @ _stream_writable.js:307writeOrBuffer @ _stream_writable.js:293Writable.write @ _stream_writable.js:220Socket.write @ net.js:651execute @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:48(anonymous function) @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:84getSuggestions @ C:\Users\Idris Mubarak\.atom\packages\autocomplete-php\lib\provider.coffee:71(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:325module.exports.AutocompleteManager.getSuggestionsFromProviders @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:304(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3module.exports.AutocompleteManager.findSuggestions @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:291(anonymous function) @ C:\Users\Idris Mubarak\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3
events.js:160 Uncaught Error: spawn php ENOENTexports._errnoException @ util.js:1026ChildProcess._handle.onexit @ internal/child_process.js:193onErrorNT @ internal/child_process.js:359_combinedTickCallback @ internal/process/next_tick.js:74_tickCallback @ internal/process/next_tick.js:98
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)
events.js:160 Uncaught Error: spawn php ENOENT
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)
events.js:160 Uncaught Error: spawn php ENOENT
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)
events.js:160 Uncaught Error: spawn php ENOENT
util.js:1026 Uncaught (in promise) Error: write EPIPE(…)
events.js:160 Uncaught Error: spawn php ENOENT

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [autocomplete-php](https://atom.io/packages/autocomplete-php) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
