### ISSUE TITLE
Quickly accepting suggestion causes it to not be inserted

### ISSUE THREAD

**Issue by nmote** [atom/autocomplete-plus#803]
I've conducted this test with a stock Atom install with no plugins enabled. My autocomplete-plus settings are all default.

If you have a list of autocomplete results and you in very quick succession type a letter to filter them and then press enter, the autocomplete box closes and nothing is inserted. The suggestion isn't inserted, nor is a newline character.

Here is a more concrete example. Let's say I have a file with the following text:

```
someToken
so|
```
(where `|` is the location of the cursor).

I type `m` and get an autocomplete box with the one suggestion `someToken`. Then I press `e` and immediately press Enter (nearly at the same time). This causes the undesirable effects explained above.

I can figure out how to post a video if this explanation isn't adequate, but GitHub doesn't seem to like mov files.

@nathansobo suggested adding a 100 ms grace period, so if results appear within 100 ms of the user pressing enter, the top suggestion is confirmed. Of course, if autocomplete providers are really slow this wouldn't help, but in that case it's hard to create a good user experience anyway.

CC @iolsen.

**Comment by nathansobo** [comment]
Seems worth cc'ing the primary package contacts on this one as well, @as-cii and @joefitzgerald. Just making you aware of this in case you weren't... we can schedule reactive work on this if needed.

**Comment by rsese** [comment]
Going through some older issues, I was unable to reproduce on macOS 10.12.6 and 1.34.0-nightly0 - can you still reproduce @nmote?
