### ISSUE TITLE
autocomplete sass don't work

### ISSUE THREAD

**Issue by farnetani** [atom/autocomplete-plus#819]
I try to install autocomplete sass, but don't install.

The link is break!

**Comment by farnetani** [comment]
Unable to download https://www.atom.io/api/packages/autocomplete-sass/versions/0.1.0/tarball: 400 Bad Request Repository inaccessible

**Comment by 50Wliu** [comment]
The built-in autocomplete-css package includes Sass and SCSS support.  I'll see what we can do about removing autocomplete-sass.
