### ISSUE TITLE
Colon & Key/Value Pair suggestion is blocking

### ISSUE THREAD

**Issue by alteredtastes** [atom/autocomplete-plus#821]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

See attached image. This issue came after my update two days ago.

### Steps to Reproduce

See attached image. Suggestion on colon enforces use of same line in switch case - `enter` does not autocomplete anything. `enter` appends "key" into key name if used while creating an object.

**Expected behavior:** [What you expect to happen]

Hard to tell the real benefit of this suggestion even in key/value pair context. Atom can't infer the data type/syntax for the value and "key" is automatically appended on the user's chosen key name. `enter` does not autocomplete anything when it suggests on a colon in a switch case. `spacebar` does not collapse/ignore suggestion. 

**Actual behavior:** [What actually happens]

when colon is placed, `enter` and `spacebar` do not allow new line or collapsing/ignore of the suggestion. see screenshot below for context.

`enter` won't make new line, `space` does not remove suggestion.
<img width="422" alt="screen shot 2017-02-15 at 11 00 14 pm" src="https://cloud.githubusercontent.com/assets/14845097/23011023/5b10f26a-f3d3-11e6-847a-4c23509368cf.png">
suggestion triggers on `:`
<img width="202" alt="screen shot 2017-02-15 at 11 27 08 pm" src="https://cloud.githubusercontent.com/assets/14845097/23011524/5624c3fa-f3d6-11e6-88d7-ad4dc01b24e9.png">
then `enter` will automatically append "key" to the key name.
<img width="150" alt="screen shot 2017-02-15 at 11 27 17 pm" src="https://cloud.githubusercontent.com/assets/14845097/23011525/5a19dc02-f3d6-11e6-9edd-b539c4a6394a.png">

**Reproduces how often:** [What percentage of the time does it reproduce?]

always

### Versions

Atom    : 1.14.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.10.2

osx el capitan 10.11.6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
You can disable the autocomplete-snippets package to get around this issue.  If you would rather that the snippet be changed, please file an issue on whatever language package you're using to highlight that file.
