### ISSUE TITLE
Autocomplete does not work for markdown file.

### ISSUE THREAD

**Issue by Josca** [atom/autocomplete-plus#824]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Autocomplete for markdown files does not work. How to enable autocomplete for ALL files? I replaced 'File Blacklist' filed with value '*.ttt' to disable default value [*.md, *.txt]. When I rename my .md file with .py extension, autocomplete works.

### Steps to Reproduce

1. Modify autocomplete-plus settings: File Blacklist: *.ttt.
2. Create test.md.
3. Write string 'hello' to the first line.
4. Try to write 'hel' to the second line - autocomplete does not work.
5. Rename file to test.py
6. Try to write 'hel' to the second line - autocomplete works.

**Expected behavior:** Autocomplete for markdown file.

**Actual behavior:** No autocomplete for markdown file.

**Reproduces how often:** 100%

### Versions

Atom    : 1.14.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Ubuntu: 16.04

### Additional Information

How to disable default 'File Blacklist' value without putting dummy '*.ttt' extension?

**Comment by 50Wliu** [comment]
I noticed that you did not check the prerequisites.  Can you reproduce this in safe mode (`atom --safe`)?

**Comment by Josca** [comment]
Oh, sorry. Yes in safe mode - the same problem.

**Comment by 50Wliu** [comment]
Ok, thanks.  This is odd, because [the default](https://github.com/atom/autocomplete-plus/blob/e834b0a90e85a619e73efb17ac253a11c4da551f/package.json#L87) for the file blacklist is currently dotfiles only.  Can you please share your `config.cson` here?

**Comment by Josca** [comment]
No problem.
[config.cson.txt](https://github.com/atom/autocomplete-plus/files/784137/config.cson.txt)

**Comment by avonmoll** [comment]
Same problem here.

# Versions
Atom v1.14.4
npm 3.10.5
Windows 7

# Config
Same as @Josca

# Notes
- [x] Reproduced in safe mode

**Comment by ungb** [comment]
Thanks for reporting.  I can repro the issue with repro steps above.  

Instead of renaming the file you can also just change the file grammar (hotkey: `ctrl+shift+L`) to something other than markdown.  When you change it back to markdown it still seems to work.   

My default for blacklist is `.*` which would only match files like `.gitignore` or any files that start with a .  

![image](https://cloud.githubusercontent.com/assets/5624870/23569956/f270df54-0016-11e7-8564-bf39c74594ec.png)

**Comment by rsese** [comment]
Just checking on some older issues - I can no longer reproduce on macOS 10.12.6 with Atom 1.32.0, can you still reproduce @Josca?
