### ISSUE TITLE
Dock border is on top of autocompletion

### ISSUE THREAD

**Issue by 50Wliu** [atom/autocomplete-plus#834]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Dock borders appear on top of the autocompletion box:
![dock-over-autocomplete](https://cloud.githubusercontent.com/assets/2766036/24584053/a748ac5e-172d-11e7-991d-a5546d15befa.png)

### Steps to Reproduce

1. Type near the bottom of the screen, close to where the bottom dock is
2. Trigger autocompletion

**Expected behavior:** The autocompletion box to appear over the dock border

**Actual behavior:** The dock border appears over the autocompletion box

**Reproduces how often:** 100%

### Versions
```
Atom    : 1.17.0-dev-11915bfdc
Electron: 1.6.5
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.12.0.windows.1
visual studio 2015
```
Windows 10 x64

/cc @matthewwithanm

**Comment by nathansobo** [comment]
I'm having trouble reproducing this on master.

**Comment by 50Wliu** [comment]
Hmm.  I can still reproduce on 1.17.0-dev-d008ccfd7, which is latest master + Electron branch.

**Comment by Ben3eeE** [comment]
Trying to reproduce in the atom master repo with the CONTRIBUTING document open;

![docks typing 2](https://cloud.githubusercontent.com/assets/1058982/24729273/b1ca9830-1a5d-11e7-82f4-287cc9905a94.gif)

**Comment by nathansobo** [comment]
Okay, I just reproduced it accidentally. Weird that I couldn't when I tried previously. Looks like setting the z-index of overlays to 11 or greater fixes the issue. @simurai could you help us sort out the zIndex issues here?

**Comment by simurai** [comment]
![image](https://cloud.githubusercontent.com/assets/378023/24738563/674f950c-1ad1-11e7-96fa-aa3faabec65f.png)

☝️  seems there is another ghost bot 👻 🤖 .

Anyways.. yeah, the docks use a `z-index` of `10` + `11`. So in #835 it got raised to `12` for autocomplete.
