### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by snowwolf007cn** [atom/autocomplete-plus#837]
You have the core package "autocomplete-plus" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (/Users/zhangzhi/Downloads/DevTools/Atom.app/Contents/Resources/app.asar/node_modules/dalek/lib/main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (/Users/zhangzhi/Downloads/DevTools/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/Users/zhangzhi/Downloads/DevTools/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/Users/zhangzhi/Downloads/DevTools/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:32)
```

**Comment by Ben3eeE** [comment]
You have the core package "autocomplete-plus" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.

**Comment by jerome-diver** [comment]
You have the core package "autocomplete-plus" installed as a community package. See https://github.com/atom/atom/blob/master/packages/dalek/README.md for how this causes problems and instructions on how to correct the situation.

<unknown> - /usr/lib/atom/node_modules/dalek/lib/main.js:14:14
Generator.next - null:null:null
step - /usr/lib/atom/node_modules/dalek/lib/main.js:1:428
run - /home/jerome/.atom/packages/git-plus/node_modules/core-js/modules/es6.promise.js:75:22
<unknown> - /home/jerome/.atom/packages/git-plus/node_modules/core-js/modules/es6.promise.js:92:30
flush - /home/jerome/.atom/packages/git-plus/node_modules/core-js/modules/_microtask.js:18:9

stlll bugged on version 1.35.1-1 (installed on archlinux), please, do not close as long as long as this deprecated error exist

**Comment by Arcanemagus** [comment]
Please read the previous comment and the error you posted.

[I got a warning, what do I do?](https://github.com/atom/atom/tree/master/packages/dalek#i-got-a-warning-what-do-i-do)
