### ISSUE TITLE
How do I make autocomplete-plus stop inserting "print(${1:value}, ${2:...})" into all of my function autocompletions"

### ISSUE THREAD

**Issue by jolaroux** [atom/autocomplete-plus#844]
When confirming a function autocompletion it inserts this:
http://imgur.com/a/tRmkB

How do I make this stop?

This is python, with nothing but autocomplete-plus and nuclide installed. however it does it in other languages too.

**Comment by 50Wliu** [comment]
Make sure you have the `snippets` package enabled.
