### ISSUE TITLE
Autocomplete fails for latex

### ISSUE THREAD

**Issue by Kamik423** [atom/autocomplete-plus#849]
Whey typing LaTeX I am encountering an error very similar to [this](https://github.com/atom/autocomplete-plus/issues/516).
```
\begin{descri<tab>}
```
,or an begin statement for that means, results in 
```
 \begin{\begin{description}
    
    \item[\end{\begin{description}]
\end{description}}
```
and
```
\sec<tab>
```
or any other one line statement, results in
```
\\section{section name}
```
This is very irritating and removes all autocomplete functionality for LaTeX

### Versions

```
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

autocomplete-plus: 2.35.3
```

### Additional Information

No latex completion package is currently enabled

**Comment by 50Wliu** [comment]
Assuming that you have the language-latex package installed, what you're encountering is something called "snippets".  This is intentional behavior - instead of typing `\sec`, just type `sec`.
