### ISSUE TITLE
Autocomplete working only on first char when suggestion list follows cursor

### ISSUE THREAD

**Issue by powdevel** [atom/autocomplete-plus#850]
Autocomplete+ is not showing suggestions. It only shows suggestions for the first key.
Even if the key or substring matches, it only show suggestions if it's only one character.
If I type ctrl+space doesn't show suggestions... but just for one letter.
The same happens indepently of the language: CSS, PHP, JS.
No errors, no warnings... nothing.
I have reproduced this behavior on safe mode too. I have disabled many modules to be sure it's not some kind of incompatibility.

**Repro Steps**
1. Open Atom. 
2. Open `config.cson`
3. Add the following setting:  
```
"autocomplete-plus":
    suggestionListFollows: "Cursor"
```
**Expected**:  Autocomplete works as you continue to type

**Actual**: Autocomplete should show up at your cursor and work as you type.  It does neither of these.

@affenwiesel, discover that the root cause of this is due to `suggestionListFollows: "Cursor"` in `config.cson`, which is a package setting in autocomplete-plus.  The default is set to `Word`.

NOTE: if you remove `suggestionListFollows: "Cursor"` from your config.cson autocomplete works as you type, but this is an issue when people set their setting to `Cursor`

ATOM 1.17
AUCOMPLETE PLUS 2.35.3
WINDOWS 10

Thanks for your help.

**Comment by powdevel** [comment]
Also, if I write in CSS, for example: bord
It will not show any suggestions. But if I hit spacebar and then backspace, it will show the suggestions list, and this suggestions list will collapse in the next keystroke, no matter if it matches one or more suggestions :(

**Comment by quchen** [comment]
Same issue: one letter shows a completion list, typing more (matching or non-matching) ones hides the list. This is a regression compared to Atom 1.16.

**Comment by DavOnGit** [comment]
Same to me, no errors. --safe mode on; i'm on windows 8 64 | Atom 1.17 | autocomplete-plus 2.35.3

**Comment by markwainwright** [comment]
Same is happening for me, with all the providers I use. Atom 1.17.0, macOS 10.12.3.

![](https://cloud.githubusercontent.com/assets/2290131/26260712/1232f70c-3c83-11e7-9b59-8bc5dec2679f.gif)

**Comment by affenwiesel** [comment]
Same here.  
Suggestions from snippets are shown only if just one character has been typed, whereas those from opened buffers are shown only if exactly three characters have been typed.
atom 1.17.0, atocomplete-plus 2.35.3. 

![autocomplete_issue](https://cloud.githubusercontent.com/assets/28846805/26287399/2c1be3f0-3e7b-11e7-8ddf-d853773dfbbc.gif)

**Comment by Pepello** [comment]
Me to.
Ubuntu 16.04 LTS, Atom 1.17.0 and autocomplete-plus 2.35.3

**Comment by collinjackson93** [comment]
I am also experiencing this problem. OSx 10.12.5, Atom 1.17.0, autocomplete-plus 2.35.3

**Comment by sdaitzman** [comment]
I am experiencing this issue as well. Is there any debug information I can provide? This is causing serious workflow disruption for me, and I'd like to help get it fixed.

**Comment by sdaitzman** [comment]
@markwainwright @50Wliu how can I help out?

**Comment by intijk** [comment]
cpp file confirmed not work also.

**Comment by affenwiesel** [comment]
Good news: I found a solution!
Removing the line  `suggestionListFollows: "Cursor"` from config.cson solved the issue for me!

**Comment by sdaitzman** [comment]
@affenwiesel thank you!!! I'd still love to see this fixed, as I prefer my completions to move with the cursor.

**Comment by powdevel** [comment]
Thanks @affenwiesel it finally worked 👍

**Comment by 50Wliu** [comment]
I can confirm that this worked using v2.34.2 (the version bundled with Atom 1.16) but broke in Atom 1.17.  Bisecting to see if I can find the commit...

**Comment by sdaitzman** [comment]
@50Wliu thank you for finding that! Anything I can do to help get it fixed?

**Comment by 50Wliu** [comment]
My brief investigation showed that `this.activeEditor` was equal to `editor` for every character past the first one, leading to an early return [here](https://github.com/atom/autocomplete-plus/blob/58025fee2fb055afed4b0a407c3d6a0d2c6fc2f3/lib/suggestion-list.js#L275).  However, that logic looks essentially the same as the version in v2.34.2, so maybe you could start by looking further up the chain.  Then, if you figure out the cause and fix it, feel free to submit a PR!

**Comment by preco21** [comment]
I can confirm this issue in safe mode in `Atom 1.18.0` and `macOS Sierra 10.12.5`:

![27277882-bb57a4f4-551a-11e7-9466-64889ad526aa](https://user-images.githubusercontent.com/4936201/27326072-69f9fb86-55e5-11e7-99a1-700f81fe50ab.gif)

This issue appeared after updating `Atom 1.18.0` from `Atom 1.16.0`.
