### ISSUE TITLE
Autocomplete not functioning for Atom 

### ISSUE THREAD

**Issue by rsese** [atom/autocomplete-plus#853]
*From @Mirageee on May 21, 2017 08:31*

Autocomplete doesn't work on newly downloaded Atom

I am new to atom. I just downloaded the application and had not done any forms of modification to it. These are the actions i did:
1. created a new file and named it something.html.
2. typed html and enter to create the html boilerplate code
3. within body tags, tried the following code but unable to have an autocomplete:

Typing p doesn't generate /p automatically
Typing form doesn't generate form class"" action"" method""
Typing body doesn't generate /body
Typing div doesn't generate /div

I tried installing on Windows but it does not work as well.

**Expected behavior: I expected the above autocompletes to occur when I finish typing the first tag

**Actual behavior: autocomplete doesn't occur

**Reproduces how often:100%

### Versions 1.17.0 x64 

I am running Mac 10.12.4

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

All the default packages for autocomplete are installed and running.

*Copied from original issue https://github.com/atom/atom/issues/14538*

**Comment by rsese** [comment]
*From @samuelrey on May 22 12:51*

What have you tried doing to solve the problem?

**Comment by rsese** [comment]
*From @Mirageee on May 22 06:07*

I've tried uninstalling and reinstalling twice on Mac, and tried installing the same on windows and it all didn't work. Tried disabling and re-enabling all autocomplete packages as well but didn't work. Followed an earlier thread clicking keybinder-->toggle, didn't work. Other than that I don't know what else I can do. Seek some advice from the experts here. Thank you.

**Comment by rsese** [comment]
@Mirageee - though it sounds like it's a new install, can you confirm if you see the same behavior in safe mode (exit all instances of Atom and run `atom --safe`)?

Also, can you share a GIF or screencast of the behavior you're seeing?

**Comment by 50Wliu** [comment]
@Mirageee does this only happen with HTML files or with all files?

For HTML in order to get autocomplete working you need to either have the `snippets` package enabled or to type the starting `<` first.  See this GIF:
![autocomplete-html](https://cloud.githubusercontent.com/assets/2766036/26330665/0eb1864e-3f1b-11e7-880a-0e4142db6180.png)

**Comment by markwainwright** [comment]
This may be the same bug as https://github.com/atom/autocomplete-plus/issues/850.

**Comment by Mirageee** [comment]
Hi all, I found the solution. Autocomplete works as long as I don't type the open bracket.

e.g.
instead of `<p>`, just type p.
instead of `<form>`, just type form.

This works well for me, hope it helps others who face the same issue. Thanks.

**Comment by chriszrc** [comment]
So running in safe mode made autocomplete on keystroke work again. So what does that mean for how I can approach fixes?

**Comment by FoteiniK** [comment]
...phew! Thank you @Mirageee,this almost droved me crazy! I thought it had to do with Linter which I had recently installed...

**Comment by Mkknowledge** [comment]
@Mirageee Thanks Buddy. was so simple

**Comment by CleverOscar** [comment]
@Mirageee you are a life saver! I thought I was the only one experiencing this issue!

**Comment by j-000** [comment]
it still does not work properly with dot notation...

**Comment by rsese** [comment]
Going to go ahead and close this since the issue author has gotten past their issue.   

@j-000 - if you're still having an issue, please create a new issue and fill out the issue template and we'll take a look.

**Comment by bhovic** [comment]
I have found out that if you don't save the new file with extension .html you wont get autocomplete turned on.

**Comment by vjnaudy** [comment]
> 
> 
> Hi all, I found the solution. Autocomplete works as long as I don't type the open bracket.
> 
> e.g.
> instead of `<p>`, just type p.
> instead of `<form>`, just type form.
> 
> This works well for me, hope it helps others who face the same issue. Thanks a ton. worked for me:)

**Comment by Deirdre18** [comment]
@Mirageee thanks for your great insight, works fine.

**Comment by trigueira** [comment]
Thank you @Mirageee!!

**Comment by MikeTunechi** [comment]
thank you @Mirageee

**Comment by jtkurth7** [comment]
Ah, I had the same problem. Thank you!

**Comment by AthusM** [comment]
> I have found out that if you don't save the new file with extension .html you wont get autocomplete turned on.

Thank you, solved my problem.
