### ISSUE TITLE
Unnecessary parentheses inserted when selecting completion in Clojure

### ISSUE THREAD

**Issue by WalterGR** [atom/autocomplete-plus#859]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unnecessary parentheses are inserted when selecting a completion in a Clojure file.

### Steps to Reproduce

1. Start Atom.
2. Open a Clojure source file.
3. Type `(ma`
4. This results in `(ma_)` in the file, with the cursor indicated by an underscore. 
5. A completion dropdown will be displayed, containing `map` for example.
6. Select a completion.

**Expected behavior:**

The text `ma` is replaced with the selected completion, for example `map`, leaving the file containing the following, with the cursor indicated by an underscore:

`(map _)`

**Actual behavior:** 

The text `ma` is replaced with the selected completion, and additional parentheses are inserted around the S-expression, leaving the file containing:

`((map _ ))`

(Notice that an extra space has also been inserted...)

**Reproduces how often:** 

Always.

### Versions

> atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

> apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.11.0

**Comment by 50Wliu** [comment]
This is because you are triggering a snippet, which [explicitly includes parentheses](https://github.com/atom/language-clojure/blob/bcba97a0c4e358f05873adfd8030f32f8084a239/snippets/language-clojure.cson#L83).  The correct way to trigger this snippet is to write `map` without parentheses.
