### ISSUE TITLE
In `.scss` files, `@e...` autocompletes to `@@extend`, so you have to go back and delete the superfluous `@`.

### ISSUE THREAD

**Issue by marcdavi-es** [atom/autocomplete-plus#866]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In `.scss` files, `@e...` autocompletes to `@@extend`, so you have to go back and delete the superfluous `@`.

I'd love to open a PR to fix this myself, but I don't know which repo the code lives in?

### Steps to Reproduce

1. Open up a `.scss` file. 
2. Start typing `@e`.
3. Hit enter to trigger autocomplete for `@extend`.
4. Wince as the autocomplete leaves an extra `@` at the front.

**Expected behavior:** Autocompletes to `@extend`

**Actual behavior:** Autocompletes to `@@extend`

**Reproduces how often:** 100%

### Versions

Atom 1.18.0
macOS Sierra 10.12.4

**Comment by 50Wliu** [comment]
This is intentional - you are using a feature called snippets.  All snippets have prefixes that expand when you select them - the `extend` snippet expands into `@extend `.
