### ISSUE TITLE
Limit the height of the description container element of a completion proposal

### ISSUE THREAD

**Issue by BoykoAlex** [atom/autocomplete-plus#870]
### Description

My completion proposals have a lot of text in the `description` or rather `descriptionMarkdown` field. Since there is no `max-height` CSS style (and other related CSS attributes `overflow-y` etc) the height on `suggestion-description` the description may become very long in y direction. Layout of the `suggestion-description` and `suggestion-description-content` should be tweaked and be scrollable.

**Expected behavior:** height for the description `div` should be the same as the proposals list `div`

**Actual behavior:** Description element becomes tall even goes off screen to fit all the description text. No scrollbar.

**Reproduces how often:** If documentation field is a long string
### Versions
Atom 1.18

**Comment by BoykoAlex** [comment]
PR: https://github.com/atom/autocomplete-plus/pull/874

**Comment by simurai** [comment]
PR https://github.com/atom/autocomplete-plus/pull/874 got merged and should be in `Atom 1.20`.

@BoykoAlex Thanks 🙇
