### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by diegogPlayStudios** [atom/autocomplete-plus#884]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.5

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:46

TypeError: Cannot read property 'add' of null
    at Object.getAutocompleteManager (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:46:31)
    at Immediate.setImmediate (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:35:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -3:45.1.0 core:backspace (input.hidden-input)
     -3:20.8.0 core:confirm (input.hidden-input)
  5x -2:16.1.0 core:backspace (input.hidden-input)
     -0:38.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-jade 0.3.0 
pigments 0.40.2 
spacegray-atom-dark-syntax 1.3.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by rsese** [comment]
Do you have `_` in `Settings > Editor > Non Word Characters`?  If so you're running into https://github.com/atom/autocomplete-plus/issues/956 which was just fixed in https://github.com/atom/autocomplete-plus/pull/961.  The fix will be available in a future release.

**Comment by cjfloresalonso** [comment]
You thug. Thanks!

**Comment by rsese** [comment]
Glad that was the issue you were seeing @cjfloresalonso :+1:

Thanks again for your issue @diegogPlayStudios - we haven't received a response to our question in this comment https://github.com/atom/autocomplete-plus/issues/884#issuecomment-327069878. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
