### ISSUE TITLE
unable to install any package on atom

### ISSUE THREAD

**Issue by abhilashmental1** [atom/autocomplete-plus#891]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

package installation is failing every time .
### Steps to Reproduce

1. opened in safe mode and tried installing
2. deleted every bit of atom and tried to install
3. [and so on...]

**Expected behavior:** expected to install the package

**Actual behavior:** installation failing

**Reproduces how often:** every time (100%
![packa](https://user-images.githubusercontent.com/32108705/30630092-b281d2c0-9dfc-11e7-8a2f-8fa13d814d05.png)
)

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
This issue definitely doesn't belong on the autocomplete-plus repository.  Please move it to the atom/apm repository instead.
