### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by kghanta** [atom/autocomplete-plus#894]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [autocomplete-plus](https://github.com/atom/autocomplete-plus) package 2.35.7

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At C:\Users\Kranthi Ghanta\AppData\Local\atom\app-1.20.1\resources\app\node_modules\grim\lib\grim.js:56

TypeError: deprecationSite.getFileName is not a function
    at Object.deprecate (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/grim/lib/grim.js:56:42)
    at ProviderManager.registerProvider (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/autocomplete-plus/lib/provider-manager.js:297:22)
    at requireAutocompleteManagerAsync (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/autocomplete-plus/lib/main.js:110:69)
    at Immediate.setImmediate (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/autocomplete-plus/lib/main.js:37:17)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
```

### Non-Core Packages

```
MavensMate-Atom 1.1.0 
nuclide 0.184.0 
nuclide-format-js 0.0.36 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

Also, based on https://github.com/atom/atom/issues/15088 I think this may be an issue with Nuclide so would be great to know if you can reproduce in safe mode.

**Comment by K4zuki** [comment]
Hello,

Same error happened to me too.

- Atom 1.19.1
- Windows 7 64bit
- I was typing a date `26-Oct-2017` in a yaml file
    - delete `7` and retype causes error. Reproducible.
- `atom --safe` fixed the error

Hope this helps

**Comment by rsese** [comment]
Thanks @K4zuki :+1:

> atom --safe fixed the error

This likely means a community package you have installed is causing the problem.  One way to narrow things down is to disable all installed packages and then enable one-by-one. Or if you have a lot of installed packages, https://atom.io/packages/package-cop might be helpful too. 

And thanks again for your issue @kghanta!

We haven't received a response to our question in this comment https://github.com/atom/autocomplete-plus/issues/894#issuecomment-333219229. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
