### ISSUE TITLE
Should autocomplete never return the word you typed as a suggestion?

### ISSUE THREAD

**Issue by leroix** [atom/autocomplete-plus#901]
![screen shot 2017-10-06 at 12 34 22 pm](https://user-images.githubusercontent.com/520209/31293011-e6716256-aa92-11e7-9aad-5d1fcbba25f4.png)

In some situations, autocomplete returns the word you've already typed as a suggestion. I believe this happens when the word occurs more times than just the number of times it appears under cursors.

The proposed change would be that ac+ never returns the word you've typed as a suggestion.

There may be some edge-cases to consider like, "how should this behave when there are multiple cursors?"

/cc @nathansobo

**Comment by nathansobo** [comment]
My position is that we shouldn't ever suggest the word you have just typed. The whole point is of the menu is to provide *completions*, but you don't need a completion for the word you just typed. It seems like it could simplify the package to just always filter out the word preceding the cursor that is associated with the menu.
