### ISSUE TITLE
Computer freeze when using Subsequence as default provider

### ISSUE THREAD

**Issue by lexcast** [atom/autocomplete-plus#918]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When typing fast a few words Atom starts to increase the cpu and memory usage until the computer freezes.

### Steps to Reproduce

1. Select on Settings > Packages > Autocomplete Plus > Default Provider the Subsequence option
2. Open a file
3. Start typing fast

**Expected behavior:** Type as normal

**Actual behavior:** Computer freezes

**Reproduces how often:** 100%

### Versions

Atom    : 1.23.0-beta0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.10
npm  3.10.10
node 6.9.5 x64
atom 1.23.0-beta0
python 2.7.14
git 2.14.1

Ubuntu 17.10
Windows 10

### Additional Information

Using the Symbol provider option seems to fix the issue.

**Comment by 50Wliu** [comment]
Thanks for the issue.  We're aware of this and are actively investigating.

(Also, I sent you a Discuss message just now about something completely unrelated if you wouldn't mind replying to it :))

**Comment by leroix** [comment]
This should be fixed in 1.22.1 and 1.23.0-beta1 by https://github.com/atom/superstring/pull/44 and https://github.com/atom/superstring/pull/45.
