### ISSUE TITLE
Can't autocomplete words with dashes in CSS

### ISSUE THREAD

**Issue by jasonrudolph** [atom/autocomplete-plus#922]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In CSS and SCSS grammars, words with dashes don't appear in the list of autocomplete suggestions.

### Steps to Reproduce

1. Open a buffer and set the grammar to `CSS`
1. Paste in the following content:

    ```css
    .foo--open {
      font-size: 42em;
    }

    div .fo
    ```

1. Put your cursor at the end of the last line and trigger autocomplete (i.e., `autocomplete-plus:activate`)

**Expected behavior:** `foo--open` should appear in the list of autocomplete suggestions

**Actual behavior:** `foo--open` does not appear in the list of autocomplete suggestions

  ![screen shot 2017-11-15 at 9 08 28 am](https://user-images.githubusercontent.com/2988/32840550-f8d18486-c9e5-11e7-8170-9383060a7242.png)

**Reproduces how often:** 100%

### Versions

macOS 10.13.1

```
$ atom --version
Atom    : 1.24.0-dev-6227ecebe
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.10
npm  3.10.10
node 6.9.5 x64
atom 1.24.0-dev-6227ecebe
python 2.7.10
git 2.15.0
```

### Additional Information

I _think_ this is a recent regression with the last several weeks.

/cc @leroix @maxbrunsfeld: This is the issue I mentioned in our discussion on Monday. If there's any additional info that would be helpful, just let me know. :bow:

**Comment by 50Wliu** [comment]
Can't tell for certain but #916 looks similar.

**Comment by leroix** [comment]
fixed
