### ISSUE TITLE
autocomplete css class selector doesn't work with hyphens after update

### ISSUE THREAD

**Issue by kaiser-jakob** [atom/autocomplete-plus#931]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since the last update autocomplete plus doesn't show css selectors while typing in html document if there is a hyphen in the class name.

### Steps to Reproduce

1. create basis index.html document and create a div with attribute 'class'
2. create and link a style.css or write css in the head of the previously created index.html
3. create the classes .white-error, .white and .white_primary
4. in the div add a selector to class by starting to type 'whi'

**Expected behavior:**

that autocomplete plus suggests all three classes as it dit before updating atom

**Actual behavior:**

autocomplete plus suggests 'white' and 'white_primary' but NOT 'white-primary'

**Reproduces how often:** 

100%

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.6

macOS 10.12.6

### Additional Information

tried all the debugging steps. also reset of atom and starting like newly installed.

**Comment by leroix** [comment]
Should be fixed by #928. I'm not sure if this will make it into 1.23 (possibly?), but it will definitely be in 1.24.

**Comment by rsese** [comment]
Looks fixed in 1.24.0-beta2, going to go ahead and close - let us know if you still see a problem @kaiser-jakob and thanks for reporting :v:

**Comment by arnaudthuillier** [comment]
Hello,

Sorry to dig this out, but I encounter the exact same issue.
Same if I run Atom in safe mode.

Windows 10
Atom 1.33.0

So weird as it was already reported and fixed.

**Comment by rolandixor** [comment]
I don't remember what the setting was I had to change, but I was able to fix it by fiddling with my settings a bit. I'm sorry I don't remember what the specific setting was though.

**Comment by timofo** [comment]
@rolandixor @arnaudthuillier - I could solve this behaviour by deleting the "-" in the editor settings under "Non Word Characters".
