### ISSUE TITLE
a tag does not autocomplete in some specific cases

### ISSUE THREAD

**Issue by rodrigoyoshida** [atom/autocomplete-plus#932]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The autocomplete feature does not work in some specific cases. It is easy to reproduce the bug.

### Steps to Reproduce

- Open a new file
- Save with .html extension
- Open a `<p>` tag (happens with h1 and other tags too)
- Type "a" between the `<p></p>` tags, the autocomplete shows the suggestion to the `<a>` tag
- Tries to accept it by pressing enter or tab

**Expected behavior:** [What you expect to happen]

The `a` autocompletes and the popup is dismissed.

**Actual behavior:** [What actually happens]

Nothing happens.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
atom -v
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm -v
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.2
python 2.7.10
git 2.14.3
```

macOS 10.12.6.

### Additional Information

See https://github.com/atom/autocomplete-plus/issues/932#issuecomment-355177403 for GIFs of the behavior from different Atom versions.

*Edited by @rsese to use the issue template*

**Comment by Aerijo** [comment]
I could reproduce this with just `<p`, as it wouldn't complete (even though the option was there). However, I think this is probably an [`autocomplete-html`](https://github.com/atom/autocomplete-html) issue.

**Comment by sanada01** [comment]
Did you find the bug here? :)

**Comment by rsese** [comment]
I'll ask the team to take a look, dropping some of my findings below:

In 1.20.1, if you type `a` between `<div></div>` you get just the snippet which works fine if you select it.  If you type `<a` you get autocomplete and if you select `a` and the popup will dismiss.

![autocomplete-1 20 1](https://user-images.githubusercontent.com/734194/34546753-b64d1858-f0bb-11e7-8349-ea125d9277c0.gif)


1.21.2, if you type `a` you get the snippet and autocomplete:

![autocomplete-1 21 2](https://user-images.githubusercontent.com/734194/34546858-72a9f98a-f0bc-11e7-814a-594148ed79d3.gif)

Snippet works fine but selecting autocomplete `a` won't dismiss the popup though selecting other options seem to work (in the GIF I select `abbr` and that autocompletes and dismisses the popup).  If you type `<a`, the behavior is the same, selecting `a` won't dismiss the popup but other options will.

1.23.2, if you type `a` you get just the autocomplete:

![autocomplete-1 23 2](https://user-images.githubusercontent.com/734194/34546815-2bfacb86-f0bc-11e7-8850-4debba8a49f5.gif)

Behavior is the same as 1.21.2 and the same if you type `<a`.

**Comment by rsese** [comment]
Yes the issue is still open so it's not resolved yet - with [the work](https://github.com/atom/atom/issues?q=is%3Aopen+is%3Aissue+label%3Aiteration-plan) the team has on their plate it's not something that's been prioritized unfortunately.  We're happy to review well-written pull requests however.

**Comment by amaau** [comment]
i have the same situation in completing react properties. it seems also to depend on how much of the word i enter:

"<div clas[sName]" completes well,
but
"<div classN[ame]" just causes the suggestions to disappear, and nothing gets replaced / completed.

with "className" attribute it works just when 4 chars were entered, less or more don't work.
with "onBlur" attribute, only onb[lur] works, that is 3 characters. onbl[ur] does nothing.

suggestions always show up correctly, but when confirming, it either works or not.

**Comment by fabrem** [comment]
ffs when are we going to be able to autocomplete nested tags:(

**Comment by fabrem** [comment]
Hope this will get fixed soon!!

**Comment by sanada01** [comment]
Did you fix it? :) Really looking forward to.

**Comment by mulder-brewing** [comment]
It's really weird.  It seems to work for me until i save and close the file.  When I reopen it, autocomplete in nested tags no longer works.  This is a deal breaker for me.  I'm really liking atom but man is that annoying.

**Comment by sanada01** [comment]
Can you watch it this bug? The original post created 2017 nov 22. :'(
