### ISSUE TITLE
Letter next to autocomplete?

### ISSUE THREAD

**Issue by jmangz** [atom/autocomplete-plus#933]
<img width="342" alt="screen shot 2017-11-29 at 2 50 55 pm" src="https://user-images.githubusercontent.com/11446685/33396365-4bef465e-d516-11e7-90b5-545a609867c2.png">
<img width="327" alt="screen shot 2017-11-29 at 2 44 22 pm" src="https://user-images.githubusercontent.com/11446685/33396366-4bfe2796-d516-11e7-99d7-8ca8138e5aeb.png">
What's the letter next to the autocomplete that shows up sometimes? I thought it might be for function in the case of the screenshots, but it doesn't always show.

**Comment by leroix** [comment]
@jmangz the letter shows when we're able to determine the symbol type from the language package config for the language you're currently using. `f` stands for function, `v` for variable, `m` for method, `c` for class, etc.

**Comment by jmangz** [comment]
Just wondering, is there a reason you aren't always able to determine what it is?
