### ISSUE TITLE
The automatic dropdown closes too quickly

### ISSUE THREAD

**Issue by Leva7** [atom/autocomplete-plus#945]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The autocomplete dropdown window that appears automatically seems to disappear too quickly. The problem is particularly in the fact that any action (such as moving to the next suggestion in the list) does not prolong this timeout. Therefore, if the autocompletion suggestion that I want is at the bottom of the list, I simply fail to scroll to it in time.  
When opening the dropdown manually (Ctrl-Space) it seems to stay for as long as needed.

What I'd like to be done is one of the following:
* Allow setting a custom timeout for the automatically opened dropdown
* Allow a change in selection to disable the timeout (e.g. quickly tapping the Down arrow would make the autocomplete dropdown permanent until selection). Kind of like GRUB OS Selector stops the timeout if you make a keypress, if you're familiar with it.

I'd love to help out with this but looking through the code I couldn't seem to find anything related to this issue. Could you maybe point to the piece of code that's responsible for this behaviour? Or is it not the `autocomplete-plus` package's fault, but rather the `atom-overlay` component's?

### Steps to Reproduce

1. Type something into the editor so that an autocompletion dropdown appears
2. Move down one entry in the list

**Expected behavior:** I expect the dropdown to stay and let me make my choice

**Actual behavior:** It disappears after a certain timeout

**Reproduces how often:** Every time

### Versions
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.12
git 2.7.4
```
Running Ubuntu 16.04

**Comment by rsese** [comment]
Thanks for the report - I'm unable to reproduce this on Ubuntu 16.04 and Atom 1.23.3, the dropdown doesn't disappear using your repro steps (though you don't mention how long it takes before it disappears for you?).  Can you share a GIF/screencast that shows this behavior in safe mode?

> Could you maybe point to the piece of code that's responsible for this behaviour? Or is it not the autocomplete-plus package's fault, but rather the atom-overlay component's?

I'm not sure what code is responsible but if we can get a reproduction, we'll ask the team to take a look.

**Comment by Leva7** [comment]
@rsese Guess my lies are uncovered now - I really did not expect a package to cause such an issue so I didn't bother trying Safe Mode, but guess what - the problem does not occur there. 

And I did find what package was responsible for this issue - [`atom-idle-autosave`](https://github.com/pvorona/atom-idle-autosave)
Thanks for the help. I'll see what I can do from there :)

**Comment by Chinwike1** [comment]
Please can anyone give a well detailed and understandable answer to this question. I've been browsing the whole Internet trying to find how to make my autocomplete suggestion popup last and not disappear immediately I want to select an option. How is this possible please? Most people are just identifying the problem and not giving any solutions. If you have a solution please share.

**Comment by illright** [comment]
@Chinwike1 the problem is: the dropdown is closed when the document is saved, unless it was an autosave made by [this](https://atom.io/packages/autosave) package (which is bundled with Atom).
So the way to work around this problem is to change the source code of this package to [set the `autosaveEnabled`](https://github.com/atom/autocomplete-plus/blob/master/lib/autocomplete-manager.js#L188) based on the config of [`atom-idle-autosave`](https://github.com/pvorona/atom-idle-autosave)

**Comment by jt3748** [comment]
I figured it out!

Click Atom (next to File) and select Keymap... and paste the following:

'atom-text-editor':
  'alt': 'autocomplete-plus:activate'

and just change the 'alt' to whatever command you want! 
booyah! only took me all day

**Comment by AndrewMacmillan87** [comment]
**@jt3748** this is not working for me, I am new to Atom and have just noticed this issue, I am using version 1.34.0. Has any progress been made on this because it's really effecting the usability of the editor

**Comment by jt3748** [comment]
Sorry but it worked for me. Im new too so im not much help. Good luck brother

**Comment by hudacse6** [comment]
still unable to solve. lets try again.

**Comment by nm17** [comment]
For anyone having this problem still, UNINSTALL `atom-idle-autosave`. Disabling doesn't work.

**Comment by ayala79** [comment]
Thank you **nm17** !
It worked :)
