### ISSUE TITLE
Autocomplete not working with numbers

### ISSUE THREAD

**Issue by AlbinDaleby** [atom/autocomplete-plus#950]
As soon as I enter a number into autocomplete the windows disappears.

Here's a gif: 
![autocompletenumber](https://user-images.githubusercontent.com/11645355/35618740-23c95e52-067c-11e8-9e73-ddea22fc0755.gif)

In the above gif I want the all the words as suggestions when I type `lorem1`.

I've tried it in safe-mode and it does not work there either.
I'm pretty sure this has worked in the past.

**Comment by Aerijo** [comment]
@AlbinDaleby I found the problem. The function [`getPrefix`](https://github.com/atom/autocomplete-plus/blob/8f192dc3d8d5c19cf111db122d1697c7a0774aa0/lib/autocomplete-manager.js#L492-L506) will return an empty string if the last character is a number. This is because the regex used does not seem to include numbers. Whether this is by design, I'm not sure. As it is though, I cannot see a setting to customise this. A PR will have to be made to either include numbers always, or make it configurable.

**Comment by AlbinDaleby** [comment]
Thanks @Aerijo . I can see that `getPrefix` code was changed 29 days ago in [this commit](https://github.com/atom/autocomplete-plus/commit/c40cce6a08cf9df7f616ffa6b6b217eae7808664) by @nathansobo and @maxbrunsfeld . Maybe they implemented / can implement a way to customise this.

**Comment by Aerijo** [comment]
@AlbinDaleby For a quick fix, you can download a clone of this repo somewhere on your computer, navigate in a terminal to inside the folder, and run the command `apm link`.

Once linked, go to `lib/autocomplete-manager.js`, and down to line 513 (it's inside the function `getWordCharacterRegex`, just below the one I link to above).

Replace this line with the following:
```js
regex = new RegExp(`[${UnicodeLetters}${additionalWordChars.replace(']', '\\]')}\\d]`)
```

The difference is the `\\d` added near the end. This will allow matching all digits.

**Comment by maxbrunsfeld** [comment]
This was not an intentional change. We’d definitely merge a PR fixing it, or we can do it after this week of meetings. My apologies @AlbinDaleby

**Comment by AlbinDaleby** [comment]
@maxbrunsfeld No problem. I'll wait for the update.

**Comment by AlbinDaleby** [comment]
Closing the issue was not intentional..

**Comment by ungb** [comment]
@AlbinDaleby would you be willing to create a PR for this?

**Comment by AlbinDaleby** [comment]
@ungb This is not as urgent for me anymore. I created a workaround for my specific problem. Maybe I'll look into this when I get some time over.

**Comment by collinstocks-oscar** [comment]
Is there a plan for moving forward on this? It seems to be causing an issue in at least one other autocomplete provider (see above).

**Comment by coderforlife** [comment]
This also effects just getting identifiers with numbers in them, I have a lot of P3XXX types for Polyhedron3 and it just completely ignores everything before the 3, usually causing a double-print of it. I have even added 0123456789 as word characters with no change.

**Comment by IJustMadeThis** [comment]
Is the fix @Aerijo noted in lib/autocomplete-manager.js all that's needed here?  I'm going to try my first PR :-)
