### ISSUE TITLE
Beancount accounts

### ISSUE THREAD

**Issue by ludenticus** [atom/autocomplete-plus#951]
Hi. I'm trying to use Atom for editing beancount files, but one thing I miss is the auto-completion of accounts. For instance, an account such as `Assets:Banks:US:BofA:Savings` isn't recognized: you just have `Savings` or `Assets`, but not the whole expression. A common entry would be like this:

```
2018-01-31 * "Payee" "Narration"
 Expenses:Home:Gas     32 USD
 Assets:Banks:US:BofA:Savings   -32 USD
```

Is it possible to auto-complete accounts?

**Comment by 50Wliu** [comment]
Adding `:` to `Extra Word Characters` in `autocomplete-plus`'s settings (Settings -> Packages) should do the trick.

**Comment by ludenticus** [comment]
Well, I guess I'll have to wait. Version `1.23.3` doesn't have this option yet. Thanks

**Comment by ludenticus** [comment]
Version `1.24.0` doesn't have either the `Extra Word Characters` setting.
