### ISSUE TITLE
Autocomplete doesn't help with custom CSS Variables

### ISSUE THREAD

**Issue by oyekanmiayo** [atom/autocomplete-plus#952]
Hello, please when I declare a custom variable in the :root selector, the autocomplete-plus package doesn't help with autocompleting when I try to call the defined variable in another section of the code.

What can I do to get it to work?

See screenshots below:
![declared variables](https://user-images.githubusercontent.com/26260543/35669259-c7274754-0734-11e8-85fc-df070820acc7.png)

![calling declared variables](https://user-images.githubusercontent.com/26260543/35669335-0a30b422-0735-11e8-92bf-b38539ed2609.png)

Thank you.

**Comment by Aerijo** [comment]
@oyekanmiayo For CSS specific completions, I recommend asking on [`autocomplete-css`](https://github.com/atom/autocomplete-css).

**Comment by oyekanmiayo** [comment]
@Aerijo Thank you, I'll do just that.
