### ISSUE TITLE
[tree-sitter] Autocomplete not working for ide-* packages

### ISSUE THREAD

**Issue by lgeiger** [atom/autocomplete-plus#962]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * ~~Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode~~
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This issue only appears when using `tree-sitter`.
When using the experimental `tree-sitter` parser together with a [language server package](https://github.com/atom/atom-languageclient#official-packages), autocomplete requests aren't triggered.

I was able to reproduce this with [`ide-python`](https://github.com/lgeiger/ide-python) and [`ide-typescript`](https://github.com/atom/ide-typescript).

It seams that [`getSuggestions`](https://github.com/atom/atom-languageclient/blob/master/lib/auto-languageclient.ts#L451) in the language-client isn't triggered so I'm posting this issue here.

@damieng @maxbrunsfeld Any idea what's happening here? Keep up the great work 💯 

### Steps to Reproduce

1. Configure Atom to use experimental `tree-sitter` parser
2. Open project/file with grammar matching a installed language server plugin
3. Verify that the language server is running (linting, hover, outline, ...)
3. Type a few characters which should trigger a autocompletion suggestion

**Expected behavior:** Autocompletion should be provided

**Actual behavior:** No ide autocompletion

**Reproduces how often:** 100%

### Versions

Reproducible on macOS and:
```shell
> atom-beta --version
Atom    : 1.26.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
> atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by damieng** [comment]
Can you confirm you are using the latest version of ide-typescript?  This was fixed in https://github.com/atom/ide-typescript/releases/tag/v0.7.6

**Comment by lgeiger** [comment]
Yes I'm using `ide-typescript@v0.7.6`. `ide-python` is also using `atom-languageclient@0.9.4`

**Comment by damieng** [comment]
Can you open a typescript file then open the dev tools window and type

`atom.workspace.getActiveTextEditor().getGrammar().scopeName`

and report back here the result? Thanks.

**Comment by damieng** [comment]
Never mind, I'm able to repro and I see the issue :)  Fix going out tonight.

**Comment by damieng** [comment]
https://github.com/atom/atom-languageclient/commit/859d5c8a78a232516a7067c9bee30cd88191bf22

**Comment by damieng** [comment]
Out in 0.9.5

**Comment by lgeiger** [comment]
Thanks for the fast fix. This `v0.9.5` works great!
