### ISSUE TITLE
Enable a subsequence spec that should be enabled

### ISSUE THREAD

**Issue by Arcanemagus** [atom/autocomplete-plus#964]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This spec has a `TODO` to be re-enabled once Atom v1.22.1 was released... which happened quite a while ago 😉.

https://github.com/atom/autocomplete-plus/blob/c86c3fb27f5e7cf102f48db51772d7fc055ddf44/spec/subsequence-provider-spec.js#L483

### Steps to Reproduce

1. Look at code for this package
2. See commented out spec.
3. Profit?

**Expected behavior:** [What you expect to happen]

Specs that should be enabled are enabled.

**Actual behavior:** [What actually happens]

A spec isn't enabled that should be.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Versions

OS: Windows 10 x64 Enterprise
```
Atom    : 1.26.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0-beta1
python 2.7.14
git 2.17.0.windows.1
visual studio 2015
```

### Additional Information

This spec was added in a commented out state in https://github.com/atom/autocomplete-plus/pull/921.

**Comment by lee-dohm** [comment]
@daviwil Can you take a quick look?
