### ISSUE TITLE
Lack in your documentation

### ISSUE THREAD

**Issue by ShiftcodeDream** [atom/autocomplete-plus#966]
Hello, in your documentation, you wrote "autocomplete+ has a powerful autocomplete provider API. You should definitely install additional providers (the default provider bundled with this package is somewhat crude)"

But you never explain how to do that !!! Please make Atom easy to use and documentation accurate. If the user has to spend hours to configure his text editor, it would change his editor for another one, simpler to use immediately.

**Comment by Aerijo** [comment]
Any of the packages called `autocomplete-*` should be providers. There are also some that aren't called this, but if it does autocomplete, it's probably a provider for this package.

**Comment by thomasjo** [comment]
@ShiftcodeDream The documentation paragraph you're citing ends with a link to https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers. That wiki page is a community curated list of Autocomplete providers.

Furthermore, the official Atom documentation has a separate section specifically related to installing and configuring packages — https://flight-manual.atom.io/using-atom/sections/atom-packages/
