### ISSUE TITLE
Subsequence autocompletion bugged in Atom 1.27.0.

### ISSUE THREAD

**Issue by tristanbiesecker** [atom/autocomplete-plus#970]
### Description

After the update to 1.27.0, autocompletion of my CSS code no longer works; specifically, Atom won't suggest any autocompletions for my CSS classes while I'm editing my HTML files.

I have determined that the issue is related to the Default Provider for **autocomplete-plus**. If the Default Provider is **Subsequence**, autocompletion no longer works. However, if I switch back to **Symbol**, autocompletion seems to work again (at least for CSS, I haven't tested my other languages).

#### Update 1

I have tested my other languages and **Symbol** works for them as well. Still no dice for **Subsequence** though.

### Versions

1.27.0 x64 on Mac

**Comment by rsese** [comment]
Thanks @tristanbiesecker - without specific repro steps it's not clear, but are the CSS classes that aren't auto-completing for you hyphenated?
