### ISSUE TITLE
Autocomplete inserts what I started to type as well as what gets matched

### ISSUE THREAD

**Issue by GalacticSun** [atom/autocomplete-plus#982]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Autocomplete inserts what I started to type as well as what gets matched

### Steps to Reproduce

1. Start typing an auto-completable word.
2. Autocomplete pops up the completion.
3. Hit Enter or Tab to complete it.
4. Both the text I typed to get the match to popup, and the matched word gets inserted.

**Expected behavior:** It should not insert the same part of the matched word twice.

**Actual behavior:** The first part of the matched word that I typed should not be inserted, only the match.

**Reproduces how often:** 100%

### Versions

1.28.1

### Additional Information

I fixed this before, but now I'm on a new computer and need to fix it again but I can't remember exactly what I did, but I know it was a code change somewhere in the autocomplete package.  I've searched online but can't find it again.  Plz help!  Thanks.

**Comment by Aerijo** [comment]
@GalacticSun Can you please provide an example you know to fail. As it is, I cannot reproduce. Here are my steps:
-  On any blank file, type `abcde` 
- Press space and type `abc`
- Confirm the suggested `abcde`, and the remaining `de` is completed.

**Comment by GalacticSun** [comment]
Every single one, for me.  I also have the autocomplete-php package installed.  Maybe that is part of the problem?  Like I mentioned in the post, I ran into this before and fixed it, I just can't recall exactly how, though.

**Comment by GalacticSun** [comment]
Actually, this appears to be an issue with the autocomplete-php package https://github.com/Azakur4/autocomplete-php/issues.  I'll close this.
